### ISSUE TITLE
Adding fields to reports

### ISSUE THREAD

**Issue by hougaard** [hougaard/Simple-Object-Designer#1]
Support for adding fields to reports will hopefully come with v18 in late april.

**Comment by GrooveRings** [comment]
I have a question regarding this enhancement. Would this give us the ability to add custom fields created in BC to RDLC reports like a sales invoice document that we email to our customers? Or would that be another enhancement? Or does this option already exist? Thanks for creating such a wonderful app to BC!

**Comment by hougaard** [comment]
Yes, it will!

I have a version running here where I have added fields to sales order and sales invoices, and added that field to the dataset of order confirmation, sales order, invoice and a few more reports. 

After this is it a simple operation with **Custom Report Layout** to add the field to the layout of the report.

So a three-step:
1. Add fields to tables
2. Add fields to reports
3. Editing custom report layout to place the fields on paper.

This awaits the availability of v18, my guess is that it will be released within 2 weeks.

**Comment by GrooveRings** [comment]
That’s where I’m stuck. How do I add the new field to the dataset for the RDLC report layout? Thank you for your quick response!

**Comment by hougaard** [comment]
In 2 weeks you can do it with this app :) (If your tenant is on v18 at that time)

**Comment by szenzi** [comment]
Hi Erik!

In future there will be possible to add a flowfield with your app?
For example if I like to see on the 5806 page the vendor name, 1st i have to add the vendor name to the 121 table - it's be a very useful thing if this will be available later!
Thx,
Balazs

**Comment by igorkovski** [comment]
Hi Erik,
I was contemplating purchasing the extension but I wasn't sure whether this feature has been added to the current version of the software. I added the demo app to my sandbox environment, but the report feature doesn't seem to work. I'm assuming it's because I'm running this in the demo environment?...My production environment is currently v18.2.26 tenant.
Thanks!

**Comment by hougaard** [comment]
Adding fields to report are in the v2 of the app, that should work. Are you getting errors?

**Comment by igorkovski** [comment]
It seems I don't have any options available to me in the sandbox environment. I wanted to test out some features in the sandbox environment before doing it in production.

**Comment by hougaard** [comment]
What version of the designer do you have installed?

**Comment by igorkovski** [comment]
v2.0.0.45

**Comment by hougaard** [comment]
After you create the new field, can't you click in the "placed on reports" column?

**Comment by igorkovski** [comment]
Hi Erik,

I got it to work, however I can't seem to be able to add an existing field in the Sales Header (SellToContact) so that it shows up in the report as part of the dataset.
