### ISSUE TITLE
Field Created on Ship-To need to add to pages

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#10]
Hello Erik,

I created a field on Ship-To Address table 222 and added it to page 300 and list 301. I also want this field with its data entered from Ship-To address to be visible on the the sales order header page.

However when adding the field and going to place on pages or field transfers I have no option to do so.

Is there anyway for me to achieve what I would like to do?

**Comment by hougaard** [comment]
Hi Scott,

Version 1.0.0.49 supports 222->36 fields transfers. (Will be live in AppSource in the coming week).

**Comment by ScottB-Ronco** [comment]
Erik,

First thank you update the app per my request.

Now in below email you mentioned Version 1.0.0.49, but the version I have and also that which is currently on AppSource is v2.0.0.47. Is the version # you provided a typo if not will this not cause problems?

Thank you,



***@***.***

***@***.***<http://>
***@***.***

Scott Berg
IT Manager
P  905.660.6700 ext 1242
E  ***@***.***
W www.roncosafety.com
***@***.******@***.******@***.******@***.******@***.***<https://www.youtube.com/user/roncocanada>
***@***.***<https://bit.ly/3i4VoX7>

**Comment by hougaard** [comment]
Looks like it's not live yet...

**Comment by hougaard** [comment]
It's live now.

**Comment by ScottB-Ronco** [comment]
Erik,

I downloaded the new version and was able to pass the field data through transfer and then added it to page 42 sales order.

However when I made the field read only it greyed out the box but the text is really light and can be hard to read, if I take read only off it is more visible but then users could accidently change the value which we don’t want.

Look at the screen shot below where with our support partner they added a field called Customer Min Freight it is in a bolder green font. Is it possible to do this in your app?

***@***.***

Thank you,



***@***.***

***@***.***<http://>
***@***.***

Scott Berg
IT Manager
P  905.660.6700 ext 1242
E  ***@***.***
W www.roncosafety.com
***@***.******@***.******@***.******@***.******@***.***<https://www.youtube.com/user/roncocanada>
***@***.***<https://bit.ly/3i4VoX7>

**Comment by ScottB-Ronco** [comment]
Erik,

Could I have a follow up to the below please?

Is what I requested below about the font possible in your app?

Thank you,



***@***.***

***@***.***<http://>
***@***.***

Scott Berg
IT Manager
P  905.660.6700 ext 1242
E  ***@***.***
W www.roncosafety.com
***@***.******@***.******@***.******@***.******@***.***<https://www.youtube.com/user/roncocanada>
***@***.***<https://bit.ly/3i4VoX7>


From: Scott Berg - Ronco
Sent: Wednesday, August 11, 2021 3:43 PM
To: Erik Hougaard ***@***.***>; ***@***.***
Cc: Author ***@***.***>; hougaard/Simple-Object-Designer ***@***.***>; hougaard/Simple-Object-Designer ***@***.***>
Subject: RE: [hougaard/Simple-Object-Designer] Field Created on Ship-To need to add to pages (#10)

Erik,

I downloaded the new version and was able to pass the field data through transfer and then added it to page 42 sales order.

However when I made the field read only it greyed out the box but the text is really light and can be hard to read, if I take read only off it is more visible but then users could accidently change the value which we don’t want.

Look at the screen shot below where with our support partner they added a field called Customer Min Freight it is in a bolder green font. Is it possible to do this in your app?

***@***.***

Thank you,



***@***.***

***@***.***<http://>
***@***.***

Scott Berg
IT Manager
P  905.660.6700 ext 1242
E  ***@***.******@***.***>
W www.roncosafety.com<http://www.roncosafety.com>
***@***.******@***.******@***.******@***.******@***.***<https://www.youtube.com/user/roncocanada>
***@***.***<https://bit.ly/3i4VoX7>
