### ISSUE TITLE
PATCH API call errors

### ISSUE THREAD

**Issue by ghassanm** [hougaard/Simple-Object-Designer#100]
Hi Support/Erik
I am testing using Postman. When I try PATCH Call, I get the following error message. The standard Microsoft API works fine. Please let me know what I am doing wrong.
Thanks
Ghassan

**The PATCH Call**
https://api.businesscentral.dynamics.com/v2.0/6fd97b54-3483-4f7e-8d06-685564656d2d/Integration/api/hougaard/FHF/v2.0/sales_Headers?Company=DiCentral Testing 02-22-22&$filter=id eq "077a55a8-64fb-ec11-82f8-000d3a748922"

    "error": {
        "code": "BadRequest_MethodNotAllowed",
        "message": "'PATCH' requests for 'sales_Headers' of EdmType 'Collection' are not allowed within Dynamics 365 Business Central OData web services."
    }
}

**Header** 
if-Match: W/"JzE5OzEyMDYzMDQyMjE5NzcxNDcwNjgxOzAwOyc=\"
Content-Type: application/jason

**Body**
{
    "BilltoCity": "Dallas"
}

**Comment by hougaard** [comment]
Change your URL to use Company(<ID>) in the URL instead of Company= in querystring.

**Comment by ghassanm** [comment]
Hi Erik,
I am still getting the same error
https://api.businesscentral.dynamics.com/v2.0/6fd97b54-3483-4f7e-8d06-685564656d2d/Integration/api/hougaard/FHF/v2.0/sales_Headers?Company(DiCentral Testing 02-22-22)&$filter=id eq "077a55a8-64fb-ec11-82f8-000d3a748922"

**Comment by hougaard** [comment]
No, like this:

https://api.businesscentral.dynamics.com/v2.0/6fd97b54-3483-4f7e-8d06-685564656d2d/Integration/api/hougaard/FHF/v2.0/companies(<ID>)/sales_Headers

Where <ID> is the GUID from the company table.

**Comment by ghassanm** [comment]
Hi Erik,
Getting not found error now. I only need to update the bill-to city for a specific sales order. Thanks in advance
https://api.businesscentral.dynamics.com/v2.0/6fd97b54-3483-4f7e-8d06-685564656d2d/Integration/api/hougaard/FHF/v2.0/companies(f77a1b9c-ee93-ec11-b85a-000d3a747dd5)/sales_Headers&$filter=id eq "077a55a8-64fb-ec11-82f8-000d3a748922"

**response**
{
    "error": {
        "code": "BadRequest_NotFound",
        "message": "No HTTP resource was found that matches the request URI 'https://api.businesscentral.dynamics.com/v2.0/6fd97b54-3483-4f7e-8d06-685564656d2d/Integration/api/hougaard/FHF/v2.0/companies(f77a1b9c-ee93-ec11-b85a-000d3a747dd5)/sales_Headers&$filter=id%20eq%20%22077a55a8-64fb-ec11-82f8-000d3a748922%22?tenant=msft1a6720t14543701&aid=FIN'."
    }
}

**Comment by ghassanm** [comment]
Hi Erik,
Do you have feedback on the above. The Sales order exists, and the ID is from GET call.

regards,
Ghassan

**Comment by hougaard** [comment]
It's the URL that's still malformed, I think my suggestion was wrong, check this:

<https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/endpoints-apis-for-dynamics>

**Comment by ghassanm** [comment]
Thank for the quick response. Still getting the same error message.

https://api.businesscentral.dynamics.com/v2.0/6fd97b54-3483-4f7e-8d06-685564656d2d/Integration/api/hougaard/FHF/v2.0/sales_Headers?Company(DiCentral Testing 02-22-22)&$filter=id eq "077a55a8-64fb-ec11-82f8-000d3a748922"

Regards,
Ghassan

**Comment by hougaard** [comment]
Still malformed, try:

https://api.businesscentral.dynamics.com/v2.0/6fd97b54-3483-4f7e-8d06-685564656d2d/Integration/api/hougaard/FHF/v2.0/company(xxxx-yyyy-zzzzzzzz)/sales_Headers/?

where xxxxxx-yyyy-zzzzzzzzzzzzz  is the ID of your company (not name) and the if-match has the ID of the sales header
