### ISSUE TITLE
Transfer Field from Sales Line to Item Ledger

### ISSUE THREAD

**Issue by StillFaithful** [hougaard/Simple-Object-Designer#101]
Would like to be able to transfer Standard Fields from Sales Line to Item Ledger on post...  Any chance of that being added to the functionality?

**Comment by hougaard** [comment]
What fields are you considering?

**Comment by StillFaithful** [comment]
Well, we have a definite need to capture the Original Quantity to a new field in item ledger so that we have visibility of Short Shippings without having to rely on the Archive table for such information.

This would require a Custom Field of course in Item Ledger.  There does not seem to be an App/Extension that I can find to accomplish this.  We are in the design phases of our project and will soon be purchasing the Simple Object Designer to aide with many other minor “customizations”.

Thanks

Chad

**Comment by hougaard** [comment]
Existing field to New field transfer is a scenario we're working on, hopefully part of the next version scheduled for release with BC v21.

**Comment by GrooveRings** [comment]
I am also wanting to create a field transfer from a new custom field on the sales lines to the item ledger and value entries tables. I guess this too will need to wait until the next version?
