### ISSUE TITLE
Lookup Field Error

### ISSUE THREAD

**Issue by teganZT** [hougaard/Simple-Object-Designer#102]
Hi Erik,

I have a BC error that is referencing a lookup field that I recently added.

I added a lookup field on table 5050 (Contacts) which looks up table 156 (Resource). I named this field "Technical Lead"

I now get the attached error when trying to create a Vendor (table 23). ![2022-09-14 13_24_28-Window](https://user-images.githubusercontent.com/104230894/190222740-08f6d2a7-5f0b-40bc-8f1e-0c7a7ad9c92f.png)

The error states:
> Validation Results
> The following fields must have the same type: 
> Field: Technical Lead <-- Credit Limit 
> Table: Contact <-- Vendor 
> Type: Code <-- Decimal

Looking at SOD, it appears that the Technical Lead field I just added has the same field# as another field previously added to table 23. 
![2022-09-14 13_51_25-Window](https://user-images.githubusercontent.com/104230894/190227340-4049adc1-5f42-4c0c-8cea-330a0ab1bf73.png)

To resolve this I tried to change the field# of technical lead from 50108 to 50109, but that caused a publishing error.

What determines the field # of a custom field and do you know how this error might be fixed?

Thank you,

Tom

**Comment by teganZT** [comment]
I was able to fix this by trying different field #s until one published without failure (99998). Hopefully that helps if anyone encounters this.

For future reference I am still unsure what I should be doing with field #s. Should I have a no. series in place that prevents duplicates? Is it important that each # is unique or do we just manually adjust in the rare event of an error?

Thank you,

Tom

**Comment by hougaard** [comment]
Unfortunately,  this is one of those things that there's no way for me to prevent beforehand :(

**Comment by teganZT** [comment]
No worries, I will keep a better eye on my field #s going forward.
