### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by BabelTomahawk** [hougaard/Simple-Object-Designer#104]
I downloaded this app as a trial. I attempted to create a new fields on the Item Card. My first attempt was successful, but then I realized the type of field I selected was not what I wanted. I tried to change the type of that field from User Lookup to Text. When doing that I received an error that I couldn't change it. I then deleted the one I did wrong and recreated it, however it is now stuck I cannot figure out how to get past this. The most recent error I received is below. I know what the error is telling me, I just don't know how to correct it. Any recommendations would be greatly appreciated.

Deployment failed. Errors: App ID : 3aa0bd86-d580-4c47-be26-5e95489e7f8d Message : { Could not upgrade the NAV extension 'Tomahawk Internal Extension by Tomahawk Manufacturing Inc 1.0.0.6' due to the following error: 'TableExtension 51401 SODItem :: The field 'Planning_Approved_By' cannot be located. Removing fields is not allowed.'. } - Job Id : 5ecb2c6a-906a-4255-869e-03f2f1df1535

**Comment by hougaard** [comment]
Only way to do this in the trial version, is to uninstall your app from Extension Management with **Delete Data** turned on, then republish your app from the Object Designer.

**Comment by hougaard** [comment]
With the purchase version of the Simple Object Designer, you can do this:
https://github.com/hougaard/Simple-Object-Designer/issues/80#issuecomment-1153228876

**Comment by BabelTomahawk** [comment]
Thank you, I was able to fix this and continue moving forward with my testing.

**Comment by hougaard** [comment]
Awesome, let us know how the testing goes!
