### ISSUE TITLE
Unable to Publish new Profile (Role) Page

### ISSUE THREAD

**Issue by BabelTomahawk** [hougaard/Simple-Object-Designer#105]
I'm on the trial version and attempted to create a new role center page. I created it with the recommendations from the videos and selected Verify to ensure everything was good. Publishing was successful, however when I go to the Profile(Role) list page my test profile page is not there. I'm sure this is user error, but I can't seem to find what I'm missing. Thoughts?

![image](https://user-images.githubusercontent.com/114018949/191370057-d7029213-f677-47b0-88c4-34c3ddbbd651.png)

![image](https://user-images.githubusercontent.com/114018949/191370091-09e7788c-1601-4760-bd1a-0f644355b39e.png)

![image](https://user-images.githubusercontent.com/114018949/191369999-2c70ecc2-c730-4501-841d-dab37a9ae868.png)

**Comment by BabelTomahawk** [comment]
I wasn't sure if this was an issue related to the trial version, that maybe this wasn't a feature that worked there. I purchased the full version and was able to successfully publish, but I still cannot see the TEST PROFILE role center page I created. I re-watched the video on creating a role center/profile page and still don't have any insight as to what I'm doing wrong. Any insight into this would be greatly appreciated.

**Comment by hougaard** [comment]
Please send the downloaded .app file to support@hougaard.com and I'll take a quick look at it.

**Comment by hougaard** [comment]
Please try creating a profile without a space in the profile name (feature name)....

**Comment by BabelTomahawk** [comment]
That was the problem, I knew there was something I did wrong. Thank you so much for all your help!
