### ISSUE TITLE
Error AL0581

### ISSUE THREAD

**Issue by JulioMoreton** [hougaard/Simple-Object-Designer#106]
Hello, 

I am getting the following error and I don't know where it comes from. 

Package validation failed due to the following error(s): TableExtensions/Service_Item_TableExt.al (6,36) - Error AL0581: The length for the type 'Code' must be positive - Job Id : 57d1ef1d-52da-4ee5-86bb-2f8fefba6ffa

**Comment by hougaard** [comment]
Seems that you have created a field, type Code without a length. Go back to and add a length to your field and try publishing again.

**Comment by JulioMoreton** [comment]
I just don't see where I could add the length. 

![Field Settings ](https://user-images.githubusercontent.com/114618476/192880107-f4a61113-56e2-477e-ae73-64c85b5f74fa.jpg)

**Comment by hougaard** [comment]
It's called "size", but that one looks fine, any other fields?

**Comment by JulioMoreton** [comment]
These are all the fields I have. All of them have a size but the lookup which I don't think it deeds one. 

![All fields](https://user-images.githubusercontent.com/114618476/192882850-00c19410-debc-4ed2-81ec-4eb45322a826.jpg)

**Comment by hougaard** [comment]
Have you created a feature(table) with fields?

**Comment by JulioMoreton** [comment]
No, Those 5 fields are all the customizations I have. 
![All custom](https://user-images.githubusercontent.com/114618476/192883402-4852c15b-8a86-4ac1-9a4c-c3dc590bd754.jpg)

**Comment by hougaard** [comment]
Weird... Are you on a trial or purchased version?

**Comment by JulioMoreton** [comment]
I just sent the app file

**Comment by JulioMoreton** [comment]
Any updates on my problem?

**Comment by hougaard** [comment]
Please report this issue at hougaard.com/support if this is still an issue
