### ISSUE TITLE
Allow users to add new options to a table

### ISSUE THREAD

**Issue by ndfirth** [hougaard/Simple-Object-Designer#107]
Hi, I'm trying to create a lookup table that will allow users to add records, it looks like this is done by setting the table to InsertAllowed property to True. I would like to create the field in the Item-Stockkeeping Unit Card/List and then in the card have user be able to see the field, select on full list, and then add new. Is this possible with Simple Object Designer?

**Comment by hougaard** [comment]
You can create a table (as a feature) and then create a lookup field on the item stockkeeping table as a lookup to your new field.

**Comment by ndfirth** [comment]
Thanks, I did that, but I don't see a way that a user can add a new option. e.g. I can add in Yes, No, as options, but how can a user add an option of 'Maybe'. Right now it will only allow user to select from the options that I created in the table, but want them to be able to add their own. I don't see in attached where user can select 'New'
![Table](https://user-images.githubusercontent.com/103513553/193696858-1a1a236c-cd41-403a-a3f1-69ff80751c34.png)

**Comment by ndfirth** [comment]
> You can create a table (as a feature) and then create a lookup field on the item stockkeeping table as a lookup to your new field.

Thank you kindly, I got that far, but just can't figure out how a new user would be able to add a new possible option via BC. What I'm looking for is the ability to select from full list and then click on 'New'.

**Comment by hougaard** [comment]
You should be able to search (Alt-Q) for your new table...

**Comment by ndfirth** [comment]
> You should be able to search (Alt-Q) for your new table...

Yes, I see the table, I don't think I have the setup correct, I have the Field setup as and table setup as below, but would like for the user to enter the options to select via 'New' in BC and not entered one time into the table.

![Field Settings](https://user-images.githubusercontent.com/103513553/193900455-adf2eefc-a7fd-4bf4-99e2-4dcdacfedb4d.png)
![Table_New_Feature](https://user-images.githubusercontent.com/103513553/193900456-360249aa-b240-45de-998d-d2d3962f49aa.png)

**Comment by hougaard** [comment]
No, try typing Forecast Type in Alt-Q (as a normal user).

**Comment by hougaard** [comment]
OOpps.. hang, you're creating a lookup to itself? That's not going to work. The Type field must just be a regular field.

**Comment by ndfirth** [comment]
> 

or in the feature card, I need to set the type as Text and then it will allow them to add new?
