### ISSUE TITLE
Error on publishing

### ISSUE THREAD

**Issue by Debej** [hougaard/Simple-Object-Designer#108]
When publishing i get Extension validation failed and i am unsure why.
See attached error details.
[Result{CD7C62AC-67AF-4E7B-9C6D-C41DDD9074FB}.txt](https://github.com/hougaard/Simple-Object-Designer/files/9701299/Result.CD7C62AC-67AF-4E7B-9C6D-C41DDD9074FB.txt)

**Comment by Debej** [comment]
Sorry should have mentioned i cleared cache and downloaded most recent symbols and this is in our Sandbox environment

**Comment by hougaard** [comment]
Do you have fields selected on those APIs?

**Comment by Debej** [comment]
Hi Eric

Yes.
There are 2 fields that have been added to the item table and 1 placed on a page - item card
And for the Vendor table - 1 field has been added to the table but not placed on a page.

The above were done quite a while ago have been published successfully in prior versions.

Regards


Debbie Jones
Group Systems Administrator
p: +61 2 4230 8029 | m: +61 402 330 335
e: ***@***.*** | w: www.kollaras.com
a: PO Box 424, Figtree NSW 2525 Australia

​Please note our postal address has changed
 Please consider the environment before printing this email.
_____________________________________________________________________________________________________
DISCLAIMER: This email and any files transmitted with it are confidential and may be the subject to copyright. They are intended solely for the use of the individual or entity to which they are addressed. If you have received this message in error please notify the Kollaras Group immediately by return email or by calling +61 (0)2 4230 8000. Any views or opinions expressed in this email are solely those of the author and do not necessarily represent those of the Kollaras Group except where an authorised sender specifically states them to be views of the Kollaras Group. It is your responsibility to verify this email and any attachments for the presence of viruses. The Kollaras Group accepts no liability for any damage caused by any virus transmitted here.

**Comment by hougaard** [comment]
Please send your app file to support@hougaard.com and we'll take a look.

**Comment by hougaard** [comment]
On the Item API page, exclude these fields: Old Item No and Product Group. And on the Vendor page exclude Old Vendor No. field.

Did those fields get removed by something else?

**Comment by Debej** [comment]
Hi

Not sure what has happened here.
I just checked extension management in the sandbox and there is no current Inhouse SOD extension installed.
In Production we have v.1.0.0.60

***@***.***

We have data in prod for those old fields on the item, Customer and Vendor tables created through SOD.
Would we be best to delete the sandbox and copy prod to new sandbox and then I try to redo the changes I did in SOD.
I am concerned about the data we have in prod in those fields?

Regards


Debbie Jones
Group Systems Administrator
p: +61 2 4230 8029 | m: +61 402 330 335
e: ***@***.*** | w: www.kollaras.com
a: PO Box 424, Figtree NSW 2525 Australia

​Please note our postal address has changed
 Please consider the environment before printing this email.
_____________________________________________________________________________________________________
DISCLAIMER: This email and any files transmitted with it are confidential and may be the subject to copyright. They are intended solely for the use of the individual or entity to which they are addressed. If you have received this message in error please notify the Kollaras Group immediately by return email or by calling +61 (0)2 4230 8000. Any views or opinions expressed in this email are solely those of the author and do not necessarily represent those of the Kollaras Group except where an authorised sender specifically states them to be views of the Kollaras Group. It is your responsibility to verify this email and any attachments for the presence of viruses. The Kollaras Group accepts no liability for any damage caused by any virus transmitted here.

**Comment by hougaard** [comment]
You can use the export/import functions on the SOD setup page to save your app definitions. So you can reload SOD in the new copy and create your app.
