### ISSUE TITLE
We are getting error while publishing the existing field like debit amount and credit amount on table no -81

### ISSUE THREAD

**Issue by Bholechand-Gupta** [hougaard/Simple-Object-Designer#110]
We are getting error while publishing the existing field, like debit amount and credit amount on table no -81.

kindly resolve the issue.

Error Details Below,

**"Package validation failed due to the following error(s): PageExtensions/Bank_Receipt_Voucher_PageExt.al (7,39) - Error AL0118: The name 'Rec' does not exist in the current context
PageExtensions/Bank_Receipt_Voucher_PageExt.al (1,55) - Error AL0247: The target Page "Bank Receipt Voucher" for the extension object is not found - Job Id : 81c252bc-8c68-4768-845a-dbf0cca43600"
![image](https://user-images.githubusercontent.com/116080305/196419819-1520f3c0-f9aa-4c5a-9df1-86ba026ea222.png)**

**Comment by hougaard** [comment]
Please try to refresh your symbols from the Object Designer Setup page (Answer Yes to clear the cache), then try to publish again.
(And before that, make sure you're using the latest version of the Object Designer, update the app from Admin Center).

**Comment by Bholechand-Gupta** [comment]
||ओ३म्||
Dear Sir,

We Refresh the symbol so many time and clear the catch file but, we did not get the complete status. As per your below comments we done the same process.
Screen shot attached for your reference.

***@***.***
We tried to publish the exisiting field through object designer, but the updation is failed due to some reason.

We are the partner company, we purchased the license on urgent basis behalf of customer Admin Login ID. Please let us know how we can transfer the license key to our Partner login ID.

Please provide the solution as earliest


Regards

Bholechand Gupta

ServPRO
Pri: +91 9702266411
MS Team & Email: ***@***.******@***.***>
Web<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bfa98ecf-6b1a-4bad-8435-c88bf0272510&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2f&ValidityToken=VJt7Q8oJ8PX5BuQJGDWFHpmFqOXkM0gOSNKDTKZpn%2fw%3d> | Blog<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=6dfbfffe-82c7-4f7d-bca7-1e986469a10d&RedirectUrl=https%3a%2f%2fcommunity.servproindia.com%2fSignin&ValidityToken=sOiwXWHHNDYUYZ2OeYOb9iiUvxbB%2b8d%2fvNk%2frjy8hLE%3d> (Use Forget Password for FirstTime Use) | Project/Support<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=36fe1baf-7184-48e7-bfbd-57cf40d8040d&RedirectUrl=https%3a%2f%2fnetwork.servproindia.com%2fServPRO%2f&ValidityToken=fZ77qP3isJ1ifWc7kgJatogT48HE39XwAFjtm8fdpDs%3d> (mail us at ***@***.******@***.***> for PW) | Shop/Order<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bc9b151c-c9f2-4e05-abc9-1550797701bf&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2fshop&ValidityToken=Mu0BD7EZnaBJU10xaZmJB67m9gSxcnU99pjYWmsTeww%3d>
स्वच्छ भारत - एक कदम स्वच्छ्ता की ओर

***@***.***

**Comment by Bholechand-Gupta** [comment]
This issue is resolved through personalize flag. so, i am closing this issue.

**Comment by Bholechand-Gupta** [comment]
Issue resolved by using design option.

**Comment by Bholechand-Gupta** [comment]
||ओ३म्||
Dear Sir,

How we can add and remove the field in exisiting Report layout and screen page through Simple object designer. As per indian localization we have to add the GST rates and other details in all reports and pages.

Please guide to us and share the process and steps link and documents, how we can use the simple object designer.

Please accommodate.


Regards

Bholechand Gupta

ServPRO
Pri: +91 9702266411
MS Team & Email: ***@***.******@***.***>
Web<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bfa98ecf-6b1a-4bad-8435-c88bf0272510&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2f&ValidityToken=VJt7Q8oJ8PX5BuQJGDWFHpmFqOXkM0gOSNKDTKZpn%2fw%3d> | Blog<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=6dfbfffe-82c7-4f7d-bca7-1e986469a10d&RedirectUrl=https%3a%2f%2fcommunity.servproindia.com%2fSignin&ValidityToken=sOiwXWHHNDYUYZ2OeYOb9iiUvxbB%2b8d%2fvNk%2frjy8hLE%3d> (Use Forget Password for FirstTime Use) | Project/Support<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=36fe1baf-7184-48e7-bfbd-57cf40d8040d&RedirectUrl=https%3a%2f%2fnetwork.servproindia.com%2fServPRO%2f&ValidityToken=fZ77qP3isJ1ifWc7kgJatogT48HE39XwAFjtm8fdpDs%3d> (mail us at ***@***.******@***.***> for PW) | Shop/Order<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bc9b151c-c9f2-4e05-abc9-1550797701bf&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2fshop&ValidityToken=Mu0BD7EZnaBJU10xaZmJB67m9gSxcnU99pjYWmsTeww%3d>
स्वच्छ भारत - एक कदम स्वच्छ्ता की ओर

***@***.***

From: Bholechand Gupta
Sent: 27 October 2022 17:56
To: 'hougaard/Simple-Object-Designer' ***@***.***>; 'hougaard/Simple-Object-Designer' ***@***.***>
Cc: 'Author' ***@***.***>; Pushpinder Bhatia ***@***.***>
Subject: RE: [hougaard/Simple-Object-Designer] We are getting error while publishing the existing field like debit amount and credit amount on table no -81 (Issue #110)

||ओ३म्||
Dear Sir,

We are waiting for solution for below details,

“We are the partner company, we purchased the license on urgent basis behalf of customer Admin Login ID. Please let us know how we can transfer the license key to our Partner login ID.”

Please share the video, how we can Customised the Layout through Report layout section for all Business Central Documents.

Its Request to you, please provide the solution on above.


Regards

Bholechand Gupta

ServPRO
Pri: +91 9702266411
MS Team & Email: ***@***.******@***.***>
Web<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bfa98ecf-6b1a-4bad-8435-c88bf0272510&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2f&ValidityToken=VJt7Q8oJ8PX5BuQJGDWFHpmFqOXkM0gOSNKDTKZpn%2fw%3d> | Blog<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=6dfbfffe-82c7-4f7d-bca7-1e986469a10d&RedirectUrl=https%3a%2f%2fcommunity.servproindia.com%2fSignin&ValidityToken=sOiwXWHHNDYUYZ2OeYOb9iiUvxbB%2b8d%2fvNk%2frjy8hLE%3d> (Use Forget Password for FirstTime Use) | Project/Support<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=36fe1baf-7184-48e7-bfbd-57cf40d8040d&RedirectUrl=https%3a%2f%2fnetwork.servproindia.com%2fServPRO%2f&ValidityToken=fZ77qP3isJ1ifWc7kgJatogT48HE39XwAFjtm8fdpDs%3d> (mail us at ***@***.******@***.***> for PW) | Shop/Order<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bc9b151c-c9f2-4e05-abc9-1550797701bf&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2fshop&ValidityToken=Mu0BD7EZnaBJU10xaZmJB67m9gSxcnU99pjYWmsTeww%3d>
स्वच्छ भारत - एक कदम स्वच्छ्ता की ओर

***@***.***

From: Bholechand Gupta
Sent: 18 October 2022 21:09
To: 'hougaard/Simple-Object-Designer' ***@***.******@***.***>>; hougaard/Simple-Object-Designer ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>; Pushpinder Bhatia ***@***.******@***.***>>
Subject: RE: [hougaard/Simple-Object-Designer] We are getting error while publishing the existing field like debit amount and credit amount on table no -81 (Issue #110)

||ओ३म्||
Dear Sir,

We Refresh the symbol so many time and clear the catch file but, we did not get the complete status. As per your below comments we done the same process.
Screen shot attached for your reference.

***@***.***
We tried to publish the exisiting field through object designer, but the updation is failed due to some reason.

We are the partner company, we purchased the license on urgent basis behalf of customer Admin Login ID. Please let us know how we can transfer the license key to our Partner login ID.

Please provide the solution as earliest


Regards

Bholechand Gupta

ServPRO
Pri: +91 9702266411
MS Team & Email: ***@***.******@***.***>
Web<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bfa98ecf-6b1a-4bad-8435-c88bf0272510&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2f&ValidityToken=VJt7Q8oJ8PX5BuQJGDWFHpmFqOXkM0gOSNKDTKZpn%2fw%3d> | Blog<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=6dfbfffe-82c7-4f7d-bca7-1e986469a10d&RedirectUrl=https%3a%2f%2fcommunity.servproindia.com%2fSignin&ValidityToken=sOiwXWHHNDYUYZ2OeYOb9iiUvxbB%2b8d%2fvNk%2frjy8hLE%3d> (Use Forget Password for FirstTime Use) | Project/Support<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=36fe1baf-7184-48e7-bfbd-57cf40d8040d&RedirectUrl=https%3a%2f%2fnetwork.servproindia.com%2fServPRO%2f&ValidityToken=fZ77qP3isJ1ifWc7kgJatogT48HE39XwAFjtm8fdpDs%3d> (mail us at ***@***.******@***.***> for PW) | Shop/Order<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bc9b151c-c9f2-4e05-abc9-1550797701bf&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2fshop&ValidityToken=Mu0BD7EZnaBJU10xaZmJB67m9gSxcnU99pjYWmsTeww%3d>
स्वच्छ भारत - एक कदम स्वच्छ्ता की ओर

***@***.***

**Comment by Bholechand-Gupta** [comment]
||ओ३म्||
Dear Sir,
We are reaching out again on the topic shared in the trail to seek your help and conclude the topic.
Please accommodate.

Regards

Bholechand Gupta

ServPRO
Pri: +91 9702266411
MS Team & Email: ***@***.******@***.***>
Web<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bfa98ecf-6b1a-4bad-8435-c88bf0272510&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2f&ValidityToken=VJt7Q8oJ8PX5BuQJGDWFHpmFqOXkM0gOSNKDTKZpn%2fw%3d> | Blog<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=6dfbfffe-82c7-4f7d-bca7-1e986469a10d&RedirectUrl=https%3a%2f%2fcommunity.servproindia.com%2fSignin&ValidityToken=sOiwXWHHNDYUYZ2OeYOb9iiUvxbB%2b8d%2fvNk%2frjy8hLE%3d> (Use Forget Password for FirstTime Use) | Project/Support<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=36fe1baf-7184-48e7-bfbd-57cf40d8040d&RedirectUrl=https%3a%2f%2fnetwork.servproindia.com%2fServPRO%2f&ValidityToken=fZ77qP3isJ1ifWc7kgJatogT48HE39XwAFjtm8fdpDs%3d> (mail us at ***@***.******@***.***> for PW) | Shop/Order<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bc9b151c-c9f2-4e05-abc9-1550797701bf&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2fshop&ValidityToken=Mu0BD7EZnaBJU10xaZmJB67m9gSxcnU99pjYWmsTeww%3d>
स्वच्छ भारत - एक कदम स्वच्छ्ता की ओर

***@***.***

From: Bholechand Gupta
Sent: 16 November 2022 11:32
To: 'hougaard/Simple-Object-Designer' ***@***.***>; 'hougaard/Simple-Object-Designer' ***@***.***>
Cc: 'Author' ***@***.***>; Pushpinder Bhatia ***@***.***>
Subject: RE: [hougaard/Simple-Object-Designer] We are getting error while publishing the existing field like debit amount and credit amount on table no -81 (Issue #110)

||ओ३म्||
Dear Sir,

How we can add and remove the field in exisiting Report layout and screen page through Simple object designer. As per indian localization we have to add the GST rates and other details in all reports and pages.

Please guide to us and share the process and steps link and documents, how we can use the simple object designer.

Please accommodate.


Regards

Bholechand Gupta

ServPRO
Pri: +91 9702266411
MS Team & Email: ***@***.******@***.***>
Web<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bfa98ecf-6b1a-4bad-8435-c88bf0272510&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2f&ValidityToken=VJt7Q8oJ8PX5BuQJGDWFHpmFqOXkM0gOSNKDTKZpn%2fw%3d> | Blog<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=6dfbfffe-82c7-4f7d-bca7-1e986469a10d&RedirectUrl=https%3a%2f%2fcommunity.servproindia.com%2fSignin&ValidityToken=sOiwXWHHNDYUYZ2OeYOb9iiUvxbB%2b8d%2fvNk%2frjy8hLE%3d> (Use Forget Password for FirstTime Use) | Project/Support<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=36fe1baf-7184-48e7-bfbd-57cf40d8040d&RedirectUrl=https%3a%2f%2fnetwork.servproindia.com%2fServPRO%2f&ValidityToken=fZ77qP3isJ1ifWc7kgJatogT48HE39XwAFjtm8fdpDs%3d> (mail us at ***@***.******@***.***> for PW) | Shop/Order<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bc9b151c-c9f2-4e05-abc9-1550797701bf&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2fshop&ValidityToken=Mu0BD7EZnaBJU10xaZmJB67m9gSxcnU99pjYWmsTeww%3d>
स्वच्छ भारत - एक कदम स्वच्छ्ता की ओर

***@***.***

From: Bholechand Gupta
Sent: 27 October 2022 17:56
To: 'hougaard/Simple-Object-Designer' ***@***.******@***.***>>; 'hougaard/Simple-Object-Designer' ***@***.******@***.***>>
Cc: 'Author' ***@***.******@***.***>>; Pushpinder Bhatia ***@***.******@***.***>>
Subject: RE: [hougaard/Simple-Object-Designer] We are getting error while publishing the existing field like debit amount and credit amount on table no -81 (Issue #110)

||ओ३म्||
Dear Sir,

We are waiting for solution for below details,

“We are the partner company, we purchased the license on urgent basis behalf of customer Admin Login ID. Please let us know how we can transfer the license key to our Partner login ID.”

Please share the video, how we can Customised the Layout through Report layout section for all Business Central Documents.

Its Request to you, please provide the solution on above.


Regards

Bholechand Gupta

ServPRO
Pri: +91 9702266411
MS Team & Email: ***@***.******@***.***>
Web<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bfa98ecf-6b1a-4bad-8435-c88bf0272510&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2f&ValidityToken=VJt7Q8oJ8PX5BuQJGDWFHpmFqOXkM0gOSNKDTKZpn%2fw%3d> | Blog<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=6dfbfffe-82c7-4f7d-bca7-1e986469a10d&RedirectUrl=https%3a%2f%2fcommunity.servproindia.com%2fSignin&ValidityToken=sOiwXWHHNDYUYZ2OeYOb9iiUvxbB%2b8d%2fvNk%2frjy8hLE%3d> (Use Forget Password for FirstTime Use) | Project/Support<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=36fe1baf-7184-48e7-bfbd-57cf40d8040d&RedirectUrl=https%3a%2f%2fnetwork.servproindia.com%2fServPRO%2f&ValidityToken=fZ77qP3isJ1ifWc7kgJatogT48HE39XwAFjtm8fdpDs%3d> (mail us at ***@***.******@***.***> for PW) | Shop/Order<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bc9b151c-c9f2-4e05-abc9-1550797701bf&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2fshop&ValidityToken=Mu0BD7EZnaBJU10xaZmJB67m9gSxcnU99pjYWmsTeww%3d>
स्वच्छ भारत - एक कदम स्वच्छ्ता की ओर

***@***.***

From: Bholechand Gupta
Sent: 18 October 2022 21:09
To: 'hougaard/Simple-Object-Designer' ***@***.******@***.***>>; hougaard/Simple-Object-Designer ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>; Pushpinder Bhatia ***@***.******@***.***>>
Subject: RE: [hougaard/Simple-Object-Designer] We are getting error while publishing the existing field like debit amount and credit amount on table no -81 (Issue #110)

||ओ३म्||
Dear Sir,

We Refresh the symbol so many time and clear the catch file but, we did not get the complete status. As per your below comments we done the same process.
Screen shot attached for your reference.

***@***.***
We tried to publish the exisiting field through object designer, but the updation is failed due to some reason.

We are the partner company, we purchased the license on urgent basis behalf of customer Admin Login ID. Please let us know how we can transfer the license key to our Partner login ID.

Please provide the solution as earliest


Regards

Bholechand Gupta

ServPRO
Pri: +91 9702266411
MS Team & Email: ***@***.******@***.***>
Web<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bfa98ecf-6b1a-4bad-8435-c88bf0272510&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2f&ValidityToken=VJt7Q8oJ8PX5BuQJGDWFHpmFqOXkM0gOSNKDTKZpn%2fw%3d> | Blog<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=6dfbfffe-82c7-4f7d-bca7-1e986469a10d&RedirectUrl=https%3a%2f%2fcommunity.servproindia.com%2fSignin&ValidityToken=sOiwXWHHNDYUYZ2OeYOb9iiUvxbB%2b8d%2fvNk%2frjy8hLE%3d> (Use Forget Password for FirstTime Use) | Project/Support<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=36fe1baf-7184-48e7-bfbd-57cf40d8040d&RedirectUrl=https%3a%2f%2fnetwork.servproindia.com%2fServPRO%2f&ValidityToken=fZ77qP3isJ1ifWc7kgJatogT48HE39XwAFjtm8fdpDs%3d> (mail us at ***@***.******@***.***> for PW) | Shop/Order<https://crmri.crm8.dynamics.com/api/EmailAnalytics/OpenLink?TrackingId=6741f973-95a3-eb11-b1ac-000d3ac9d840&ConversationTrackingId=f378e4a4-0d93-480a-8364-48ca6917c5ea&ClientType=webclient&OrganizationId=55471f5c-14b2-40cf-a83d-67f17af7b338&Salt=bc9b151c-c9f2-4e05-abc9-1550797701bf&RedirectUrl=http%3a%2f%2fwww.servproindia.com%2fshop&ValidityToken=Mu0BD7EZnaBJU10xaZmJB67m9gSxcnU99pjYWmsTeww%3d>
स्वच्छ भारत - एक कदम स्वच्छ्ता की ओर

***@***.***

**Comment by hougaard** [comment]
Please update the Object Designer to the latest version, then set Publish Update Mode to "Force" in the Setup and try publishing again...
