### ISSUE TITLE
API Error when trying to add fields

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#111]
In our production system I am trying to add two new text fields to the Item Card, when I go to publish I get the following error

![image](https://user-images.githubusercontent.com/87865315/196811623-c5cea579-7e03-4147-b237-fc459a1fed48.png)

I am using latest version of SOD 5.0.0.161 and I did a refresh of all symbols.

There is nothing special with the fields, just regular text fields, 200 character, multiline.

I did the exact steps in our Sandbox system and I had no error there.

**Comment by hougaard** [comment]
Sounds like you have created a customer API, but without selecting any fields? (Check in "Expose as API")

**Comment by ScottB-Ronco** [comment]
First thank you for quick response.

You are right there was an API created with nothing added. I don't recall doing this, but I must have been testing something and didn't realize I did this in production.

Since no fields were added to the API I just deleted it and then published and all worked fine.

I will be closing this ticket now
