### ISSUE TITLE
Error when publishing : AL0185 missing features

### ISSUE THREAD

**Issue by RGI100** [hougaard/Simple-Object-Designer#112]
I am getting the following error when publishing:

Package validation failed due to the following error(s): Permissions/Permissions.al (8,29) - Error AL0185: Table '"Ship Pick CodeSOD"' is missing
Features/ItemSize/ItemSize.Table.al (1,13) - Error PTE0004: Table 50500 'ItemSizeSOD' is missing a matching permission set.

This only seems to be happening today, I have published this previously.

**Comment by hougaard** [comment]
Weird, can you send the .app file to support@hougaard.com, and I'll take a look.

**Comment by RGI100** [comment]
Thank you Eric,

Please see attached.

Regards

**Comment by hougaard** [comment]
Sorry, this is stupid, but you cannot reply to this email (notification from Github), attachments are stripped from the email. You gotta send to support@hougaard.com
