### ISSUE TITLE
NEW LABEL ON REPORTS

### ISSUE THREAD

**Issue by Agordon110799** [hougaard/Simple-Object-Designer#113]
I added a new label in an existing table and I show it on report:

![Captura](https://user-images.githubusercontent.com/116739077/198056273-a833af52-a098-458a-960a-371ee7ec36f5.JPG)

but I don't see it in treport

![Captura1](https://user-images.githubusercontent.com/116739077/198056795-1e48c7fb-6e96-4e35-a7b8-04695fe3e3f6.JPG)

**Comment by hougaard** [comment]
Fields are "only" added to the dataset of a report, you have to create a custom report layout and place the field on the page then.

Go to Custom Report Layout. Use the Update Layout before you export the layout. Then edit and import again.

**Comment by Agordon110799** [comment]
Ok, thanks. It’s ok


Antonio Gordón Ribas
Servicios Corporativos
Responsable administración y sistemas
Ronda de Can Rabadà 2, 5º 5ª, Edificio Logic
08860 Castelldefels (Barcelona)
Tel. +34933284328 | Mob. +34610262713 | ***@***.***
[Twitter]<https://twitter.com/Geprom_industry>
[LinkedIn]<https://www.linkedin.com/company/geprom-connecting-industries/>
[YouTube]<https://www.youtube.com/channel/UC5SW_2Q0paTudFrJqlIF7aw>
geprom.com <https://geprom.com/>

***@***.***



De: Erik Hougaard ***@***.***>
Enviado el: miércoles, 26 de octubre de 2022 16:48
Para: hougaard/Simple-Object-Designer ***@***.***>
CC: Antonio Gordon | Geprom ***@***.***>; Author ***@***.***>
Asunto: Re: [hougaard/Simple-Object-Designer] NEW LABEL ON REPORTS (Issue #113)


Fields are "only" added to the dataset of a report, you have to create a custom report layout and place the field on the page then.

Go to Custom Report Layout. Use the Update Layout before you export the layout. Then edit and import again.
