### ISSUE TITLE
Publish Failed

### ISSUE THREAD

**Issue by smcn0604** [hougaard/Simple-Object-Designer#115]
Hi
getting the error pasted below:
Deployment failed. Errors: App ID : e750507f-16fa-4528-92bb-440ed692a0fb Message : { Could not upgrade the NAV extension 'My Customizations by MODEL3 1.0.0.12' due to the following error: 'TableExtension 50500 SODResource :: The table 'Resource' cannot be located. Removing tables is not allowed unless they are temporary or are being moved by migration to another app.'. } - Job Id : 769229a3-ed09-47d6-90bf-4de7250c8c08
The publish has 2 new custom fields that relate to table 5766 only
I had previous custom fields that related to the Resource table but I've deleted those and removed customisations from the Resource table and page
[Result{7639EE90-41CA-4FC9-BCD7-0DB89D6940F3}.txt](https://github.com/hougaard/Simple-Object-Designer/files/9940687/Result.7639EE90-41CA-4FC9-BCD7-0DB89D6940F3.txt)

**Comment by hougaard** [comment]
You'll have to upload the downloaded .app file to extension management manually and the Schema Update Mode = Force.

(or if this is just testing, uninstall the old version with "delete data" turned on)

**Comment by smcn0604** [comment]
Hi

Thanks for your response

I uninstalled the old version WITHOUT delete data switched on, is there a way to redo?

Regards

Steve McNulty

H:  01298 85549

M: 07875739938  

This e-mail is confidential and if you are not the intended recipient then please delete the mail and notify me, you should not use or disclose the contents of this email.

**Comment by hougaard** [comment]
Then you need to re-install (by uploading from extension management) the app file that was downloaded the last time before you deleted the field.

**Comment by smcn0604** [comment]
Hi
the upload, with FORCE, fails with An extension with app Id 'e750507f-16fa-4528-92bb-440ed692a0fb' and version at least '1.0.0.4' is already installed on this environment.
The problem was also recreated in a 2nd environment by deleting a field, should this happen?
I don't now have an environment where i can publish from Simple Object
Please advise details on how to resolve, thanks

**Comment by smcn0604** [comment]
Hi
is there any support available
the simple object package seems to have stopped working, getting persistent unknown status & file not found errors

**Comment by hougaard** [comment]
Please try to update the Object Designer to the newest version. With that, you can set update mode to force in the Object Designer Setup page. Then try publishing again...

**Comment by hougaard** [comment]
Hang on, did you change the app name? What app has version 1.0.0.4 (and the id e75050.......)?
