### ISSUE TITLE
Publish doesn't work

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#118]
Hello,

Starting today, the publish of my extension is never finished. It doesn't show an error, just lasts forever. Also this morning, I also got the message of "Business Central will update a few things, close the session so you don't lose your work".

The window of the SOD where shows the installation status, just hangs out and refreshes every few minutes, and finally it doesn't respond.

Any ideas on how to troubleshoot this?

It stays like that:

![image](https://user-images.githubusercontent.com/99739571/202469301-862a04ed-e1b0-4e92-9bc5-933e9d514a46.png)

Thanks in advance.

**Comment by hougaard** [comment]
"Status=Unknown" is a Microsoft issue, if this persists, you have to open a Microsoft support ticket.

**Comment by hougaard** [comment]
How does it look if you go to Extension Management and open "Installation Status" ?

**Comment by juasanri** [comment]
In Extension Management only the last succesful installation is shown. If I go to the SOD and go "Extension Installation Status", I get that one trial is failed, all the rest unknown:

![image](https://user-images.githubusercontent.com/99739571/202657936-229249a0-127d-4c71-95f6-6f72e0708ccc.png)

**Comment by juasanri** [comment]
You can close this ticket. Today it just worked...

Thanks
