### ISSUE TITLE
Tried to delete a field and replace with a New one

### ISSUE THREAD

**Issue by tstrop** [hougaard/Simple-Object-Designer#119]
Everything was going fine until! I started by creating a text field "Picking Instruction" 50 Characters, Sales Quote, Order, Invoice and Pick Instruction and Pick List by Order Reports. Quickly relalized 50 chars were not enough. Tried to edit to no avail so I tried deleting and creating a new field. 
![First Error 2022-11-18_21-22-39](https://user-images.githubusercontent.com/15703800/202853741-d904f9bd-c6a7-4829-96e2-9ca179416475.png)
After reading some of your post I decided to try Uninstalling Simple Object with Forced option and reinstalling. 
![Second error Error 2022-11-18_21-22-39](https://user-images.githubusercontent.com/15703800/202854462-887e36a5-cd30-41c0-ba60-7a30464d6459.png)
So, my current state is, I have the original field on the forms and can't remove it, it wasn't available for selection on the Pick Instruction and Pick List RDLC reports when I originally check and I can't replace it with a new 300 character test field. Newbie mistakes. I'm going live December 1st. Thank you in advance

**Comment by hougaard** [comment]
If you update to the latest version of the Simple Object Designer, you now have the option of publishing with Force (include destructive changes like delete). Select "Force" on the Object Designer Setup Page.
