### ISSUE TITLE
Field Transfer Item Sub Entry Page 5716

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#12]
I created a field on the Item Substitution Entry page 5716 which is on the item card. I want to transfer this field to the Item Substitution Entries List page 5718, but when I go to add a transfer it is not available to add.

**Comment by hougaard** [comment]
That's the same table, no field transfer is required, you new field should be available to add on both pages.

**Comment by ScottB-Ronco** [comment]
OK then maybe I am doing something wrong then, because here is what I did to add the field. I made the field Text and 4 characters

![image](https://user-images.githubusercontent.com/87865315/131929918-69b7afca-50e6-47dd-af15-d66d55f8c16c.png)
![image](https://user-images.githubusercontent.com/87865315/131929953-e9e81125-dd9e-4be7-acbd-028c0a5ea71d.png)

Then when I went and put values in the field under item subs on item card, but the values doesn't show in subs list when pulled up on sales line substitutions, it is just a blank selectable line.

![image](https://user-images.githubusercontent.com/87865315/131930181-d3f89dce-0fe3-44c4-82ae-e009b257f54e.png)
![image](https://user-images.githubusercontent.com/87865315/131930209-c1f05eca-a5ac-4117-963f-4cb987e846e1.png)

**Comment by hougaard** [comment]
The _ (underscore) looks kinda strange in 5718, what other settings did you give the field?

**Comment by ScottB-Ronco** [comment]
I did not  set any other settings. Just added field to table 5715 Item Substitutions made it a text field and and gave it a 4 character limit. The placed it on pages 5716 & 5718.

**Comment by ScottB-Ronco** [comment]
Erik,

Do you have any ideas why this isn't working and not passing the value correctly?
