### ISSUE TITLE
Error when publishing

### ISSUE THREAD

**Issue by DogmatixAU** [hougaard/Simple-Object-Designer#121]
Am attempting to publish some changes but I get an error message

![Screenshot 2022-11-23 141123](https://user-images.githubusercontent.com/92653294/203482542-5e2127a6-7b70-451e-be60-0309c0e5d058.png)

Could this be because the version number is in a different format to you?

![Screenshot 2022-11-23 141255](https://user-images.githubusercontent.com/92653294/203482694-85207c86-64e9-4872-a30c-3bb00c3e788b.png)

**Comment by hougaard** [comment]
A version number must have four components A.B.C.D, you only have three there....
