### ISSUE TITLE
Add option to field created and publish

### ISSUE THREAD

**Issue by JulioMoreton** [hougaard/Simple-Object-Designer#129]
Hello, 

I was wondering if it's possible to add an additional option to a field that I have created with simple object designer. This field is an option field and I will like to add one more but it is already puchished.

**Comment by hougaard** [comment]
Yes, you can do that, just add the new option and republish.

**Comment by JulioMoreton** [comment]
I get the following error. 

![Screenshot 2022-12-15 164857](https://user-images.githubusercontent.com/114618476/207974507-e4982237-29e5-4f95-b337-32764bc8eb1e.jpg)

**Comment by hougaard** [comment]
Right now, you'll have to delete the field and reenter it (with the same name and field number). Then you must turn on "Force" deployment in the setup to allow publishing of the change.

**Comment by hougaard** [comment]
.. or you can wait for version 5.0.0.202 - that will come out tonight, it will allow it :)
