### ISSUE TITLE
Calculation fields in Simple Object Designer

### ISSUE THREAD

**Issue by InaFie** [hougaard/Simple-Object-Designer#13]
Good Day 

This is a query rather than an issue and it is whether it is possible or if you are planning to make available the ability to perform calculations in the App to place on reports and pages in BC and Wiise?

Thank you
Ina

**Comment by hougaard** [comment]
By "calculations", do you mean FlowFields?

**Comment by InaFie** [comment]
I have a requirement to add a field to a Word Template report which is a calculation of 2 other fields, LineTotal/LineQty to get the NetUnitPrice.

Is that a FlowField?

**Comment by hougaard** [comment]
No, that's not a flowfield, that is a proper calculation. 

I have some ideas on how to support that in the object designer, in a drag-and-drog kinda way. But not ready fro prime time yet.

**Comment by InaFie** [comment]
Great and thank you.  I look forward to seeing it in the future.
