### ISSUE TITLE
New fields stop posting of delivery to work

### ISSUE THREAD

**Issue by MKEWAS** [hougaard/Simple-Object-Designer#130]
Hi 

I added 2 new fields to table 36 - sales header. One Text and one decimal field. I also transfered the fields to sales archieve also.
When i try to post a delivery BC complaimts that i am trying to move a decimal field to a text field.

I cannot see how i can get back to my old working version.

I had to deactivate my customizations to get it to work againg. And I need to work as quick as possible,

Best regards,
Morten
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/120103105/206442133-355ac9f2-0488-4fba-ae70-8a3d6448d7e4.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/120103105/206442140-b9462534-bab3-4473-be64-0a053388d51e.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/120103105/206442141-371a0909-f7f1-4a53-b346-d11fd5f214da.png)

**Comment by hougaard** [comment]
Hi Morten,

In a few places BC requires fields to have the same number across tables, I can see that that's not the case in your screenshots. If you change the field number to match across tables it will all work :)

**Comment by MKEWAS** [comment]
Hej
Tak
Jeg slettede felterne og tilføjede dem igen.
Så nu kører jeg igen.

Det er virkelig en fin app du har lavet

Mvh
Morten

Sendt fra min iPhone

Den 8. dec. 2022 kl. 17.06 skrev Erik Hougaard ***@***.***>:

﻿

Hi Morten,

In a few places BC requires fields to have the same number across tables, I can see that that's not the case in your screenshots. If you change the field number to match across tables it will all work :)

**Comment by hougaard** [comment]
Tak!
