### ISSUE TITLE
Can not change Shipment Method Code Caption Value Table 26 Field 27

### ISSUE THREAD

**Issue by rjonespro** [hougaard/Simple-Object-Designer#134]
It looks like the Current Caption is not showing what is populated on Pages.

![image](https://user-images.githubusercontent.com/26175728/207955075-c1bf92ef-b7fa-47e7-a16a-f33f15f79bb3.png)

![image](https://user-images.githubusercontent.com/26175728/207955283-f43a5ed4-38cc-41b2-95c4-822ca5895bb2.png)

**Comment by rjonespro** [comment]
Any feedback on this?

**Comment by hougaard** [comment]
Yes, looked into it... the "Code" caption is being set on the page and overrides what comes from the table. So even if you override the caption on the table, that still gets overridden by the page.
