### ISSUE TITLE
Field Transfer - Decription 2: From 36 Item to 83 Item Journal Ledger

### ISSUE THREAD

**Issue by MKEWAS** [hougaard/Simple-Object-Designer#136]
Hi,
Can you help me with a field transfer of customized field "Description 2" to table 83 Item Journal Ledger?
Thank you in advance.
Best regards,
Morten

**Comment by hougaard** [comment]
From where?

**Comment by MKEWAS** [comment]
Table 36. Item. It is in subject.

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Erik Hougaard ***@***.***>
Sendt: Tuesday, December 20, 2022 6:30:39 AM
Til: hougaard/Simple-Object-Designer ***@***.***>
Cc: Morten Eriksen ***@***.***>; Author ***@***.***>
Emne: Re: [hougaard/Simple-Object-Designer] Field Transfer - Decription 2: From 36 Item to 83 Item Journal Ledger (Issue #136)


From where?

**Comment by hougaard** [comment]
Wow, thanks :)

**Comment by hougaard** [comment]
.. You can't go from 36 to 83, Item Journal Lines do not get created from the Header, only from the Lines. But you can add the file to 37 also, and then field transfer your way through.
