### ISSUE TITLE
The data does not represent a valid JSON token.

### ISSUE THREAD

**Issue by ExcalibuR373** [hougaard/Simple-Object-Designer#137]
Installed Simple Object Designer extension (this APP is AMAZING!!!).  Worked up some customizations, verified they are working, and published to the production environment.

After having trouble adding some existing fields to reports, I decided to clear everything out and start over after completely uninstalling SOD, including clearing the cache (in the Sandbox environment).

This was unsuccessful.  I want to continue on with the original, working APP mods extension...but when attempting to Import App under the SOD Setup, I'm getting the following error:

The data does not represent a valid JSON token.

Internal session ID: 
acc0a97d-4609-4d17-90fa-de589035821b

Application Insights session ID: 
9cb0c56d-c6de-4dcd-9cfa-2a237617ff4a

Client activity id: 
067f5f3b-a818-47cc-b807-edd638849421

Time stamp on error: 
2022-12-19T21:00:39.3706333Z

AL call stack: 
"Simple Field Setup Hgd"(Page 70310250)."Import - OnAction"(Trigger) line 13 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."Setup - OnAction"(Trigger) line 4 - Simple Object Designer by Hougaard
"Guided Experience Impl."(CodeUnit 1991).RunObject line 4 - System Application by Microsoft
"Guided Experience Impl."(CodeUnit 1991).Run line 34 - System Application by Microsoft
"Guided Experience Impl."(CodeUnit 1991).RunExtensionSetup line 22 - System Application by Microsoft
"Guided Experience"(CodeUnit 1990).RunExtensionSetup line 2 - System Application by Microsoft
"Extension Installation Impl"(CodeUnit 2500).RunExtensionSetup line 6 - System Application by Microsoft
"Extension Management"(Page 2500)."SetupApp - OnAction"(Trigger) line 9 - System Application by Microsoft
"Object Designer Menu Hgd"(Page 70310263)."Help5Ctl - OnDrillDown"(Trigger) line 2 - Simple Object Designer by Hougaard
"Guided Experience Impl."(CodeUnit 1991).RunObject line 4 - System Application by Microsoft
"Guided Experience Impl."(CodeUnit 1991).Run line 34 - System Application by Microsoft
"Guided Experience Impl."(CodeUnit 1991).RunExtensionSetup line 22 - System Application by Microsoft
"Guided Experience"(CodeUnit 1990).RunExtensionSetup line 2 - System Application by Microsoft
"Extension Installation Impl"(CodeUnit 2500).RunExtensionSetup line 6 - System Application by Microsoft
"Extension Management"(Page 2500)."SetupApp - OnAction"(Trigger) line 9 - System Application by Microsoft
"Object Designer Menu Hgd"(Page 70310263)."Help5Ctl - OnDrillDown"(Trigger) line 2 - Simple Object Designer by Hougaard

I have both the source code and APP file.  Help!

Thanks,
  -Gabriel

**Comment by hougaard** [comment]
You're importing the wrong file, use the one you got when you used the export app.

**Comment by ExcalibuR373** [comment]
*feeling dumb* I didn't understand that Export App is the backup of the Simple Object Designer APP setup/configuration/modifications.

I don't have the .json file from this iteration, it's been lost into the digital void.  I thought downloading source, or the auto downloaded APP was what I needed. Back to starting over!  Practice makes perfect.

Thanks for the quick reply, I posted to the forums in case anyone else runs into this problem (due to user error).
