### ISSUE TITLE
Problem adding a new field to the Customer Price Group table

### ISSUE THREAD

**Issue by archdixon** [hougaard/Simple-Object-Designer#139]
I ran into a problem when trying to add a custom field to the Customer Price Group table and page. When I anchored the field to an existing field and look at the page, I do see my new field. However, there's also a second Code column and it doesn't behave well. Specifically, it doesn't ask for verification if you try changing the field value (like normally happens when you try changing the primary key values). 

I've since deleted the new field I was trying to add and forced a publication, but the rogue Code column is still on the page. 

![image](https://user-images.githubusercontent.com/44958730/210012451-6af7df61-9f37-4a5f-a893-aba2ea9a5e38.png)

...

Okay, so confession here... when presented with the following prompt, I answered "no," because I don't have a domain account and can't get this to successfully run. Is this why I'm having problems? 

- Your source code symbols are not up to date, do you want to update them now? (If you publish without updated symbols you run the risk of a deployment failure).

Thanks,

**Comment by hougaard** [comment]
The symbols thing would not affect this.

If you uninstall your app from Extension Management, is the field gone then?

**Comment by archdixon** [comment]
When I uninstalled the app, the rogue column does go away. 

![image](https://user-images.githubusercontent.com/44958730/210125990-9f85a03d-e3c6-4039-a096-a529f9548a71.png)

**Comment by hougaard** [comment]
Use the "Inspect" area to clear customizations from that page, seems like you got a rogue page placement sitting somewhere..

**Comment by archdixon** [comment]
Where and how do I do that?

**Comment by archdixon** [comment]
That worked. Using the **Inspect** and **Customize** tool on the page, I was able to remove just the rogue field and leave my new field visible.
