### ISSUE TITLE
Field Type Errors when Posting Sales Order

### ISSUE THREAD

**Issue by GrooveRings** [hougaard/Simple-Object-Designer#14]
I have two fields I've created and published to the sales order and invoice documents. One is a code field and the other is a decimal field. They are unrelated to one another. I'm confused by this error I got after testing a posting with the new fields. 

<img width="547" alt="Screen Shot 2021-09-23 at 6 31 39 PM" src="https://user-images.githubusercontent.com/82909149/134597023-f94b09a8-4500-4f1b-a469-9a117e1253e7.png">

![Screen Shot 2021-09-23 at 6 33 22 PM](https://user-images.githubusercontent.com/82909149/134597121-e02ed8d7-7302-42d7-9284-97b5d84695a5.png)

**Comment by hougaard** [comment]
Use personalizations and make the field number visible. I think you got the number of the fields swapped.

**Comment by GrooveRings** [comment]
You are absolutely right. Thank you for the quick response!
