### ISSUE TITLE
API Query type with sum

### ISSUE THREAD

**Issue by CakeDavidB** [hougaard/Simple-Object-Designer#140]
Hi,

Would it be possible to add a feature so that an API Page can instead be a query, with the addition of a sum method at the end?

In my naive head its just changing the type and adding something like "{method = sum;}" to the end. This would then automatically aggregate to the chosen fields. Could be useful when someone is pulling data for use in some external report. 

Dont know how useful it would be without the ability to also pull in linked data, for example headers and lines. But its an idea.

Thanks for a great app!

**Comment by hougaard** [comment]
Not really possible, that's not how BC APIS work, can't you sum in the consumer of the apis?
