### ISSUE TITLE
System fields removed from API

### ISSUE THREAD

**Issue by rmfont** [hougaard/Simple-Object-Designer#143]
Hi Erik, the system fields SystemCreatedAt, SystemCreatedBy, SystemModifiedAt, and SystemModifiedBy have disappeared from the available API fields and were removed from exisiting published APIs.  We use SystemModifiedAt as the DateTime field in PowerBI incremental refresh configuration for tables such as G/L Entry and G/L Budget Entry, and so all our PowerBI dataflows are failing due to the missing field.  Do you know if this change is coming from SOD or from a recent Microsoft update?

**Comment by hougaard** [comment]
Ahh... I think I know the reason. Stay tuned for an update later tonight....

**Comment by hougaard** [comment]
Issued located and fixed, will submit an update to appsource soon.

Sorry for the inconvenience.
