### ISSUE TITLE
Refresh Symbols Failing / Error

### ISSUE THREAD

**Issue by jmcDEV87** [hougaard/Simple-Object-Designer#144]
When opening we're prompted to refresh symbols, i authenticate using device login but it says error, no code:

Could not contact dynamics.com, error ()

Pass on the following information to technical support:

Any ideas?

**Comment by hougaard** [comment]
Have you blocked HttpRequests on the Object Designer app (in Extension Management, click configure)?

**Comment by jmcDEV87** [comment]
Hi,  i dont have  configure option for the object designer, but when i click view from the extension management screen , the "Allow HttpClient Request" was toggled off, i've moved that to on but still get the same error. 
![image](https://user-images.githubusercontent.com/122998738/213427287-6fe9baa7-e932-46be-b865-4ec0e0d24140.png)
![image](https://user-images.githubusercontent.com/122998738/213427367-7ace4be8-79ec-4a85-9f22-23b8b0f8ffe8.png)

**Comment by jmcDEV87** [comment]
Using Version: GB Business Central 21.2

**Comment by hougaard** [comment]
Weird, can you screenshot the error and press the "Copy information to clipboard" to get the callstack.

thanks!

**Comment by jmcDEV87** [comment]
![image](https://user-images.githubusercontent.com/122998738/215745325-fd61c2b6-a643-4213-91cb-3a4675f76dcc.png)

Could not contact dynamics.com, error ()

Internal session ID: 
e6c13b71-54cb-44df-9e9e-1a0fdd362bd4

Application Insights session ID: 
b7ea2c97-13ec-4440-ad7a-6c122e13d92a

Client activity id: 
3a4899bc-2ee4-4c32-b320-c4e67f218e06

Time stamp on error: 
2023-01-31T11:13:42.6566669Z

AL call stack: 
"Symbol Management Hgd"(CodeUnit 70310251).DownloadFile line 66 - Simple Object Designer by Hougaard
"Symbol Management Hgd"(CodeUnit 70310251).DownloadSymbols line 63 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263).OnOpenPage(Trigger) line 28 - Simple Object Designer by Hougaard

**Comment by hougaard** [comment]
And are you using the Alternative API URL field? (In SOD Setup)
<img width="357" alt="image" src="https://user-images.githubusercontent.com/3357237/215819117-8f798941-aad4-48fa-b3bd-530b62a32212.png">

**Comment by jmcDEV87** [comment]
i don't have that option shown on the SOD Setup.
![image](https://user-images.githubusercontent.com/122998738/215836081-0ee68944-36d6-4651-9472-8f6e35934cf3.png)

Also unsure if related but i have published additional APIs - these show up on business central but the API queue card on SOD shows zero now.  I'm able to connect and the use the APIs still.

![image](https://user-images.githubusercontent.com/122998738/215836499-c9c452bc-4bca-4a25-88cc-b791d53c2322.png)

**Comment by JulioMoreton** [comment]
Hello Erik, 

I am getting the same error message when I try to update the source code symbols. I am a Super User so I have all the permissions and I have checked specifically for the Snapshot Debugging permission and I do have it as well as an individual permission. 

I have checked the Simple Object Designer extension and I have the option Allow HttpClient Requests activated. 

BC version 21.3.51409.51575 and Simple Object Designer version 7.0.0.246. 

Before today, I could always update the source code symbols. Any ideas? 


![Error Simple Object Designer ](https://user-images.githubusercontent.com/114618476/217311993-1952e79f-a97a-419f-8e56-e59fb2e5b514.jpg)

**Comment by hougaard** [comment]
Are you a dynamics 365 admin in your tenant?

**Comment by JulioMoreton** [comment]
Yes, I am.

**Comment by hougaard** [comment]
Can you try in a sandbox?

**Comment by JulioMoreton** [comment]
It worked in the sandbox. I tried again in the production environment and I still get the same error.

**Comment by hougaard** [comment]
And you have this?
<img width="645" alt="image" src="https://user-images.githubusercontent.com/3357237/217356446-9e62fab8-bb91-40a0-aa9b-0df47f5c2bc5.png">

**Comment by JulioMoreton** [comment]
I do

![Permissions](https://user-images.githubusercontent.com/114618476/217375623-293bc8cb-50d1-4b4d-a37b-d0f1f13297de.jpg)

**Comment by hougaard** [comment]
That is the permission set giving snapshot debugging permissions.

Not sure how to help you? Can you try with a different users?

**Comment by jmcDEV87** [comment]
Hi Eric,
I've also tried our sandbox environment and can confirm it also works. here but not on our live/production environment.

Still revieing the same error:

Could not contact dynamics.com, error ()

Internal session ID: 
69f4e66f-74cc-4a0d-a240-645e11156ed3

Application Insights session ID: 
75366f86-eec7-4952-ab12-c7e76fcb9fc5

Client activity id: 
f40b4d41-a0a6-44a2-aa58-b0b37a972253

Time stamp on error: 
2023-02-08T09:54:48.2584695Z

AL call stack: 
"Symbol Management Hgd"(CodeUnit 70310251).DownloadFile line 66 - Simple Object Designer by Hougaard
"Symbol Management Hgd"(CodeUnit 70310251).DownloadSymbols line 63 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263).OnOpenPage(Trigger) line 28 - Simple Object Designer by Hougaard


I'm wondering at this point if its easier to to uninstall the SOD extension and reinstall ?
What would happen to any existing APIs  and fields i've added to pages that have been published - would these be lost or still function?
Can our licence key be applied again?

**Comment by JulioMoreton** [comment]
Hello Erik, 

I have tried with another user that has also Super User permissions and the permission ser for the debugging and that user gets the same error.

**Comment by JulioMoreton** [comment]
Hello Erik, 

Any update on this? 

Thank you,
Julio

**Comment by hougaard** [comment]
In my tests, I have not been able to get the error. Are you a global admin on the tenant?

**Comment by jmcDEV87** [comment]
I think these are two separate issues. 
the error message  @JulioMoreton  is receiving is different to one originally reported by my message.  @hougaard  any update on my last post?

**Comment by hougaard** [comment]
> I think these are two separate issues. the error message @JulioMoreton is receiving is different to one originally reported by my message. @hougaard any update on my last post?

Are you getting this error in a sandbox or in production?

**Comment by JulioMoreton** [comment]
> In my tests, I have not been able to get the error. Are you a global admin on the tenant?

Yes, I am a global admin.

**Comment by hougaard** [comment]
@JulioMoreton problem was a permission issue (not having SUPER and snapshot debugging for all companies).

**Comment by jmcDEV87** [comment]
> 

error in production, sandbox is working fine,
refreshes no issue.

**Comment by hougaard** [comment]
@jmcDEV87  Please update your Simple Object Designer to the latest version, I might be able to see more in the telemetry...

**Comment by jmcDEV87** [comment]
@hougaard 
To update I would need to uninstall and install the new extension? uninstalling can you confirm if the existing published content (namely APIs and fields placed on pages) would those be removed or remain?

**Comment by hougaard** [comment]
No, go into Admin Center and update the **Simple Object Designer** - Don't touch the app you have created.

Like this: https://youtu.be/Ei2cf236KWc

**Comment by jmcDEV87** [comment]
> No, go into Admin Center and update the **Simple Object Designer** - Don't touch the app you have created.
> 
> Like this: https://youtu.be/Ei2cf236KWc

Hi, completed the Extension update but still erroring with the following:

Could not contact dynamics.com, error ()

Internal session ID: 
132873a5-ebcd-4dac-b256-fa5d45a1c1f1

Application Insights session ID: 
82f03b39-424f-41af-83d1-08a181361a40

Client activity id: 
1bc2f5ff-597f-4fba-803f-44ea51a10c3d

Time stamp on error: 
2023-02-14T11:50:25.2928603Z

AL call stack: 
"Symbol Management Hgd"(CodeUnit 70310251).DownloadFile line 86 - Simple Object Designer by Hougaard
"Symbol Management Hgd"(CodeUnit 70310251).DownloadSymbols line 65 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263).OnOpenPage(Trigger) line 28 - Simple Object Designer by Hougaard

**Comment by jmcDEV87** [comment]
@hougaard   any update?
ran the refresh today again with this response:

Could not contact dynamics.com, error ()

Internal session ID: 
0a6789a0-9c0b-461d-b0a5-896dc4f7dac2

Application Insights session ID: 
b94943de-4b19-4585-a61f-7857cab710de

Client activity id: 
b91fa884-aa8c-416a-af91-b28ea67bb1de

Time stamp on error: 
2023-02-17T11:44:27.5982808Z

AL call stack: 
"Symbol Management Hgd"(CodeUnit 70310251).DownloadFile line 86 - Simple Object Designer by Hougaard
"Symbol Management Hgd"(CodeUnit 70310251).DownloadSymbols line 65 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263).OnOpenPage(Trigger) line 28 - Simple Object Designer by Hougaard

**Comment by DogmatixAU** [comment]
Telemetry message

d
AL ErrorCode:DB:Ok Connection type:WebClient Message: An error occurred and the transaction is stopped. Contact your administrator or partner for further assistance. StackTrace: "Object Designer Menu Hgd"(Page 70310263).OnOpenPage(Trigger) line 27 - Simple Object Designer by Hougaard

**Comment by jmcDEV87** [comment]
@hougaard 

still the same issue for me also.

Could not contact dynamics.com, error ()

Internal session ID: 
c4666cca-aa6e-4b19-a62e-1bb8ff6d8978

Application Insights session ID: 
de8ae496-2eb0-4f67-a086-6fc380eb137a

Client activity id: 
a11ec613-dfdc-42e1-b575-dd5e36d1766f

Time stamp on error: 
2023-02-22T12:58:39.2958343Z

AL call stack: 
"Symbol Management Hgd"(CodeUnit 70310251).DownloadFile line 86 - Simple Object Designer by Hougaard
"Symbol Management Hgd"(CodeUnit 70310251).DownloadSymbols line 65 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263).OnOpenPage(Trigger) line 28 - Simple Object Designer by Hougaard

Does the call stack tell you anything?
We have further APIs we want to publish to use but we don't want to take any action while we are still getting this error message.

We have had this issue over a month now.

**Comment by jmcDEV87** [comment]
@hougaard   any update or a fix for our issue?  conscious i raised this over a month ago now and i have provided the updates you have requested?

the call stack as of today:

Could not contact dynamics.com, error ()

Internal session ID: 
51eeeea1-c244-4e53-a3f1-113cddda9ad7

Application Insights session ID: 
13c55891-aabb-455c-9595-a4797d47d991

Client activity id: 
f51acd2f-268d-40d4-ac76-87453ac6edd5

Time stamp on error: 
2023-02-28T09:33:53.3328545Z

AL call stack: 
"Symbol Management Hgd"(CodeUnit 70310251).DownloadFile line 86 - Simple Object Designer by Hougaard
"Symbol Management Hgd"(CodeUnit 70310251).DownloadSymbols line 65 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263).OnOpenPage(Trigger) line 28 - Simple Object Designer by Hougaard

**Comment by hougaard** [comment]
Please email support@hougaard.com so we can arrange a teams call, I gotta see this...

**Comment by DogmatixAU** [comment]
Hi Erik.

I am happy to join in on a teams call as well, as I am getting the same problem.

But I am in Perth, Australia (GMT+8) - which I think is around 16hrs ahead of you.



Michael Inga

ERP Practice manager

[Smart Phone]   0418 926 687



________________________________

**Comment by mdstiles** [comment]
Hey, were there any further updates from that teams call? I'm getting a similar error when trying to download symbols on the latest version (9.0.0.294). I have the correct permission sets and am a Dynamics 365 Administrator. I get the following error whenever I try to refresh symbols:
![image](https://github.com/hougaard/Simple-Object-Designer/assets/131403267/ac3dd7f9-3e32-4b95-8ae4-79750df4e7eb)

With a call stack of: 
If requesting support, please provide the following details to help troubleshooting:

Could not contact dynamics.com, error (The credentials provided are incorrect)

Internal session ID: 
7d6f5747-ffd4-4c0a-b0c2-aeaf3e72d187

Application Insights session ID: 
e6500e05-cc65-4085-964c-f9ac667bfbd9

Client activity id: 
46426f65-0765-4702-b755-144a28dd7b97

Time stamp on error: 
2023-05-23T19:18:59.8558190Z

AL call stack: 
"Symbol Management Hgd"(CodeUnit 70310251).DownloadFile line 86 - Simple Object Designer by Hougaard
"Symbol Management Hgd"(CodeUnit 70310251).DownloadAndImportSymbolsFromApp line 15 - Simple Object Designer by Hougaard
"Symbol Management Hgd"(CodeUnit 70310251).DownloadSymbols line 54 - Simple Object Designer by Hougaard
"Simple Field Setup Hgd"(Page 70310250)."Connect - OnAction"(Trigger) line 18 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."Setup - OnAction"(Trigger) line 5 - Simple Object Designer by Hougaard

Please let me know if you have any suggestions or would like to set up a call!

**Comment by hougaard** [comment]
Please report this issue at hougaard.com/support if this is still an issue
