### ISSUE TITLE
Creating role center generates error

### ISSUE THREAD

**Issue by Boezelman** [hougaard/Simple-Object-Designer#145]
When I publish my app SOD generates an error:

Package validation failed due to the following error(s): Features/Unirole/Unirole.RoleCenter.al (21,29) - Error AL0198: Expected one of the application object keywords (codeunit, page, table, report, xmlport, query)
Features/Unirole/Unirole.RoleCenter.al (27,29) - Error AL0198: Expected one of the application object keywords (codeunit, page, table, report, xmlport, query)
Features/Unirole/Unirole.RoleCenter.al (33,29) - Error AL0198: Expected one of the application object keywords (codeunit, page, table, report, xmlport, query)
Features/Unirole/Unirole.RoleCenter.al (39,29) - Error AL0198: Expected one of the application object keywords (codeunit, page, table, report, xmlport, query)
Features/Unirole/Unirole.RoleCenter.al (45,29) - Error AL0198: Expected one of the application object keywords (codeunit, page, table, report, xmlport, query)
Features/Unirole/Unirole.RoleCenter.al (54,29) - Error AL0198: Expected one of the application object keywords (codeunit, page, table, report, xmlport, query)
Features/Unirole/Unirole.RoleCenter.al (61,29) - Error AL0198: Expected one of the application object keywords (codeunit, page, table, report, xmlport, query)
Features/Unirole/Unirole.RoleCenter.al (68,29) - Error AL0198: Expected one of the application object keywords (codeunit, page, table, report, xmlport, query)
Features/Unirole/Unirole.RoleCenter.al (75,29) - Error AL0198: Expected one of the application object keywords (codeunit, page, table, report, xmlport, query)

Am I doing something wrong?

Kind regards.

**Comment by hougaard** [comment]
What version of SOD are you running? We had an issue in an old version where stuff broke if you have a space in the feature name?

**Comment by Boezelman** [comment]
We are on 7.0.0.230

**Comment by hougaard** [comment]
I just found a bug in the rolecenter generation, try switching your language to english before publish....

**Comment by Boezelman** [comment]
Hi Erik, this workaround fixes the issue!

**Comment by hougaard** [comment]
Should also be fixed in 7.0.0.246, try updating.
