### ISSUE TITLE
Hidden fields

### ISSUE THREAD

**Issue by gmotion** [hougaard/Simple-Object-Designer#146]
Can we use SOD to make hidden fields visible? Can we use SOD to change the field from read-only to reading and writing?

Thanks

**Comment by hougaard** [comment]
Hidden? It depends on how it's hidden, if it's added to a page, but marked hidden, then we cannot change that with SOD, but if it's not there, you can add it.

You can not change a field from read-only to edit.

**Comment by gmotion** [comment]
Thanks, Erik,
I am sure there is a reason why SOD doesn't unhide fields. But we have scenarios where the user wants to personalize their page but some fields are not visible to add to the page. What is the fastest way to make a field visible?

Regards,
Ghassan

**Comment by hougaard** [comment]
Version 23 allow showing these fields by default now.
