### ISSUE TITLE
Flow fields

### ISSUE THREAD

**Issue by jdbowles** [hougaard/Simple-Object-Designer#148]
Hi Eric,

I can add flow fields to existing table which is great, although I don't seem to be able to use the functionality in tables that we have created using the new features option.. Is this the "Spring / April-ish" update I have seen on other posts ?

Best 
James

**Comment by hougaard** [comment]
You can just go back and add more field to your feature, that's totally allowed.

**Comment by jdbowles** [comment]
Yes - I tried but when I select flow field on a table I created (by going into features etc) it doesnt seem to default the options under the lookup tab. Attached the screenshot

[SOD - FF issue.docx](https://github.com/hougaard/Simple-Object-Designer/files/10559834/SOD.-.FF.issue.docx)

**Comment by hougaard** [comment]
Ahh. flowfields... coming very soon to features ..... on the workbench right now...

**Comment by jdbowles** [comment]
Ah I'm happy that it wasnt user error. It will be a game changer I think. Thanks for such a speedy response.

**Comment by hougaard** [comment]
Just testing the functionality now, will be available sometime next week.
