### ISSUE TITLE
Permissions Limitations

### ISSUE THREAD

**Issue by ArronKochanowicz** [hougaard/Simple-Object-Designer#149]
Hi Erik,

I just installed the free trial of SOD in a Sandbox environment, created a new feature called "Asset" and exposed it as an API.  I also exposed a couple of fields on the standard Customer table so they can be reached through the "hougaard" endpoint.

Customers Endpoint:
`https://api.businesscentral.dynamics.com/v2.0/{{bcTenantId}}/{{Environment}}/api/hougaard/SOD/v2.0/companies({{bcCompanyId}})/customers`

Assets Endpoint:
`https://api.businesscentral.dynamics.com/v2.0/{{bcTenantId}}/{{Environment}}/api/hougaard/SOD/v2.0/companies({{bcCompanyId}})/assets`

I'm getting a permissions error on the Assets endpoint only:
```
{
    "error": {
        "code": "Internal_ServerError",
        "message": "Sorry, the current permissions prevented the action. (TableData AssetSOD Read: My Customizations)  CorrelationId:  7dc93223-e051-416e-b98d-f2fd053fd990."
    }
}
```

The testing was done in Postman using the same credentials.
Is this perhaps an intended limitation of the trial?

**Comment by hougaard** [comment]
You app is coming with a permission set. Make sure that the user you authentication with from Postman has that permission set assigned. (If S2S, then the Azure Active Directory must have the permission set assigned).

**Comment by ArronKochanowicz** [comment]
This was my first guess too.  I'm authenticating with Client Credentials via a registered Azure app on Postman, but as far as I can tell all permissions are set correctly:

![image](https://user-images.githubusercontent.com/112115079/216656716-f5b7f030-645b-474a-a421-556ca52881e8.png)

I also verified that the ClientId / CleientSecret match with the registered app permissions just in case.
Am I missing something more fundamental?

P.S. thank you for the extremely rapid reply.

**Comment by hougaard** [comment]
No, inside BC, search for "Azure Active Directory", you'll find applicationIDs also have permissions.

**Comment by ArronKochanowicz** [comment]
That did it.  Many thanks!
Maybe this was a no-brainer for other users, but in case it's helpful to others my steps to correct the issue:

- Create a new permission set in BC and specify ("include") the custom table (Assets in my example) in the permission set.
- Add the newly created permission set in the "Azure Active Directory Applications" to the registered app.
