### ISSUE TITLE
Work Description field not presenting correctly on some Word Templates

### ISSUE THREAD

**Issue by InaFie** [hougaard/Simple-Object-Designer#15]
I have added the Work Description field from the Sales Header onto a number of document reports which are being generated through Word Templates.

For some of the reports the field data comes through correctly and in others it looks like a box of sorts that allows you to enter data.  The output is scrambled.

Examples attached.

Thank you for a great product!

Kind Regards
Ina
[Work Description field.docx](https://github.com/hougaard/Simple-Object-Designer/files/7223210/Work.Description.field.docx)

**Comment by hougaard** [comment]
That looks strange, try removing all the boxes/controls in that area and try re-inserting the new field. Word templates can sometimes be quite quirky to work with.

Report 208 runs of Sales Shipment Header (Table 110)

**Comment by InaFie** [comment]
Thank you for the response.  I have tried the suggestion of removing and re-adding but will try again.

Thanks for the information on Report 208.
