### ISSUE TITLE
Transfert a field to a table

### ISSUE THREAD

**Issue by Keg13** [hougaard/Simple-Object-Designer#150]
Hello Erik,
I want to transfert an add field from 27 Item to Production BOM line 99000772
I add the line in the transfert screen
Table source : 27
Table destination : 99000772
Destination : Production BOM Line
Via champs : 11
Destination ID : ONVALIDATE
Via le Champs : No.
The system ask me to create the field in the table 99000772 and I accept, I activate this transfert line and publish the Apps

The field appear in the table but the data is not transfert : for example if I add a Familly with a lookup on a new table, the value in the item card is not transfered to the BO Line when I select the item

Some help ?

Regards

![Capture](https://user-images.githubusercontent.com/124386536/216668382-18831f49-0225-43b7-a216-28dc0b8d7a00.JPG)

**Comment by hougaard** [comment]
I'll add that in the next version.

**Comment by hougaard** [comment]
Added to the next version, look for when support for Mandatory fields(!!!) are coming out.
