### ISSUE TITLE
Add a new field : Type list

### ISSUE THREAD

**Issue by Keg13** [hougaard/Simple-Object-Designer#151]
Hello
When I add a new field, I don't access to end of the type list after Lookup (RecordId, Date Formula, TableFilter and FlowField)
 Some help ?

Bruno

**Comment by hougaard** [comment]
Sorry, not quite sure what you're asking about?

**Comment by Keg13** [comment]
sorry Erik, 

When I add a new field to a table, with my version of SOD I can't select type RecordId, Date Formula, TableFilter and FlowField (the values after lookup) because they don't appear in my list screen and I have not the scrooll you show in your video ....
So at this moment I can't add for example a Flowfield type
Bruno

**Comment by hougaard** [comment]
Ahh... You gotta update, check this out: https://youtu.be/Ei2cf236KWc
