### ISSUE TITLE
Question: Production Installation of SOD

### ISSUE THREAD

**Issue by MrPooks** [hougaard/Simple-Object-Designer#152]
I have only been using SOD in a sandbox, I started with the trial version then purchased and have the license key and want to start using in production.  I just don't know the steps for this, is there a non-trial version for download to install in production, I cannot find that, or do you install the trial version and then insert the key...

**Comment by hougaard** [comment]
The trial version gets upgraded to the full version by entering the license key. Then when you deploy in your sandbox, an app file is also downloaded. That file you can upload in extension management on your production environment.

**Comment by MrPooks** [comment]
So, with a single app this is great, but is it possible to just publish
from the prod environment as well, so both ways?  I would not do that just
asking.


Happy new year Eric!  Thanks for all the help!
