### ISSUE TITLE
Add Field Transfer from Item Journal Lines to Capacity Ledger

### ISSUE THREAD

**Issue by ontron258** [hougaard/Simple-Object-Designer#155]
Hi Erik,
We have a few requirements to build with SOD since a custom app we had is no longer available/broken.
Biggest one is taking several fields from the Item Journal Lines (82) (i.e. Output Journal) and transferring them to the Capacity ledger when posted.

Available transfers are the Value and Item Journals but the Output journal also posts to Capacity Ledger.

![image](https://user-images.githubusercontent.com/125708426/221629805-fbb36899-11e2-40f6-ac13-89482431e91c.png)

Some fields we need to transfer are Prod. Order Line number, Routing Step Finished, Resource ID, and a Notes field.

Is that doable?

**Comment by hougaard** [comment]
I'll add that in the next version if possible.

**Comment by Agordon110799** [comment]
Hi Hougaard. It's this added?

**Comment by hougaard** [comment]
It's in the next version... Same time as mandatory fields(!!!) :)
