### ISSUE TITLE
Cannot connect to API with Flow after we copied a test environment into production

### ISSUE THREAD

**Issue by GerardHamel** [hougaard/Simple-Object-Designer#158]
We try to use the API's produced by Simple Object Designer in the production environment and the connection is not recognized, yet it works in the sandbox environment.

Notes: The production environment was created from a copy that was in the test sandbox.  The publish function works but the API does not connect, do you have a solution?

-----Error Message in Power automate------------------------------------------------------------------------

Could not retrieve values. The dynamic invocation request failed with error: {
  "error": {
    "code": 404,
    "source": "canada-001.azure-apim.net",
    "clientRequestId": "18dcb549-c861-4880-a889-3c3ca115ae87",
    "message": "The response is not in a JSON format.",
    "innerError": "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
  }
}.
[ghamel_Moison Montreal1.0.0.3.zip](https://github.com/hougaard/Simple-Object-Designer/files/10893073/ghamel_Moison.Montreal1.0.0.3.zip)

**Comment by hougaard** [comment]
Is your extension installed in production?

**Comment by GerardHamel** [comment]
Yes it is installed

[cid:0c66960b-ac88-4dfc-a147-0b806a10f34d]


[cid:image001_91b9dcf5-9abc-49c8-9c90-162d4223812f.png] Gérard Hamel
Gestionnaire, Solutions Technologiques
Technology Solutions Manager
T. 514 344-4494, poste Ext. 319

|
6880, chemin de la Côte-de-Liesse, Montréal (QC) H4T 2A1
moissonmontreal.org<https://www.moissonmontreal.org/>
|
[cid:image002_454bfadc-6e9d-4084-9b3e-c917086fd40d.png]<https://www.facebook.com/moissonmtl/> [cid:image003_59948d4c-5886-4ef0-a6d4-8074b934908e.png] <https://www.instagram.com/moissonmontreal/>  [cid:image004_7cf4b082-ce57-4898-8196-a6e83cec4fcb.png] <https://www.linkedin.com/company/moisson-montreal/>  [cid:image005_76e83bcd-9518-4e6a-a1d9-d4d8aa32220f.png] <https://twitter.com/MoissonMTL>  [cid:image006_1e20d8e1-e3a8-46c1-8463-cd19cf452ad0.png] <https://www.youtube.com/channel/UCy8FbjiuE6OMQbvdQTfNpZQ>
<https://www.saq.com/fr/a-propos/responsabilite-societale/aide-alimentaire><https://www.saq.com/fr/a-propos/responsabilite-societale/aide-alimentaire>

 [cid:signature970pxx100px-vert_03bf262f-f067-4236-ace8-631319342ec5.png] <https://www.moissonmontreal.org/nos-donateurs/donateurs-de-denrees/>

________________________________
De : Erik Hougaard ***@***.***>
Envoyé : 5 mars 2023 17:29
À : hougaard/Simple-Object-Designer ***@***.***>
Cc : Gérard Hamel ***@***.***>; Author ***@***.***>
Objet : Re: [hougaard/Simple-Object-Designer] Cannot connect to API with Flow after we copied a test environment into production (Issue #158)


Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>


Is your extension installed in production?

**Comment by hougaard** [comment]
And does the identity that connects from PowerAutomate have permissions?

**Comment by hougaard** [comment]
I get the error here also... Hang on...

**Comment by hougaard** [comment]
It's a Microsoft issue, try selecting the powerbi category

<img width="463" alt="image" src="https://user-images.githubusercontent.com/3357237/222990875-c3de571e-4552-40c7-8e30-9c22c34234d7.png">

I suggest filing a ticket with Microsoft. I'll also let them know.

**Comment by GerardHamel** [comment]
I will open a ticket and yet if I use the API version V2.0 I am able to see the tables

[cid:9898e557-a134-4b86-838f-34c20739c2ed]


[cid:image001_91b9dcf5-9abc-49c8-9c90-162d4223812f.png] Gérard Hamel
Gestionnaire, Solutions Technologiques
Technology Solutions Manager
T. 514 344-4494, poste Ext. 319

|
6880, chemin de la Côte-de-Liesse, Montréal (QC) H4T 2A1
moissonmontreal.org<https://www.moissonmontreal.org/>
|
[cid:image002_454bfadc-6e9d-4084-9b3e-c917086fd40d.png]<https://www.facebook.com/moissonmtl/> [cid:image003_59948d4c-5886-4ef0-a6d4-8074b934908e.png] <https://www.instagram.com/moissonmontreal/>  [cid:image004_7cf4b082-ce57-4898-8196-a6e83cec4fcb.png] <https://www.linkedin.com/company/moisson-montreal/>  [cid:image005_76e83bcd-9518-4e6a-a1d9-d4d8aa32220f.png] <https://twitter.com/MoissonMTL>  [cid:image006_1e20d8e1-e3a8-46c1-8463-cd19cf452ad0.png] <https://www.youtube.com/channel/UCy8FbjiuE6OMQbvdQTfNpZQ>
<https://www.saq.com/fr/a-propos/responsabilite-societale/aide-alimentaire><https://www.saq.com/fr/a-propos/responsabilite-societale/aide-alimentaire>

 [cid:signature970pxx100px-vert_03bf262f-f067-4236-ace8-631319342ec5.png] <https://www.moissonmontreal.org/nos-donateurs/donateurs-de-denrees/>

________________________________
De : Erik Hougaard ***@***.***>
Envoyé : 5 mars 2023 18:01
À : hougaard/Simple-Object-Designer ***@***.***>
Cc : Gérard Hamel ***@***.***>; Author ***@***.***>
Objet : Re: [hougaard/Simple-Object-Designer] Cannot connect to API with Flow after we copied a test environment into production (Issue #158)


Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>


It's a Microsoft issue, try selecting the powerbi category

[https://user-images.githubusercontent.com/3357237/222990875-c3de571e-4552-40c7-8e30-9c22c34234d7.png]<https://user-images.githubusercontent.com/3357237/222990875-c3de571e-4552-40c7-8e30-9c22c34234d7.png>

I suggest filing a ticket with Microsoft. I'll also let them know.

**Comment by hougaard** [comment]
I know, but any category with a publisher/group gives the error right now. It seems to be only Canadian tenants, I just tried on a few US tenants, no issues.
