### ISSUE TITLE
New Field on Customer, Sales Order Header and Sales Order Confirmation Report

### ISSUE THREAD

**Issue by ndfirth** [hougaard/Simple-Object-Designer#159]
Hi, I'm trying to add a field to the Customer Header that will appear in the Sales Header which I've done, but doesn't seem to be available to add to the sales order report 1305. Can this be done with this program?

**Comment by hougaard** [comment]
Yes, follow this:

1. Restart your browser after you have published your extension
2. Go to Custom Report Layout
3. Click "Update Layout" to add new fields to the XML poart
4. Export Layout
5. Edit in Word, new fields should be available
6. Import Layout
7. Succes!

**Comment by ndfirth** [comment]
Hi, yes, I get that part of it, I’ve added the field to the customer header and sales order header successfully, but can’t see how to put on the Sales Order Report 1305. Below is how far I’ve gone.

[Graphical user interface, text, application  Description automatically generated]

In Customer Card

[Table  Description automatically generated]

Field Transfer

[Table  Description automatically generated]

But on the Report Field Placement I don’t see where I can add to Sales Order (1305)

[Table  Description automatically generated]



Nick Firth - español
***@***.******@***.***>
Phone: (800)367-4836 ext. 230
Fax: (703)971-0070
Skype: Xeroxparts
Trillian: Xeroxparts
www.iteminc.com<http://www.iteminc.com>
***@***.***
Parts • Supplies • Service
Xerox • Dell • Lexmark • Konica-Minolta • Samsung • Canon • Oki • Ricoh
