### ISSUE TITLE
CREATE NEW CALC FIELDS

### ISSUE THREAD

**Issue by Agordon110799** [hougaard/Simple-Object-Designer#160]
Hi
We want to create a new calc field in table 1001 Job Task. It must be the difference between two existing fields ( 11 Schedule Total Price - 10 Schedule Total Cost).
Is it possible?
Thanks

**Comment by hougaard** [comment]
Nope, that is not possible. Those two fields are calculated from different fields, flowfields cannot add stuff like that together.

**Comment by Agordon110799** [comment]
And it’s posible to créate a new field with a calculated formula with two fields on the same table?


Antonio Gordón Ribas
Servicios Corporativos
Responsable Administración y Sistemas – Servicios Corporativos
Ronda de Can Rabadà 2, 5º 5ª, Edificio Logic
08860 Castelldefels (Barcelona)
Tel. +34933284328 | Mob. +34610262713 | ***@***.***
[Twitter]<https://twitter.com/Geprom_industry>
[LinkedIn]<https://www.linkedin.com/company/geprom-connecting-industries/>
[YouTube]<https://www.youtube.com/channel/UC5SW_2Q0paTudFrJqlIF7aw>
geprom.com <https://geprom.com/>

***@***.***



De: Erik Hougaard ***@***.***>
Enviado el: miércoles, 8 de marzo de 2023 8:45
Para: hougaard/Simple-Object-Designer ***@***.***>
CC: Antonio Gordon | Geprom ***@***.***>; Author ***@***.***>
Asunto: Re: [hougaard/Simple-Object-Designer] CREATE NEW CALC FIELDS (Issue #160)


Nope, that is not possible. Those two fields are calculated from different fields, flowfields cannot add stuff like that together.

**Comment by hougaard** [comment]
Nope, not possible.

**Comment by Agordon110799** [comment]
thanks

Antonio Gordón Ribas
Servicios Corporativos
Responsable Administración y Sistemas – Servicios Corporativos
Ronda de Can Rabadà 2, 5º 5ª, Edificio Logic
08860 Castelldefels (Barcelona)
Tel. +34933284328 | Mob. +34610262713 | ***@***.***
[Twitter]<https://twitter.com/Geprom_industry>
[LinkedIn]<https://www.linkedin.com/company/geprom-connecting-industries/>
[YouTube]<https://www.youtube.com/channel/UC5SW_2Q0paTudFrJqlIF7aw>
geprom.com <https://geprom.com/>

***@***.***



De: Erik Hougaard ***@***.***>
Enviado el: miércoles, 8 de marzo de 2023 18:38
Para: hougaard/Simple-Object-Designer ***@***.***>
CC: Antonio Gordon | Geprom ***@***.***>; Author ***@***.***>
Asunto: Re: [hougaard/Simple-Object-Designer] CREATE NEW CALC FIELDS (Issue #160)


Nope, not possible.
