### ISSUE TITLE
Mandatory fields

### ISSUE THREAD

**Issue by kfrdsen** [hougaard/Simple-Object-Designer#163]
Hi Erik

It would be a great feature if the Simple Object Designer could make existing fields mandatory. And even better mandatory based on a set of conditions.

**Example of use case**
To automate reporting of duties, item data must include HS Code and Country of Origin. But these fields are not mandatory by default. As a result, lack of data and errors occur.

By making the fields mandatory on the condition that Type = Inventory, lack of data and errors can be eliminated.

/Kristian

**Comment by hougaard** [comment]
Funny you should ask :)

https://youtu.be/Lfk2XAEPLSo
https://youtu.be/B1rxyqR2ZCY

If you need help to update to the latest version: https://youtu.be/Ei2cf236KWc
