### ISSUE TITLE
Cannot update API files in Power BI web with Odata.

### ISSUE THREAD

**Issue by MKEWAS** [hougaard/Simple-Object-Designer#164]
Hi 

I cannot setup my Power BI reports to scheduled updates in web. Everything works fine in Power BI Desktop.
I seems like Power BI cannot reconize the company from the url.

![image](https://user-images.githubusercontent.com/120103105/225120789-f7a6533f-c8e9-4c92-b9a7-80c220dea396.png)

Does anyone have a solution for this issue?

Best regards,

Morten

**Comment by hougaard** [comment]
What format is your URL (with companies(id) or Company=) ?

**Comment by MKEWAS** [comment]
.../api/hougaard/SOD/v2.0/companies(eae3d41c-6790-eb11-8ce5-0022489c32e2)/value_Entrys

I think i can get it updating if i use API as web source but i have limitation of 20.000 lines. So that does not work me.
And when i use Odata i get the abovementioned error.

**Comment by hougaard** [comment]
The 20.000 is a general OData limitation, you can use $top and $skip to get more records.

https://learn.microsoft.com/en-us/odata/client/pagination

**Comment by MKEWAS** [comment]
When I use OData in power bi desktop there is no limit to number of records. Only when i use web.
I am not a skilled coder som i need help to the pagination.

But is it possible to change the url to include the company instead of companyID?

**Comment by MKEWAS** [comment]
I found a solution. If I use the Business Central Connector in Power BI there is no issue toward the number of lines.
Thanks for helping out.

![image](https://user-images.githubusercontent.com/120103105/225540306-a0f99599-030b-4e46-857f-08ddaaa06ac3.png)
