### ISSUE TITLE
Remove options e.g. Item Journal Entry Type

### ISSUE THREAD

**Issue by kfrdsen** [hougaard/Simple-Object-Designer#165]
Hi Erik

It would be a great feature if the Simple Object Designer could remove options in standard fields.

Example of use case
https://community.dynamics.com/nav/f/microsoft-dynamics-nav-forum/433702/remove-entry-type-options-in-item-journals-form-nav-2009

/Kristian

**Comment by hougaard** [comment]
Not "remove", but you can use the new Mandatory Fields functionality to not allow the usage of certain values in journals and documents.
