### ISSUE TITLE
Field Transfer from table 900 to 910

### ISSUE THREAD

**Issue by Lennardleenheer** [hougaard/Simple-Object-Designer#17]
Hi Erik,
Would it be possible to make a field transfer from a assembly order to a booked assembly order ( table 900 to 910 )

**Comment by hougaard** [comment]
It's not necessary to do explicit, as long as your adding the same fields (and they get the same field numbers) then the transfer happens automatically.
(Use personalization to show the field number assigned to your fields in the new field list page).

**Comment by Lennardleenheer** [comment]
doe this also work somehow for existing fields, I want to transfer item field Vendor Item Number ( so 27 32  ) to purchase order lines.
