### ISSUE TITLE
Note-field blanked when posting invoice

### ISSUE THREAD

**Issue by HMadsen4000** [hougaard/Simple-Object-Designer#172]
Hi all

I have added a note-field to Sales Order Header, to be used on shipping notes and invoices.

It transfers fine to the Sales Invoice Header, but when the invoice is posted the field is blanked.

I have activated the transfer on the Sales Invoice Header to Sales Invoice Header with the comment "For edit of posted document"

The field is visible on the page showing the posted invoice, but it is empty.

Any ideas?

Regards
Henrik Madsen

**Comment by hougaard** [comment]
What version of the Simple Object Designer are you using, because something changed around this, and we moved that field transfer to a different event.

If you are on an old version, please upgrade and publish again.

**Comment by HMadsen4000** [comment]
I tried with a singe line text it worked fine, but with a multi-line field the content is not transferred

**Comment by hougaard** [comment]
When you say "multi-line", are you changing the field type?

**Comment by hougaard** [comment]
Have you chosen multi-line on both pages?

**Comment by hougaard** [comment]
Please report this issue at hougaard.com/support if this is still an issue
