### ISSUE TITLE
Having Trouble with Flow Field (Advanced Case)

### ISSUE THREAD

**Issue by GrooveRings** [hougaard/Simple-Object-Designer#173]
Hi Erik,
I'm attempting to add a flow field to the item card. This flow field should pull the available quantity for the "bottleneck" item from the BOM Buffer table for the current date. I've published this and I am not getting an error but it's showing 0 for all the items when it should be a quantity. Am I doing something wrong or will this method not work?

(As I was writing this, I realize that I'm looking at the available quantity of the parent item no. which will always be 0 in my case. So it's working as I told it to. So now I can't figure out how to do down to the BOM level to retrieve the bottleneck available quantity to publish on the item card of the parent item no.)

![image](https://user-images.githubusercontent.com/82909149/228684760-88d7995c-99c9-4d1d-9557-59800ed0f2f9.png)

![image](https://user-images.githubusercontent.com/82909149/228684835-8b81e725-5a4d-4ec4-bf19-0d7004efd415.png)

**Comment by hougaard** [comment]
"today" doesn't work. It's not possible to set a flowfield filter for today :(

**Comment by GrooveRings** [comment]
Do you have a suggestion on how we can retrieve the qty available based on the bottleneck item in the BOM buffer table? I created an API for that table but when I preview it in Power BI the table is blank.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/82909149/230968143-58ddd9c5-0fab-4448-a9d3-67aa2bafdcc1.png">

**Comment by hougaard** [comment]
That table is temporary, so the content is calculated when you open the page inside BC then content is calculated and stored temporary in the server's memory. When exposing as an API there's never a calculation phase happening.

This is beyond "Simple" because the BOM Buffer is used from multiple different places, so there's is no simple way of exposing the data.
