### ISSUE TITLE
FlowField behavior

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#174]
Hello,

I have created several FlowFields, mainly to count the number of items to be shown in another table. And this works, but...

I have created one FlowField in the Item table, to count this item is used in non-business central standard table (trazabilidad table), and in the Items page, it shows as a number, I click on the number, and it shows the trazabilidad table filtered for this item:

See the field "Usado en Equipos":

![image](https://user-images.githubusercontent.com/99739571/228881310-6e20288c-63b1-48dd-9104-dc1371230af7.png)

When I click it shows the "Trazabilidad" table properly filtered:

![image](https://user-images.githubusercontent.com/99739571/228881585-aa54384d-5f32-407f-b518-11295cc66371.png)

However, I have now created a similar FlowField (with the "Count" option) in the Service Item table, and it does the work counting the records of a different table, but I cannot click on the number to show the second table filtered:

See the field "TS":

![image](https://user-images.githubusercontent.com/99739571/228882120-ac510e9b-8a26-4bd5-be4f-1486227f9e70.png)

Is there anything different I can setup to obtain the first behavior?

Thanks in advance

**Comment by hougaard** [comment]
Hmm.... let me check...

**Comment by juasanri** [comment]
Any news on this?

Thanks...

**Comment by hougaard** [comment]
Fix coming in the next version (But I'm at the Directions conference this week, so I'm a bit slow)
