### ISSUE TITLE
FlowField Lookup question

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#176]
Hello,

I have created a FlowField to show the Net Weight of an Item in the lines of a Service Order, with the "Lookup" option. And it works, but it only displays 2 decimal places in the Service Lines, although in the Item card it has more decimal places. 
For items that have a weight less than 0.004 Kg, it shows 0.00.

It is the "Peso Neto" field, take a look to the first line, it is 0.00:

![image](https://user-images.githubusercontent.com/99739571/228883437-47afca52-e42b-4100-a418-9927fa47e454.png)

However, in the Item card, the net weight is 0.001:

![image](https://user-images.githubusercontent.com/99739571/228883720-e5aef75b-5aca-440a-8b11-3ff57747f194.png)

Is there a way to show exactly the same number?

Thank in advance!

**Comment by hougaard** [comment]
I have never exposed the decimal place property, so right now it's not possible.... But a very good suggestion.

**Comment by juasanri** [comment]
Ok, thank you
