### ISSUE TITLE
Update to version 8.0.0.270 not possible

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#178]
Hello,

I am running SOD version 7.0.0.254 and to update to 8.0.0.270 there is an "Action Required":

![image](https://user-images.githubusercontent.com/99739571/229763178-2e9d9947-bcfc-4066-91b8-78641fbdd9c6.png)

![image](https://user-images.githubusercontent.com/99739571/229763225-8e67c75d-b41f-46dd-9275-be90a8399847.png)

However, I cannot find and install this app in the Extension MarketPlace:

Only the SOD and the following ones:

![image](https://user-images.githubusercontent.com/99739571/229763378-27af9ac7-c350-4b32-b01e-dde0c5354d96.png)

How can I proceed?

Thanks

**Comment by hougaard** [comment]
That should happen automatically, weird? 

Anyway, there's an easy fix, simply install my "ToolBox" app, then you're also getting the unlisted AL Compiler app.

**Comment by juasanri** [comment]
It happened automatically after I pressed the "Update to Latest Version", sorry for bothering.
