### ISSUE TITLE
Standard Text Transfers

### ISSUE THREAD

**Issue by DogmatixAU** [hougaard/Simple-Object-Designer#18]
We have added a new field to items, that transfers onto sales lines. I have also created the same field onto the Standard Text field (#7) which also need to transfer onto the sales line. 

Can you add the sales line & purchase line tables available as transfer targets from Standard Text table?

Thanks

![SOD Image 1](https://user-images.githubusercontent.com/92653294/137603961-411378a0-e267-48a7-ac67-c323602076a1.png)
![SOD Image 2](https://user-images.githubusercontent.com/92653294/137603964-9298f905-5cba-4fa8-ac95-745e65851fee.png)

**Comment by hougaard** [comment]
Added, check for version 1.0.0.55 in Admin Center.

**Comment by DogmatixAU** [comment]
Thanks for the quick Response Erik. But I am not sure what/where you are referring to as the Admin Centre?

The latest version in Marketplace is 2.0.0.54.



Michael Inga
ERP Practice Manager | CFO
0418 926 687
