### ISSUE TITLE
Lookup User table (2000000120) 

### ISSUE THREAD

**Issue by GDU-ACY** [hougaard/Simple-Object-Designer#181]
The User table (2000000120) is not accessible from a lookup, is it possible to make it accessible?

**Comment by hougaard** [comment]
The challenge is, that the primary key is the security id GUID, not what users see as the userid. So a lookup to that table needs a lot of behind-the-scene code to be nice.

An alternative is to use the "User Setup" table instead.

**Comment by GDU-ACY** [comment]
I did the lookup with the user parameter table.thank you
