### ISSUE TITLE
Error AL0654 from previously successful published extension

### ISSUE THREAD

**Issue by ndfirth** [hougaard/Simple-Object-Designer#184]
Getting the error below when trying to add a field to the sales order, looks to be from a previous successfull publishing. I see it's there as an RDLC default report which is what I'm using for that report, but not sure why it's giving this error now or how to fix?

Package validation failed due to the following error(s): ReportExtensions/IWX_Picking_List_ReportExt.al (3,18) - Error AL0654: The property value contains an unexpected file extension: .rdlc. The expected extensions are .docx. 

![Picking List](https://user-images.githubusercontent.com/103513553/230533299-f8126560-a5ca-430d-a79a-c4f20ea6c472.PNG)

**Comment by ndfirth** [comment]
I see in the code that it's an RDLC Layout, but not sure why it's looking for docx




Reportextension 50667 "SODIWX_Picking_List" extends "IWX Picking List"
{
    RDLCLayout = './IWX_Picking_List.rdlc';

    dataset
    {
        add("WhseActLine")
        {
            column("Description_2_WhseActLine_SOD"; "WhseActLine"."Description 2")
            {
            }
        }
        add("WhseActLine")
        {
            column("Description_2_WhseActLine_Lbl_SOD"; "WhseActLine".FieldCaption("Description 2"))
            {
            }
        }
        add("Warehouse Activity Header")
        {
            column("Special_Instructions_Warehouse_Activity_Header_SOD"; "Warehouse Activity Header"."Special_Instructions")
            {
            }
        }
        add("Warehouse Activity Header")
        {
            column("Special_Instructions_Warehouse_Activity_Header_Lbl_SOD"; "Warehouse Activity Header".FieldCaption("Special_Instructions"))
            {
            }
        }
    }
}

**Comment by hougaard** [comment]
Do you have multiple extensions created or is it only one?

**Comment by ndfirth** [comment]
Only one

Nick Firth - español
***@***.******@***.***>
Phone: (800)367-4836 ext. 230
Fax: (703)971-0070
Skype: Xeroxparts
Trillian: Xeroxparts
www.iteminconline.com<http://www.iteminconline.com/>
***@***.***
Parts • Supplies • Service
Xerox • Dell • Lexmark • Konica-Minolta • Samsung • Canon • Oki • Ricoh

**Comment by hougaard** [comment]
You better send your app (Export from Setup page) and the generated .app file to support@hougaard.com - Then we'll take a look at it.
