### ISSUE TITLE
Page assignment

### ISSUE THREAD

**Issue by GDU-ACY** [hougaard/Simple-Object-Designer#185]
Hello,
It is not possible to assign a page created by an SOD document template in new fields of type flowfield on the article table for example.
Document template
![image](https://user-images.githubusercontent.com/129877589/231493346-b7b1a086-0eed-45ac-8f42-0c3b248be933.png)

Page inspection 56011
![image](https://user-images.githubusercontent.com/129877589/231494106-bdda6307-2786-49ff-822b-11e1522267a2.png)

In Item table a create a new field type flowfield
![image](https://user-images.githubusercontent.com/129877589/231494588-247a776b-8362-42ef-b7c2-72c47980ee1d.png)

It is not possible to assign a page created by an SOD document template
![image](https://user-images.githubusercontent.com/129877589/231495219-392476f5-1114-4cde-942b-c01922cb83ce.png)

![image](https://user-images.githubusercontent.com/129877589/231495750-3c1e5c5d-def5-41ec-b04c-f954b2997f93.png)

**Comment by hougaard** [comment]
I'll fix that.
