### ISSUE TITLE
Users cannot see published fields

### ISSUE THREAD

**Issue by RGI100** [hougaard/Simple-Object-Designer#186]
I have added new fields but these cannot be seen by the users, even through personalization. Are there security settings that need to be added ?

**Comment by hougaard** [comment]
There should be no security implications for just fields, is the extension published successfully?

**Comment by RGI100** [comment]
Hi Erik,

Yes, these were successfully published.

Many thanks

**Comment by krhee1026** [comment]
Hello,  I am also having this issue.  I am in a sandbox environment and have added some fields on top of an extension from the marketplace.  I am able to see the fields that I've added, but other users are not.

**Comment by hougaard** [comment]
I see two possible solutions:

1. They have personalized the page and the personalization are preventing the new fields from showing. Use "Personalized pages" to delete the personalization.
2. The users do not have permissions, try temporary setting one of the SUPER to test that theory.

**Comment by hougaard** [comment]
Have you added the permission set(*) from your new app to the user?

(*) Yes, every app published must supply a permission set.

**Comment by krhee1026** [comment]
I did not!  I looked again and saw the “SIMPLE OBJECT DESIGNER” permission set and added this on.  This resolved the issue for me, thank you.

[A black and white sign  Description automatically generated with low confidence]
Kevin Rhee
***@***.******@***.***>
T: 410-381-9000 ext.1711  C: 443-851-0610


[Text  Description automatically generated]
