### ISSUE TITLE
Repeat and update field from Sales Header to Sales Lines

### ISSUE THREAD

**Issue by MKEWAS** [hougaard/Simple-Object-Designer#190]
Hi
Is it possible to make a field from Sales Header and repeat it on every Sales Lines with SOD?

The same way Business Central does it with for example Shipping Agent Code.
If a change are made BC ask me if i wan't to update all Sales Lines.

Is it possible to do the same thing for Your_reference or du you need to code something?

**Comment by hougaard** [comment]
Sorry, but no, the "update all lines" is a code-based approach, but you could create a Lookup FlowField on the lines table that lookup a field from the header, sortof the same result?

**Comment by MKEWAS** [comment]
Thank you Erik. 🙂
I created the field with help from your turturial video.
https://www.hougaard.com/sod-user-guide-create/


Still love the App...

________________________________
Fra: Erik Hougaard ***@***.***>
Sendt: 19. april 2023 14:03
Til: hougaard/Simple-Object-Designer ***@***.***>
Cc: Morten Eriksen ***@***.***>; Author ***@***.***>
Emne: Re: [hougaard/Simple-Object-Designer] Repeat and update field from Sales Header to Sales Lines (Issue #190)


Sorry, but no, the "update all lines" is a code-based approach, but you could create a Lookup FlowField on the lines table that lookup a field from the header, sortof the same result?
