### ISSUE TITLE
Cannot publish app

### ISSUE THREAD

**Issue by RGI100** [hougaard/Simple-Object-Designer#191]
I have deleted a table and I am trying to publish my app but get the following error 

"The Table Metadata Hgd does not exist. Identification fields and values : Table No = 50620"

Please could you advise how the resolve.

Thank you

**Comment by hougaard** [comment]
Please refresh your Symbols and try again.

**Comment by RGI100** [comment]
Thank you Erik, unfortunate that did not work, same issue.

Lindsay Smith
Director of Information Systems

[Logo  Description automatically generated]
TEAMWORK~OWN IT~POSITIVITY
[Marker with solid ***@***.***,-122.0125659,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5484476c166f84c7:0x180398ab30dc54e9!2m2!1d-122.0128322!2d49.1177372>43756 South Sumas, Chilliwack, B.C. V2R 4L6
[Receiver with solid fill]778-704-0734 Ext. 109
[Smart Phone with solid fill]778-808-7006
[Telephone with solid fill](877) 866-8100
[Cursor with solid fill]<http://www.rainbow.ca/>www.rainbow.ca<http://www.rainbow.ca/>
***@***.******@***.***<https://www.instagram.com/rainbowgreenhouses/> ***@***.*** <https://www.linkedin.com/company/rainbow-greenhouses/mycompany/>  ***@***.*** <https://www.youtube.com/channel/UC3WQpUA2p-Ghl5drqR7X4AQ>

**Comment by hougaard** [comment]
Email me the extra info you can copy to the clipboard when you get the error. It sounds like you go a reference to a field that no longer exists?

**Comment by RGI100** [comment]
Thank you Erik,

Please see below:

The Table Metadata Hgd does not exist. Identification fields and values: Table No.='50620'

Internal session ID:
e6b56838-8227-47b8-be30-61f3c416f143

Application Insights session ID:
127cae73-ca5d-4a18-8ead-824b447d6245

Client activity id:
d7174b4e-f4ff-462d-b04c-638f523c6b7b

Time stamp on error:
2023-04-25T20:48:09.7702040Z

AL call stack:
"Build Extension Hgd"(CodeUnit 70310250).ExportTableExtensions line 177 - Simple Object Designer by Hougaard
"Build Extension Hgd"(CodeUnit 70310250).CreateExtensionEx line 229 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."ExportExtension - OnAction"(Trigger) line 6 - Simple Object Designer by Hougaard

Regards

Lindsay Smith
Director of Information Systems

[Logo  Description automatically generated]
TEAMWORK~OWN IT~POSITIVITY
[Marker with solid ***@***.***,-122.0125659,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5484476c166f84c7:0x180398ab30dc54e9!2m2!1d-122.0128322!2d49.1177372>43756 South Sumas, Chilliwack, B.C. V2R 4L6
[Receiver with solid fill]778-704-0734 Ext. 109
[Smart Phone with solid fill]778-808-7006
[Telephone with solid fill](877) 866-8100
[Cursor with solid fill]<http://www.rainbow.ca/>www.rainbow.ca<http://www.rainbow.ca/>
***@***.******@***.***<https://www.instagram.com/rainbowgreenhouses/> ***@***.*** <https://www.linkedin.com/company/rainbow-greenhouses/mycompany/>  ***@***.*** <https://www.youtube.com/channel/UC3WQpUA2p-Ghl5drqR7X4AQ>

**Comment by RGI100** [comment]
Hi Erik,

I hope you are doing well. I am just following up to see if there is any feedback on this.

Many thanks

Lindsay Smith
Director of Information Systems

[Logo  Description automatically generated]
TEAMWORK~OWN IT~POSITIVITY
[Marker with solid ***@***.***,-122.0125659,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5484476c166f84c7:0x180398ab30dc54e9!2m2!1d-122.0128322!2d49.1177372>43756 South Sumas, Chilliwack, B.C. V2R 4L6
[Receiver with solid fill]778-704-0734 Ext. 109
[Smart Phone with solid fill]778-808-7006
[Telephone with solid fill](877) 866-8100
[Cursor with solid fill]<http://www.rainbow.ca/>www.rainbow.ca<http://www.rainbow.ca/>
***@***.******@***.***<https://www.instagram.com/rainbowgreenhouses/> ***@***.*** <https://www.linkedin.com/company/rainbow-greenhouses/mycompany/>  ***@***.*** <https://www.youtube.com/channel/UC3WQpUA2p-Ghl5drqR7X4AQ>

From: Lindsay Smith
Sent: Tuesday, April 25, 2023 1:51 PM
To: hougaard/Simple-Object-Designer ***@***.***>; hougaard/Simple-Object-Designer ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [hougaard/Simple-Object-Designer] Cannot publish app (Issue #191)

Thank you Erik,

Please see below:

The Table Metadata Hgd does not exist. Identification fields and values: Table No.='50620'

Internal session ID:
e6b56838-8227-47b8-be30-61f3c416f143

Application Insights session ID:
127cae73-ca5d-4a18-8ead-824b447d6245

Client activity id:
d7174b4e-f4ff-462d-b04c-638f523c6b7b

Time stamp on error:
2023-04-25T20:48:09.7702040Z

AL call stack:
"Build Extension Hgd"(CodeUnit 70310250).ExportTableExtensions line 177 - Simple Object Designer by Hougaard
"Build Extension Hgd"(CodeUnit 70310250).CreateExtensionEx line 229 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."ExportExtension - OnAction"(Trigger) line 6 - Simple Object Designer by Hougaard

Regards

Lindsay Smith
Director of Information Systems

[Logo  Description automatically generated]
TEAMWORK~OWN IT~POSITIVITY
[Marker with solid ***@***.***,-122.0125659,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5484476c166f84c7:0x180398ab30dc54e9!2m2!1d-122.0128322!2d49.1177372>43756 South Sumas, Chilliwack, B.C. V2R 4L6
[Receiver with solid fill]778-704-0734 Ext. 109
[Smart Phone with solid fill]778-808-7006
[Telephone with solid fill](877) 866-8100
[Cursor with solid fill]<http://www.rainbow.ca/>www.rainbow.ca<http://www.rainbow.ca/>
***@***.******@***.***<https://www.instagram.com/rainbowgreenhouses/> ***@***.*** <https://www.linkedin.com/company/rainbow-greenhouses/mycompany/>  ***@***.*** <https://www.youtube.com/channel/UC3WQpUA2p-Ghl5drqR7X4AQ>
