### ISSUE TITLE
New Issue when publishing, "you do not have sufficient permissions"

### ISSUE THREAD

**Issue by RGI100** [hougaard/Simple-Object-Designer#194]
This issues has only started occurring today; Simple Object Designer was publishing yesterday and no changes have been made.

When i attempt to publish I get the following error:

"You do not have sufficient permissions to manage extensions. Please contact your administrator."

I have both D365 FULL ACCESS and D365 EXTENSION MGT access. We also have not updated the version of Business Central. 

I carried out the following troubleshooting measures:
!. Updated the symbols in Simple Object Designer as a troubleshooting measure.
2. Upgraded to version 9.0.0.285 of Simple Object Designer and version 1.0.0.201 of the Al Complier and now i am unable to update the symbols, i get the following error: "Could not contact dynamics.com, error ({"message":"You do not have the following permission: Snapshot debugging"})"

**Comment by RGI100** [comment]
We found the issue, was related to Business Central.

**Comment by hougaard** [comment]
What was the issue, I hear the same from other customer?

**Comment by RGI100** [comment]
Thank you Erik,

My Business Central license in the Office 365 Portal was accidentally deactivated, but because I am an administrator in Business Central it allowed me to log in and do other things. I only realized that this was an issue was an issue in Business Central when I tried to install a new extension.

Regards


Lindsay Smith
Director of Information Systems

[Logo  Description automatically generated]
TEAMWORK~OWN IT~POSITIVITY
[Marker with solid ***@***.***,-122.0125659,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5484476c166f84c7:0x180398ab30dc54e9!2m2!1d-122.0128322!2d49.1177372>43756 South Sumas, Chilliwack, B.C. V2R 4L6
[Receiver with solid fill]778-704-0734 Ext. 109
[Smart Phone with solid fill]778-808-7006
[Telephone with solid fill](877) 866-8100
[Cursor with solid fill]<http://www.rainbow.ca/>www.rainbow.ca<http://www.rainbow.ca/>
***@***.******@***.***<https://www.instagram.com/rainbowgreenhouses/> ***@***.*** <https://www.linkedin.com/company/rainbow-greenhouses/mycompany/>  ***@***.*** <https://www.youtube.com/channel/UC3WQpUA2p-Ghl5drqR7X4AQ>

**Comment by hougaard** [comment]
OK, thanks
