### ISSUE TITLE
Suggestion : Date calulcations

### ISSUE THREAD

**Issue by RGI100** [hougaard/Simple-Object-Designer#196]
It would be great if you could include a way had a custom, date calculation field. For example, we operate mostly in weeks and there are several areas in the system, like the released product orders or lot number expiry date, that we would like to convert to the current week of the year and have this show in field. 

I have reviewed the "Be a date wizard" video (https://www.youtube.com/watch?v=ldSSu-VUJ60) and if this functionality could be included in Simple Object Designer.

**Comment by hougaard** [comment]
This can be done now with the calculated field support
