### ISSUE TITLE
Receiving an error when attempting to publish after delete

### ISSUE THREAD

**Issue by RGI100** [hougaard/Simple-Object-Designer#197]
When attempting to publish after deleting a field i get the following error:

Package validation failed due to the following error(s): Management/FieldManagement.al (83,21) - Error AL0132: 'Record "Purchase Line"' does not contain a definition for 'No_'

I have checked the purchase line fields, both in existing records and new records and cannot find a link. Is there a way for me to find what the cause of the error is.

**Comment by hougaard** [comment]
That is very weird, please check your field transfers..

**Comment by RGI100** [comment]
Thank you Erik, that pointed me in the right direction.

It seems that there is a bug in Simple Object Designer.

I setup the following transfer field:

***@***.***


***@***.***

This was causing errors throughout the system, for example when editing a sales order line , running MRP or changing an item:

***@***.***

For example

***@***.***

We logged with Microsoft and after they run through the telemetry found that this was causing the issue.

Regards

Lindsay Smith
Director of Information Systems

[Logo  Description automatically generated]
TEAMWORK~OWN IT~POSITIVITY
[Marker with solid ***@***.***,-122.0125659,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5484476c166f84c7:0x180398ab30dc54e9!2m2!1d-122.0128322!2d49.1177372>43756 South Sumas, Chilliwack, B.C. V2R 4L6
[Receiver with solid fill]778-704-0734 Ext. 109
[Smart Phone with solid fill]778-808-7006
[Telephone with solid fill](877) 866-8100
[Cursor with solid fill]<http://www.rainbow.ca/>www.rainbow.ca<http://www.rainbow.ca/>
***@***.******@***.***<https://www.instagram.com/rainbowgreenhouses/> ***@***.*** <https://www.linkedin.com/company/rainbow-greenhouses/mycompany/>  ***@***.*** <https://www.youtube.com/channel/UC3WQpUA2p-Ghl5drqR7X4AQ>

**Comment by hougaard** [comment]
Screenshots get's removed when you email to the github issue... send them directly to support@hougaard.com please.
