### ISSUE TITLE
Report doesn't work with TempSalesShpLineNo

### ISSUE THREAD

**Issue by MarkMatthewsJr** [hougaard/Simple-Object-Designer#200]
We need to get the Manufacturer to show up on this Report.  The problem is that it uses the Temp as opposed to Non-Temp.  Do you know of a way to fix it?

![image](https://github.com/hougaard/Simple-Object-Designer/assets/80910139/c97758e4-1c2f-4b09-ab51-f31150ecb242)

![image](https://github.com/hougaard/Simple-Object-Designer/assets/80910139/30e67588-a3e4-4152-89cc-71073836a5f3)

**Comment by hougaard** [comment]
What report number?

**Comment by MarkMatthewsJr** [comment]
50004 – Sales Shipment – Lehr


Mark Matthews
IT Manager

Lehr - Nevada
9240 Prototype Dr | Reno, NV 89521
direct 775-507-2474 | telephone 775-507-2460

**Comment by hougaard** [comment]
That's a custom report, nothing I can do for that, sorry :(

**Comment by MarkMatthewsJr** [comment]
208 works.  1007x Doesn’t work.  So, 208 is what I got.

Mark Matthews
IT Manager

Lehr - Nevada
9240 Prototype Dr | Reno, NV 89521
direct 775-507-2474 | telephone 775-507-2460
