### ISSUE TITLE
Added field in table is not part of the API

### ISSUE THREAD

**Issue by johannel7** [hougaard/Simple-Object-Designer#204]
![image](https://github.com/hougaard/Simple-Object-Designer/assets/133975778/e295082c-c5e9-4fbb-95f6-bced1a5362c3)

in the API I do not see this new field

![image](https://github.com/hougaard/Simple-Object-Designer/assets/133975778/155c8ef9-d4bd-4fdd-8ff9-838272dfb99f)

**Comment by hougaard** [comment]
Scroll down, it should be there, but at the bottom of the field list?

**Comment by johannel7** [comment]
Apologies, I did a filter and it did not show up…
It is there however (not in the order I expected) thanks!

I loooooove this tool! 😊

Johanne

Johanne Laurendeau
ERP Consultant |Conseillère ERP
***@***.******@***.***> | 514-323-3535, 132 | 514-242-0691

**Comment by hougaard** [comment]
They're ordered by field numbers :)
