### ISSUE TITLE
Filter syntax

### ISSUE THREAD

**Issue by GDU-ACY** [hougaard/Simple-Object-Designer#205]
Hello,
What syntax should be written to filter on an empty or 0D date?
![image](https://github.com/hougaard/Simple-Object-Designer/assets/129877589/d1c6a874-0391-4b10-acd9-64e230254f80)

**Comment by hougaard** [comment]
Try with CONST and 0D.

**Comment by GDU-ACY** [comment]
and to do the opposite <>OD does not work
![image](https://github.com/hougaard/Simple-Object-Designer/assets/129877589/05ca4e85-508a-41cf-8255-5bbe62a013d0)
![image](https://github.com/hougaard/Simple-Object-Designer/assets/129877589/f81ba5f1-ce0d-44a7-9030-e8ec5c2d598d)

**Comment by hougaard** [comment]
Not supported, but I guess you can specify a filter range 1980.1.1..2099.12.31 or something like that?

**Comment by GDU-ACY** [comment]
not just a list of records with a date
