### ISSUE TITLE
Calculated Field filter

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#206]
Hello,

Thanks for adding the calculated fields feature, it works perfect. I have a question though.

I have created a calculated field in my Item Card. It is a sumation of the inventory, the qty on purchase orders and qty on production order, minus the qty on service orders, sales orders, and componente lines.
I have added this field to Item Card (page 30) and Item List (page 31)

If negative, it means that I should place a purchase order for this item because I need right now.

The idea of having this field was to create a view with a filter in the Item List, but I have just found out that I cannot place a filter by this new field. Is this something expected?

Thanks in advance.

**Comment by hougaard** [comment]
> Is this something expected?

Yes, that's expected, a filter is applied during data retrieval, the calculation is performed after the data has been retrieved.
