### ISSUE TITLE
Field Transfer from Sales Return Order to Posted Sales Credit Memo

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#21]
I created fields for Sales Order Header table 36 and Line table 47 for use on the Sales Return Order Header & Lines pages (6630 & 6631). I would like to have a field transfer so that I can the data from these fields go to the Posted Credit Memo Header table 114 and Line table 115. 

I would also like to be able to have the fields be placed and made visible on the Posted Credit Memo Header and Line pages 134 & 135 as well as Posted Credit Memo list page 144. 

I would also like to add it to my posted credit memo report id 50106 (custom report), but I believe I can't add it here because the fields don't exist on the posted credit memo tables

**Comment by ScottB-Ronco** [comment]
I would also like to to have a transfer from Sales Return Order Header table 36 and Line table 47 to Sales Return Order Archive Header table 5107 and Line table 5108.

Along with it being visible on Sales Return Order Archive Header page 6627 and Line page 5108 along with Sales Return Order Archive List page 6629

**Comment by hougaard** [comment]
I have added field transfer options that can be selected for those tables, look for an update in admin center next week.
