### ISSUE TITLE
Create New sections on Pages

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#214]
Does SOD have the option to create new sections on pages like Sales Order & Purchase Order?

An example of what I mean on Purchase Order page you have sections called General, Invoice Details & Shipping and Payment. These sections help segregate fields into more meaningful areas.

We have a bunch of fields we want to create but would like to put them into there own section that can be expanded/collapsed to show or hide the entire section of fields.

**Comment by hougaard** [comment]
I'm working on that right now, coming "soon".

**Comment by ScottB-Ronco** [comment]
That is good news!

By chance do you have an ETA of when it be available? Is it days, weeks or months?

I know that some things in BC look simple to do, but in fact are not. So if it is still a ways away then I understand.

**Comment by hougaard** [comment]
Weeks, hope to have it done during July.

**Comment by ScottB-Ronco** [comment]
OK that works.

Now if decide to add all the fields we want to the system now, under the current sections available in BC, once your new feature is available will we be able to change the fields in SOD to move them into the new section that we create with SOD?

**Comment by ScottB-Ronco** [comment]
By chance will you (or could you) also provide a means to move current sections (groups) around?

For Example on Purchase Order page there is the Shipping section. I know I can move the fields, but it would be nice to move the whole section to be above the line subform for a more consistent data entry process.

**Comment by hougaard** [comment]
That's not part of any plans right now....

**Comment by otherjoel** [comment]
> By chance will you (or could you) also provide a means to move current sections (groups) around?
> 
> For Example on Purchase Order page there is the Shipping section. I know I can move the fields, but it would be nice to move the whole section to be above the line subform for a more consistent data entry process.

If I understand correctly what you’re describing, this is already possible with personalization. A few of my users have moved the shipping section above the lines on their sales orders and sales quotes.

**Comment by ScottB-Ronco** [comment]
> > By chance will you (or could you) also provide a means to move current sections (groups) around?
> > For Example on Purchase Order page there is the Shipping section. I know I can move the fields, but it would be nice to move the whole section to be above the line subform for a more consistent data entry process.
> 
> If I understand correctly what you’re describing, this is already possible with personalization. A few of my users have moved the shipping section above the lines on their sales orders and sales quotes.

I tried to use personalization but it only let's me move the fields and not the actual header or the whole section at once. If you know how to do this, that would be great.

![image](https://github.com/hougaard/Simple-Object-Designer/assets/87865315/cca15a8a-44a5-41b3-89ff-8b0da7ce680e)

**Comment by otherjoel** [comment]
Hmm. Weirdly, my own Shipping Payment section _is_ above the Lines section, but I just tried personalizing and I can't move it either. Either it was possible in the past, or perhaps the differences from user to user are attributable to the role centers being used.

**Comment by hougaard** [comment]
The latest version of the Simple Object Designer now has the ability to define sections and handle field ordering.
