### ISSUE TITLE
New Install & Process

### ISSUE THREAD

**Issue by keysimm** [hougaard/Simple-Object-Designer#215]
Hi All,

I'm looking for some general support about the install and applying changes to production. We have a support partner developer but they have no experience of SOD and I'm not confident of going live before I clarify a couple of things. Any advice or pointers to the correct place would be appreciated.

1. I have a sandbox environment to install the trial but previously had this and my developer overwritten this environment so the SOD was deleted. Do I have to have a dedicated sandbox that should never be overwritten? If this is the case, I'll never get to see more recent data - is the usual?
2. If I create an app file (when I pay for the sub) does that file contain all changes/fields for everything I've ever implemented or is a new file created each time so if I created 15 new fields on separate occasions there'd be 15 extensions? (My preference is for 1 file).
3. If I had created an app file and it was implemented in production but then the Sandbox was overwritten (accidentally or otherwise) would I need to start and create all the fields again because any new app files would overwrite production based on the sandbox environment, i.e. the fields would no longer be in the sandbox because SOD was deleted so no changes would be there essentially.
4. Is there a guide on how to install the extensions to production? Do I need any developer support or are these simple installs and they're live?

Any advice would be greatly appreciated.

**Comment by hougaard** [comment]
Great questions!

1. You can always import your app again into any sandbox, that's part of the paid program.
2. Yes, the preference in SOD is to have _one_ app that includes all your changes
3. Same as answer 1, you can always import your app in SOD.
4. Simply take the .app file you generated in a sandbox, go to Extension Management and upload it - it's that simple :)

As soon as you have paid for the app, you'll get an .app file downloaded every time you publish. That's the file you use deployment to prod and to import into SOD again. It's the solution to every one of your questions. But also the central piece we have excluded from the trial version :)

**Comment by keysimm** [comment]
Thank you, Erik. I appreciate the quick response. 

I have been experiencing another error whilst testing but I've opened a specific thread with regards to this.
