### ISSUE TITLE
Issue Upgrading to v22 BC

### ISSUE THREAD

**Issue by DogmatixAU** [hougaard/Simple-Object-Designer#218]
Hi.

I have a client with SOD. The upgrade to v22BC kept failing - with reference to the SOD extension we loaded.

I made a copy of Prod environment to a sandbox called TEST & removed the extension and ran the upgrade - which worked without error. However when I try to reload the extension, it failed, with following error.

Format error in package.
If requesting support, please provide the following details to help troubleshooting:

**Format error in package.**
> Internal session ID: 
> fcfdddb2-8555-45a6-a6e2-73fe860abc37
> 
> Application Insights session ID: 
> cb939ec7-63a4-4c7b-a2d3-35b8b4b65348
> 
> Client activity id: 
> cf7021a9-230e-4f44-bfef-1b5e97527187
> 
> Time stamp on error: 
> 2023-06-20T06:46:48.9985935Z
> 
> AL call stack: 
> "Extension Operation Impl"(CodeUnit 2503).DeployAndUploadExtension line 19 - System Application by Microsoft
> "Upload And Deploy Extension"(Page 2507)."Deploy - OnAction"(Trigger) line 7 - System Application by Microsoft

I also went back to the dev environment (which has SOD application), removed SOD and upgraded to v22BC (sucessfully). Then reinstalled latest version of SOD and reimported my previous app backup and republished. It produces a similar Format error when applying to local environment 

> AL call stack: 
> "Extension Operation Impl"(CodeUnit 2503).DeployAndUploadExtension line 19 - System Application by Microsoft
> "Extension Management"(CodeUnit 2504).UploadExtensionToVersion line 2 - System Application by Microsoft
> "Build Extension Hgd"(CodeUnit 70310250).InstallExtension line 7 - Simple Object Designer by Hougaard
> "Build Extension Hgd"(CodeUnit 70310250).CreateExtensionEx line 554 - Simple Object Designer by Hougaard
> "Object Designer Menu Hgd"(Page 70310263)."ExportExtension - OnAction"(Trigger) line 6 - Simple Object Designer by Hougaard
> 

Do you have any ideas as to what the cause of the issue is? and what to do next? The client needs to upgrade to v22BC asap, but cant atm. I can provide zip export copy of SOD app.

Thanks in advance.

**Comment by hougaard** [comment]
Please send the app file to ***@***.*** - On my way to bed, 
will check it first time tomorrow.

/erik

On 2023-06-19 23:53, Michael Inga wrote:

> Hi.
> 
> I have a client with SOD. The upgrade to v22BC kept failing - with 
> reference to the SOD extension we loaded.
> 
> I made a copy of Prod environment to a sandbox called TEST & removed 
> the extension and ran the upgrade - which worked without error. However 
> when I try to reload the extension, it failed, with following error.
> 
> Format error in package.
> If requesting support, please provide the following details to help 
> troubleshooting:
> 
> Format error in package.
> 
>> Internal session ID:
>> fcfdddb2-8555-45a6-a6e2-73fe860abc37
>> 
>> Application Insights session ID:
>> cb939ec7-63a4-4c7b-a2d3-35b8b4b65348
>> 
>> Client activity id:
>> cf7021a9-230e-4f44-bfef-1b5e97527187
>> 
>> Time stamp on error:
>> 2023-06-20T06:46:48.9985935Z
>> 
>> AL call stack:
>> "Extension Operation Impl"(CodeUnit 2503).DeployAndUploadExtension 
>> line 19 - System Application by Microsoft
>> "Upload And Deploy Extension"(Page 2507)."Deploy - OnAction"(Trigger) 
>> line 7 - System Application by Microsoft
> 
> I also went back to the dev environment (which has SOD application), 
> removed SOD and upgraded to v22BC (sucessfully). Then reinstalled 
> latest version of SOD and reimported my previous app backup and 
> republished. It produces a similar Format error when applying to local 
> environment
> 
>> AL call stack:
>> "Extension Operation Impl"(CodeUnit 2503).DeployAndUploadExtension 
>> line 19 - System Application by Microsoft
>> "Extension Management"(CodeUnit 2504).UploadExtensionToVersion line 2 
>> - System Application by Microsoft
>> "Build Extension Hgd"(CodeUnit 70310250).InstallExtension line 7 - 
>> Simple Object Designer by Hougaard
>> "Build Extension Hgd"(CodeUnit 70310250).CreateExtensionEx line 554 - 
>> Simple Object Designer by Hougaard
>> "Object Designer Menu Hgd"(Page 70310263)."ExportExtension - 
>> OnAction"(Trigger) line 6 - Simple Object Designer by Hougaard
> 
> Do you have any ideas as to what the cause of the issue is? and what to 
> do next? The client needs to upgrade to v22BC asap, but cant atm. I can 
> provide zip export copy of SOD app.
> 
> Thanks in advance.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***> [ { ***@***.***": 
> "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { 
> ***@***.***": "ViewAction", "target": 
> "https://github.com/hougaard/Simple-Object-Designer/issues/218", "url": 
> "https://github.com/hougaard/Simple-Object-Designer/issues/218", 
> "name": "View Issue" }, "description": "View this Issue on GitHub", 
> "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": 
> "https://github.com" } } ]



Links:
------
[1] https://github.com/hougaard/Simple-Object-Designer/issues/218
[2]

**Comment by DogmatixAU** [comment]
Thanks.

Zip file sent to ***@***.***



Michael Inga

ERP Practice Manager

[Smart Phone]   0418 926 687



________________________________

**Comment by DogmatixAU** [comment]
Hi Erik.

I managed to solve the problem. There was an additional SOD field on a report that seems to have been deprecated/replaced in the latest upgrade.

However, there is another related issue.

In the SOD extension, if I go to the Inspect Reports page. and click the option Only Customized Objects, I get this error

If requesting support, please provide the following details to help troubleshooting:




The Report Metadata Hgd does not exist. Identification fields and values: Report No.='5180'

Internal session ID:
572a6c51-d19a-4434-a61d-679851b11d2e

Application Insights session ID:
2169762c-ad34-4953-8dc8-a7574a05f9e5

Client activity id:
74ac41a7-87ce-4f1c-bf28-4ea34c7a2b6d

Time stamp on error:
2023-06-21T23:15:02.9641137Z

AL call stack:
"Existing Reports Hgd"(Page 70310264)."ShowOnlyCustomized - OnAction"(Trigger) line 9 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."Action4 - OnDrillDown"(Trigger) line 2 - Simple Object Designer by Hougaard



5180 is one of the reports that I had to remove the customisation from to get around the earlier problem (there were 3 reports in total).





Michael Inga

ERP Practice Manager

[Smart Phone]   0418 926 687



________________________________

**Comment by hougaard** [comment]
That's not a case that was anticipated, I'll post a new SOD version tonight that will handle it.

**Comment by DogmatixAU** [comment]
Thanks!



Michael Inga

ERP Practice Manager

[Smart Phone]   0418 926 687



________________________________
