### ISSUE TITLE
Field Transfer from Sales Order to Sales Order Archive

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#22]
I would like to have field transfer option available so that I can have fields created on table Sales Order Header table 36 and Line table 37 to Sales Order Archive Header table 5107 and Line table 5108.

Would also like option to add these field to pages Sales Order Archive Header 5159 and Line 5160.

**Comment by hougaard** [comment]
As long as the field numbers are the same, they should be transferred automatically to the archive tables and it's not necessary to specify a field transfer. Use personalization to show the fields no. field.

**Comment by hougaard** [comment]
I have added field transfer options that can be selected for those tables, look for an update in admin center next week.
