### ISSUE TITLE
Create Calculated field from date field

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#220]
I'm taking my first go at creating a calculated field against a date field,

I created the calculated field on purchase order page and made the field type date. 

I then went into the expression editor and as a first test I used the cheat sheet to select the expression "CalcDate('<3D>',Rec."Posting Date")". However I get the below error when I go to test the results.

![image](https://github.com/hougaard/Simple-Object-Designer/assets/87865315/d14219de-efa2-4929-b593-40d73210608f)

Now my actual end goal is to create a calculated date field against the order date field from the purchase order page and add 3 business days (not calendar days).

With that how would that calculation be done and is what I am trying to do even possible?

**Comment by ScottB-Ronco** [comment]
Hello Erik I know you are probably very busy, not sure if you missed this request, but could I get your feedback on this?

**Comment by hougaard** [comment]
I think that's because the test checks against a blank field, ignore the test, and this publishing it anyway.

(I'm working on improving the expression tester)

**Comment by ScottB-Ronco** [comment]
OK I'll create and publish a field in sandbox to see if it works as expected

Now by chance do you know what the expression would be to be 3 business days from current date?

I've been reading different articles about how dates work in business central but its quite confusing :)

**Comment by hougaard** [comment]
Calcdate does not do "business days" :(

**Comment by ScottB-Ronco** [comment]
Is there another method to calculate business days and if so is it supported by SOD's calculated fields?

**Comment by ScottB-Ronco** [comment]
Following up on my last request asking if there is another way to calculate business days.

Also when I tried to create a calculated field using the cheat sheet formula "CalcDate('<3D>',Rec."Posting Date")", if I skip verification and just try to exit the edit expression screen I still get the same error as shown in above screenshot and it will not let me exit the expression editor.

I'm also running latest version of SOD 9.0.0.306.

Also another question I have is does the calculated field option let me take values from different areas? For example one calculated field I want to do is take order date on Purchase Order and from the vendor card add the vendor lead time so it would PO Order Date + Vendor Lead Time eg: Order Date 5/28/2023 + 90D from vendor lead time field on vendor card.

If that doesn't work would I then need to expose and/or transfer the field from vendor card to purchase order so that the field exists there to do the calculation?

**Comment by hougaard** [comment]
1. I'm working on the verification not puking on date fields, ETA very soon!
2. Bringing in values from other places can be done with flowfields, but they have to be visible. I'm trying to come up with a better way of doing that.

**Comment by ScottB-Ronco** [comment]
Following up on this request in regards to getting the verification fixed on date fields, any updates there?

Also per my example of using fields from another area, you stated I could do this with a flowfield, could you elaborate on this a bit more? What type of flowfield would I need to setup and how?

**Comment by hougaard** [comment]
Working on it right now :)

You'll get an option to mark what flowfields need to be calculated.

**Comment by ScottB-Ronco** [comment]
Thanks for the quick response.

I'm still confused about the flowfields, why type of flowfield would I need to create to have the vendor lead time be part of a calculated field on the PO?

I'm also not quite sure I understand what you mean by I'll get an option to mark which flowfield is to be calculated.

**Comment by hougaard** [comment]
You can use flowfields to pull in values from other places, something that might not be available where you are, but there's a reference to it. An example: you have a Customer No. field, but you need a field from the customer card. Then you can use the Customer No. in a FlowField(Subtype Lookup) to pull in the other field.

But Flowfields are calculated "on demand", and including them inside a formula does not constitute "on demand", so I'll have to create a list where you can select what flowfields need to be resolved before doing your calculation.

**Comment by ScottB-Ronco** [comment]
I want to first provide an update that with the latest version of SOD the validation of date calculated fields is now working.

Now based on your last comment I'm not sure I understand what you are saying about creating a flowfield to pull in another field.

Now I also have another question about the calculated fields. When I created one as test it automatically made it read only. Is there anyway to make the field editable? What I am trying to achieve is have a date field auto calculate the first time and populate a value, but still allow the user to override it.

**Comment by hougaard** [comment]
A calculated field cannot be editable, because it's not stored anywhere, so there's no place to put whatever you type in the field. 

As I'm slowly wetting my feet with the technology behind making calculated fields possible (and actually also the mandatory fields). I'm going to add more options like this. Field initialization could be a good candidate.

**Comment by ScottB-Ronco** [comment]
Per a previous question made above on June 29th, I am trying to create a calculated field where I use the order date on Purchase Order and add it with the value from the Lead Time Calculation field that already exists on the PO screen eg: Order Date 5/28/2023 + 90D from lead time calculation field.

The exact expression I put is Rec."Order Date" + Rec."Vendor Lead Time"

However when I tried to verify it, I get the following validation error 

Syntax error: Syntax error: (Line 1): Unsupported record field type (DateFormula)
Syntax error: Syntax error: (Line 1): Type mismatch Integer vs Undefined

**Comment by hougaard** [comment]
try:

calcdate(Rec."Vendor Lead Time",Rec."Order Date")

**Comment by ScottB-Ronco** [comment]
I tried to verify that calculation I get the this error

![image](https://github.com/hougaard/Simple-Object-Designer/assets/87865315/77ccabc8-aeb2-49a9-a6a4-3e969457cf90)

Which the same error I originally got when using the cheat sheet calculation option of CalcDate('<3D>',Rec."Order Date").

You had fixed this in a release 9.0.0.311 so that it would still validate on division by 0 or blank fields. Not sure if this is the same issue.

**Comment by hougaard** [comment]
Ahh.. this is a different issue... this is a blank date formula field.... 

But I think you can just ignore the verify and go for it, try publishing anyway....

**Comment by ScottB-Ronco** [comment]
So I had time to try the formula you provided again today and I skipped the verification.

If I try to exit the calculated field window I get this error and doesn't let me exit. So I can't publish it to see if it works

![image](https://github.com/hougaard/Simple-Object-Designer/assets/87865315/7862a487-c6be-41e7-a9bd-ce394c779977)

**Comment by hougaard** [comment]
Try on the latest version of SOD

**Comment by ScottB-Ronco** [comment]
I am on the latest version, 9.0.0.324. I just upgraded it this morning.

**Comment by hougaard** [comment]
I see the problem.. Stay tuned for an update...

**Comment by hougaard** [comment]
Grab 9.0.0.326, it will allow you to close the page without verifying. (and the underlying I'm gonna fix in the ToolBox (that's actually used behind the scene to do the verification).
(Will take a couple of hours to get to AppSource)

**Comment by ScottB-Ronco** [comment]
OK so I finally had the chance to get to this issue again and I tried to deploy the calculated with with the formula provided of CalcDate(Rec."Vendor Lead Time",Rec."Order Date").

However deployment failed with the following error

Deployment failed. Errors: App ID : 63320191-aaae-4f4c-8291-a041fb2068e9 Message : { Extension compilation failed
PageExtensions/Purchase_Order_PageExt.al(98,32): error AL0132: 'Record "Purchase Header"' does not contain a definition for 'Vendor Lead Time' } - Job Id : e2e86dae-b171-4808-bf7a-b105571179f1

**Comment by hougaard** [comment]
I believe the field is called Rec."Lead Time Calculation" .. not "vendor lead time"

**Comment by ScottB-Ronco** [comment]
DOH!... that makes sense as once I used the correct field name then published, it worked fine without issue.

I'll close this issue now
