### ISSUE TITLE
Change values to an Option Field

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#23]
I created a field with the type set to Option and then clicked on Advanced to show the Option members field to enter the values and then published the field.

When setting the options I forgot to include the option for blank. However if try to go back to change values it doesn't let me because the field has been published. So then I went to delete the field but then it prompted me that I would need to use the "delete extension data" to redeploy.

If I use this option does it delete all data related to all fields I have created in the system so far or only for the field that I am deleting?

Also why does SOD not let you change the values to a field type of option and then redeploy?

**Comment by ScottB-Ronco** [comment]
Erik.

Could I get an answer to this please?

**Comment by hougaard** [comment]
Are you updated to v19 yet?

**Comment by ScottB-Ronco** [comment]
Yes our Sandbox is on v19 and this is where I do my testing with SOD. Our production is not on v19 yet though.

**Comment by hougaard** [comment]
Uncheck "published" for that field, change the option members and publish again....

If the publish fails, then upload the app file manually to extension management with "add" as Schema Sync Mode
![image](https://user-images.githubusercontent.com/3357237/143342806-8f9382e2-f5e6-4ead-8ad2-1a266c76ab3f.png)

**Comment by ScottB-Ronco** [comment]
I can't uncheck published it is greyed out.

**Comment by ScottB-Ronco** [comment]
Also any update on this request.

I made note that I cannot uncheck published as it is greyed out.

**Comment by hougaard** [comment]
Then you must delete the field, re-create it again with the same field number and name.

**Comment by ScottB-Ronco** [comment]
OK when I do that it gives a message along the lines that I must use the the delete extension data.

But since SOD uses one extension for all fields addition/changes then when using that option I would have make sure and export/record all records that have the field data to import back in.

Now can I just delete a field in SOD say ok to the message about delete extension data, then not publish the change, but just do as you said recreate field with same details and publish again? Will this cause any issues?

**Comment by hougaard** [comment]
As long as you recreate the same fieldno/name it will work. (I know this is a "dirty" workaround, but it will work).
