### ISSUE TITLE
Calculated Field Divided By Zero

### ISSUE THREAD

**Issue by Pfc-JoeH** [hougaard/Simple-Object-Designer#230]
Apologies if this is a bit too basic a question but I'm wondering if it is possible to create a calculated field expression that would be something along the lines of: IF(Rec.CustomQtyField <>0, Rec.Price / Rec.CustomQtyField).

**Comment by hougaard** [comment]
Not right now... But it's in the works to have calculated fields survive division by zero and other cases of blank values...

**Comment by Pfc-JoeH** [comment]
Any nonsensical expressioning I might be able to make work like adding back in a certain amount or something?


[7LXCIfJMbkOAAAAAElFTkSuQmCC]
***@***.******@***.***>
888.PFC.9151 x139 TOLL FREE
610.474.0440 x139 OFFICE
610.474.0444 FAX
59 Airport Road · Pottstown, PA 19464
Please consider the environment before printing this email [XxjEeVQYtlzvZGBn4WYott+CSGfIiRbkQpBtIBrkSpBGEABZAHINTA6WvVxUs+H5FG92AoWRLjR1X362AyO7oYchwYwOilEQAMUkMsCb0WEKQV4+fH8BOAxBADkCQHxQGNkqJuAvgtCzAKxwRI4AQoUjAIjET9psgRgaAAAAAElFTkSuQmCC]
[AZIkxAjvEwYRAAAAAElFTkSuQmCC]<https://www.facebook.com/performancefoodcenters>  [x+npPD+LS8flQAAAABJRU5ErkJggg==] <https://www.twitter.com/PFCNutrition>   [i6f0E39T8AUOO8cKFureMAAAAASUVORK5CYII=] <https://www.instagram.com/performancefoodcenters>   [AiPAzrwTPXVFAAAAAElFTkSuQmCC] <https://www.linkedin.com/company/simple-again>
[SKSmCgCAgCAgC5SDgk7Hr1q1TZCGCBCCFHXfcUY0YMaJDjEFMDzITgqkU91Q0Av688847WnMwxRBFTAfkGUFAEBAEBIHsCJi7wpG3m2++udYW0Bq23nrr7JX93xu5CcHVIiSB6WjlypXabARrrVq1Knfn5EVBQBAQBASBjggYkxGawMYbb5xZCwjh+T+Svu1ZBmRuIAAAAABJRU5ErkJggg==]<https://itunes.apple.com/us/app/pfc-mobile/id1398114453?ls=1&mt=8>[D0444YSBFEBxzcJ8JEACJEACJEACiNnZuHHj6urq6rt1ApVVxKyLHu8NEffTq1evET169Pi3srKyE1WV4e9JgARIgARIgASyTaC+vv6N5ubmzbt27XrWJF5Hh1qqokenAkxDAiRAAiRAAiRAAvkgQNGTD8q8BwmQAAmQAAmQQKcToOjpdBOwAiRAAiRAAiRAAvkgQNGTD8q8BwmQAAmQAAmQQKcToOjpdBOwAiRAAiRAAiRAAvkg8P8BQgIAZg0UCWAAAAAASUVORK5CYII=]<https://play.google.com/store/apps/details?id=com.performancefoodcenters.pfcmobile>



From: Erik Hougaard ***@***.***>
Date: Thursday, July 6, 2023 at 5:16 PM
To: hougaard/Simple-Object-Designer ***@***.***>
Cc: Joe Hocker ***@***.***>, Author ***@***.***>
Subject: Re: [hougaard/Simple-Object-Designer] Calculated Field Divided By Zero (Issue #230)

Not right now... But it's in the works to have calculated fields survive division by zero and other cases of blank values...

**Comment by hougaard** [comment]
Well, you can add 0.0000001 to the number before you divide :)

**Comment by hougaard** [comment]
Rec.Price / (Rec.CustomQtyField + 0.000000001)

**Comment by Pfc-JoeH** [comment]
I tried it with just a .1 before and I guess because there wasn’t a leading 0 it got upset. This issue can close for now but if it’s possible to have calculated fields survive divided by zero, that would be awesome!


[7LXCIfJMbkOAAAAAElFTkSuQmCC]
***@***.******@***.***>
888.PFC.9151 x139 TOLL FREE
610.474.0440 x139 OFFICE
610.474.0444 FAX
59 Airport Road · Pottstown, PA 19464
Please consider the environment before printing this email [XxjEeVQYtlzvZGBn4WYott+CSGfIiRbkQpBtIBrkSpBGEABZAHINTA6WvVxUs+H5FG92AoWRLjR1X362AyO7oYchwYwOilEQAMUkMsCb0WEKQV4+fH8BOAxBADkCQHxQGNkqJuAvgtCzAKxwRI4AQoUjAIjET9psgRgaAAAAAElFTkSuQmCC]
[AZIkxAjvEwYRAAAAAElFTkSuQmCC]<https://www.facebook.com/performancefoodcenters>  [x+npPD+LS8flQAAAABJRU5ErkJggg==] <https://www.twitter.com/PFCNutrition>   [i6f0E39T8AUOO8cKFureMAAAAASUVORK5CYII=] <https://www.instagram.com/performancefoodcenters>   [AiPAzrwTPXVFAAAAAElFTkSuQmCC] <https://www.linkedin.com/company/simple-again>
[SKSmCgCAgCAgC5SDgk7Hr1q1TZCGCBCCFHXfcUY0YMaJDjEFMDzITgqkU91Q0Av688847WnMwxRBFTAfkGUFAEBAEBIHsCJi7wpG3m2++udYW0Bq23nrr7JX93xu5CcHVIiSB6WjlypXabARrrVq1Knfn5EVBQBAQBASBjggYkxGawMYbb5xZCwjh+T+Svu1ZBmRuIAAAAABJRU5ErkJggg==]<https://itunes.apple.com/us/app/pfc-mobile/id1398114453?ls=1&mt=8>[D0444YSBFEBxzcJ8JEACJEACJEACiNnZuHHj6urq6rt1ApVVxKyLHu8NEffTq1evET169Pi3srKyE1WV4e9JgARIgARIgASyTaC+vv6N5ubmzbt27XrWJF5Hh1qqokenAkxDAiRAAiRAAiRAAvkgQNGTD8q8BwmQAAmQAAmQQKcToOjpdBOwAiRAAiRAAiRAAvkgQNGTD8q8BwmQAAmQAAmQQKcToOjpdBOwAiRAAiRAAiRAAvkg8P8BQgIAZg0UCWAAAAAASUVORK5CYII=]<https://play.google.com/store/apps/details?id=com.performancefoodcenters.pfcmobile>



From: Erik Hougaard ***@***.***>
Date: Thursday, July 6, 2023 at 5:23 PM
To: hougaard/Simple-Object-Designer ***@***.***>
Cc: Joe Hocker ***@***.***>, Author ***@***.***>
Subject: Re: [hougaard/Simple-Object-Designer] Calculated Field Divided By Zero (Issue #230)

Rec.Price / (Rec.CustomQtyField + 0.000000001)

**Comment by hougaard** [comment]
Yeah, .1 is not a valid number in source code :)
