### ISSUE TITLE
Invalid argument was passed to a list data type method

### ISSUE THREAD

**Issue by Math4118** [hougaard/Simple-Object-Designer#231]
I can't publish with success my extension through the SImple Object Designer. I get this error message: ''Invalid argument was passed to a list data type method''. What's wrong?

**Comment by hougaard** [comment]
Do you get the option of copying detail to the clipboard? (If so, please paste them here)

**Comment by Math4118** [comment]
If requesting support, please provide the following details to help troubleshooting:

An invalid argument was passed to a 'List' data type method.

Internal session ID: 
ade7e9cf-405d-4b07-b92f-41a519dfd8f9

Application Insights session ID: 
41ab8554-3a87-40b5-97af-af4cbfd57d47

Client activity id: 
c288d54a-81b4-40b5-ac9d-f60b84711351

Time stamp on error: 
2023-07-06T23:09:50.0633894Z

AL call stack: 
"Build Feature Code Hgd"(CodeUnit 70310254).ExportTableFields line 267 - Simple Object Designer by Hougaard
"Build Feature Code Hgd"(CodeUnit 70310254).ExportTable line 30 - Simple Object Designer by Hougaard
"Build Extension Hgd"(CodeUnit 70310250).CreateExtensionEx line 261 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."ExportExtension - OnAction"(Trigger) line 6 - Simple Object Designer by Hougaard

**Comment by hougaard** [comment]
I think you have a field without a type on one of your features?

**Comment by Math4118** [comment]
yes you are right, I had one. I fixed it but I still get the same error message. I reload but still doesn't work.

**Comment by Math4118** [comment]
ok, it works now. I deleted the lookup that has been done with the field with no type and remade it... now it works. :) Thank you so much Erik :)
