### ISSUE TITLE
Metadata Hgd does not exist.

### ISSUE THREAD

**Issue by jdbowles** [hougaard/Simple-Object-Designer#238]
Hi Eric,
I updated the SOD application and now I get an error.
Identification fields and values: Table No.='50109'
AL call stack: 
"Existing Tables Hgd"(Page 70310271)."ShowOnlyCustomized - OnAction"(Trigger) line 9 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."Action5 - OnDrillDown"(Trigger) line 2 - Simple Object Designer by Hougaard

I realise it is something that no longer exists somewhere but what is the easiest way to check? I have quite a lot of new fields etc
I ran the publish action prior to downloading the latest version and it worked fine then post the update and the error occurred. The reason I was doing that is that I had an error in another environment so I was running through app by app to see where the issue was.

Regards
James

**Comment by hougaard** [comment]
Let me check...

**Comment by hougaard** [comment]
Yeah, something got removed, I have added a fix for this in the version of SOD that's coming out tomorrow....
