### ISSUE TITLE
Added field transfers get error

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#24]
After updating SOD to 3.0.0.72, I created a date field called PO Entered Date on Sales Order Header and did a transfer of the field to Sales Invoice Header and Sales Header Archive.

When I go to create a Sales Return Order and use the Get posted document option I now get this error
![image](https://user-images.githubusercontent.com/87865315/143897540-7e5bc564-550f-4bb0-9147-da2250718e4a.png)

Not sure what it means because when I created the field on sales header and created the transfers it auto created the fields. When I look at the field in SOD they all have the same data type
![image](https://user-images.githubusercontent.com/87865315/143898051-43a38c1e-9927-4f8e-94af-5e558b777c35.png)

Also if I try to delete the SRO I created I get the following error
![image](https://user-images.githubusercontent.com/87865315/143898243-c3faa0b7-2c94-4410-9f4d-994a9eb38da6.png)

In both errors it also makes reference to the field "ShipTo Min. Freight Amt." which was created a long time ago and I never had an issue with it until now.

Thank you
Scott

**Comment by hougaard** [comment]
Use personalizations to show the "Field No." in the above list, then give either "PO Entered Date" or "ShipTo Min. Freight Amt." a different field number.

**Comment by ScottB-Ronco** [comment]
OK so that means the errors mentioned above are saying that the fields exist in both tables and they both have the same field number correct?

I am not sure that is the problem though because if we see below screenshot many fields exist in different tables and the field number duplicates. if you take PO Entered Date field on it exists on sales header as field # 70002 and on Sales Invoice header & sales header archive as field # 70000 but the ShipTo Min Freight Amt only exists on Sales header. So why would this cause an issue?

![image](https://user-images.githubusercontent.com/87865315/143927119-5509e618-4397-4af7-a7e2-ff9326cec1b8.png)

Also when I used the option to create a field transfer for PO Entered Date SOD auto created field to the tables and assigned the field number. So would this potentially be a bug in SOD as I never had to manually assign a field number before.

**Comment by ScottB-Ronco** [comment]
I also get this error when trying to post a whse shipment. In this case the field Return Reason already has different field number than the ShipTo Min Freight Amt.

![image](https://user-images.githubusercontent.com/87865315/143933601-82e2309d-826d-4cf8-bfe7-e26f91b5296b.png)

**Comment by ScottB-Ronco** [comment]
Any update?

**Comment by hougaard** [comment]
Please email me your .app file.

**Comment by ScottB-Ronco** [comment]
Just sent you email with my .app file.

**Comment by hougaard** [comment]
See email reply

**Comment by ScottB-Ronco** [comment]
With the email you sent I understand what happened and that on a future update of the SOD app you will have this fixed.

With that I will consider the is issue closed

For anyone else who comes across this and is wondering what the solution is, it is to do this:

1. Within SOD when you are on the Edit - Create Fields screen use the personalization option and add the FieldNo field.
2. On the first table you create the new field on take note of the Field number that gets created.
3. When you use the field transfer option and it prompts to create field for you on the secondary table it will auto generate and populate the fieldno field with a new field number.
4. You must change the fieldno number value on the secondary table to ensure it is using the same field number from primary table where field was first created.

Once these steps are done you can publish your extension and not face the problem I had above.
