### ISSUE TITLE
Error when setting Flowfield filter

### ISSUE THREAD

**Issue by mikeswartzentruber** [hougaard/Simple-Object-Designer#242]
When setting the FlowField filter, it gives an error when publishing.

This is the error:
Deployment failed. Errors: App ID : db798535-bdf8-45cc-9d45-63c2dcdf96c2 Message : { Extension compilation failed
TableExtensions/Prod__Order_Line_TableExt.al(11,79): error AL0186: Reference '"Next Operation No. RSWSG"' in application object 'Prod. Order Line' does not exist }

here is a snip of the value in that table:

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/3344659a-ab6c-467e-9cb3-686f6a97465e)

What am i doing wrong?

**Comment by mikeswartzentruber** [comment]
Trying to work around this I also tried to use the "Place existing fields on pages" for this same field and get a different error now... This field was created by another developer, is permissions the issue?

this is the erro:

Deployment failed. Errors: App ID : db798535-bdf8-45cc-9d45-63c2dcdf96c2 Message : { Extension compilation failed
PageExtensions/Prod__Order_Line_List_PageExt.al(12,55): error AL0161: '"Next Operation No. RSWSG"' is inaccessible due to its protection level }

**Comment by hougaard** [comment]
Sounds like the developer of the other app has configured it to be non-extensible

**Comment by mikeswartzentruber** [comment]
Thank you, i worked with the other developer and after they made this field accessible it worked!

**Comment by mikeswartzentruber** [comment]
Thanks again.
