### ISSUE TITLE
Cannot remove Number Series fields from Setup feature even after deleting/renaming associated feature

### ISSUE THREAD

**Issue by otherjoel** [hougaard/Simple-Object-Designer#245]
Due to the problem encountered in #244 I had to rename my document feature to use a shorter identifier. This caused enough problems that I ended up deleting the feature in order to start from scratch again.

However, this left some “number series” fields on the Setup feature card for fields/features which no longer exist.

How can I remove these fields from the Setup feature card, or remove the Setup feature card altogether?

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/df85123f-e248-4be1-b284-b8f0b55abc89)

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/e33cf589-56cc-48d6-ab51-333c7fe29104)

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/692f5fdd-779d-49c0-b438-ac8df0289c17)

**Comment by otherjoel** [comment]
Bump: is there any quick hack I can do to get these number series setup fields removed?

**Comment by hougaard** [comment]
Dunno if this is quick, but this is a way:

1. Update to the latest version of SOD (Very important)
2. Export App (from setup page)
3. Open the exported JSON file
4. Locate table 70310274
5. Delete the two records from table 70310274
6. Save the JSON
7. Import App (from the setup app)
