### ISSUE TITLE
Read-Only field in table 952

### ISSUE THREAD

**Issue by teganZT** [hougaard/Simple-Object-Designer#246]
Hi Erik,

I am trying to build a connector into Dynamics Time Sheets that will automatically add time to a user's time sheets. Using table 952 I would like to be able to create and update lines with the API. I was surprised to get an error message saying the Quantity field is read-only.

Is there a way you know of to get around this limitation? If it is not possible with SOD is a Dynamics developer able to adjust read-only rules, or is it completely locked down?

Thank you,

Tom

**Comment by hougaard** [comment]
Yeah, it's a read-only field:
<img width="245" alt="image" src="https://github.com/hougaard/Simple-Object-Designer/assets/3357237/3a7a1304-695e-4a2d-b811-a98e989a8b6c">

Putting unvalidated data into field is far from "Simple" and beyond the scope of the SOD.
