### ISSUE TITLE
Cannot edit number series configuration in new feature setup

### ISSUE THREAD

**Issue by otherjoel** [hougaard/Simple-Object-Designer#247]
I recreated the feature I deleted in #245. This new feature has the “Use a number series for primary key value” option checked, and the Setup feature card now shows a field for setting the number series to use. 

However, the field is read only; I cannot edit it to configure the number series, even when in edit mode on the setup page. (1st screenshot below).

* I have not enabled the “Read only” option on the field for the setup card (2nd screenshot below).
* I am running as SUPER user, and an “Effective Permissions” check confirms I have full access to the table and table data for that page.
* No errors encountered during verify or publish.

Using SOD 9.0.0.314 / 22.2.56969.57282

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/bc8e3749-c4a6-4473-88b3-6c591be9a451)

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/3185af5f-6a89-42ca-a806-a040633396f3)

**Comment by hougaard** [comment]
Click the "+" on the Lotus Setup page to create a new setup record.

**Comment by otherjoel** [comment]
Oof. That was it, thanks.
