### ISSUE TITLE
Generated table captions on new features prevent distinguishing tables in Jet reports

### ISSUE THREAD

**Issue by otherjoel** [hougaard/Simple-Object-Designer#249]
In my SOD app, I have a feature whose table caption is set to “Commission Payment Register”. This feature has both header and lines, as well as a posted variant, so of course the app is actually introducing four tables.

I also have “Exposed as API” enabled everywhere in this feature.

When I need to access these tables in Excel via Jet Reports, instead of offering me access to the four distinct tables, it shows the same one four times (screenshot below). No matter which of the four I select, it _only_ provides fields/records from one of the tables (the non-posted Header table for the feature).

I believe this is because SOD sets the table caption for all four of the tables to the same exact string (second screenshot). Since Jet formulas specify the table using the table caption, this means the Jet formulas cannot distinguish the other three tables.

It seems like it would be straightforward to have SOD use the “Prefix for posted documents” and “Name for Lines Section” fields to generate distinct captions for each of the tables it adds for a feature.

(I am filing a separate ticket with Jet to help them see this pitfall of the approach they are using. I am not holding my breath for them to fix it, however.)

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/00b9357c-c342-4301-86b9-2fea667c2ae4)

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/e7ca578a-4cc9-4298-b213-fcd4bf4f67d0)

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/63fb1ada-06be-4507-8d5e-2d07f82b48c2)

**Comment by hougaard** [comment]
Fixed in version 9.0.0.317
