### ISSUE TITLE
Added table API field not showing in Power BI

### ISSUE THREAD

**Issue by bhagaamt** [hougaard/Simple-Object-Designer#252]
I added description to the item table API and refreshed symbols and cleared cache and published in simple object designer. The description is not showing up in the web source item in power bi. Can you recommend some things to try to get the description to show up in power bi? Thanks!

**Comment by hougaard** [comment]
Where did you add the field?

**Comment by bhagaamt** [comment]
Thanks for your prompt response I figured out how to add it in.
