### ISSUE TITLE
Field Transfer Request - Purchase Line to G/L Entry

### ISSUE THREAD

**Issue by Brad403** [hougaard/Simple-Object-Designer#253]
Hello,

I some custom fields added to the Purchase Line (table 39), and was wondering if it's possible to have those fields transfer to G/L Entry (table 17)? 

I do those fields transferring to the Item Journal Line (table 81) and then to the Item Ledger Entry (table 32), but don't see an option to have it go to the G/L Entry.

I have some users that when creating PO use the "Type" G/L Account and then they fill in those custom fields I have on the Purchase Lines, but they don't transfer to the General Ledger Entries.

Thanks,

Brad

**Comment by hougaard** [comment]
Not possible, there's not a 1-1 relationship between document lines and GL entries. They get buffered in the posting routine.

**Comment by Brad403** [comment]
Okay. Thanks for explanation on why it won't work, Erik.
