### ISSUE TITLE
Publishing error (Value cannot be null Parameter 'adminServiceFacade')

### ISSUE THREAD

**Issue by Sunny1Bunny** [hougaard/Simple-Object-Designer#254]
Why am i getting this error when publishing SOD changes. Happens regardless what company I am working in. 
![Screenshot 2023-07-31 142555](https://github.com/hougaard/Simple-Object-Designer/assets/141065202/79a994e7-7050-4a63-8c3b-15f40c0b54d2)

**Comment by hougaard** [comment]
Bug at Microsoft, I'm already talking with them about it (you're not alone), they're working on a fix, keep trying periodically.

**Comment by mikeswartzentruber** [comment]
Any update on this error?

**Comment by hougaard** [comment]
They're working on it, that's all they told me..

**Comment by SBalslev** [comment]
We're on it :) Issue is being resolved now - let me know if it's fixed.

**Comment by GrooveRings** [comment]
Worked for me! Thanks for the update!

**Comment by mikeswartzentruber** [comment]
Working for me! Thanks for the quick response!

**Comment by hougaard** [comment]
Thanks for your help @SBalslev, closing this ticket.

**Comment by Sunny1Bunny** [comment]
Thanks Eric!!

________________________________

**Comment by Sunny1Bunny** [comment]
It's working, thank you!
________________________________
