### ISSUE TITLE
Error when using pipe in CONST flowfield filter

### ISSUE THREAD

**Issue by mikeswartzentruber** [hougaard/Simple-Object-Designer#255]
I get the below error when trying to use multiple values (with a pipe) within the CONST in a flowfield filter.

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/074d275e-9946-4825-a34d-7c6e3779fb33)

How should i write the CONST so it works?

**Comment by mikeswartzentruber** [comment]
So i figured out this works if i use a FILTER instead of a CONST, but using the filter i just get an error if i add a "blank" filter betwen the pipes. Maybe a bug in SOD?

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/f19f6c47-c2da-4f52-9695-665529e263a4)


![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/c3ca181d-a7d6-440c-b7bf-305d10e7e0ee)

**Comment by hougaard** [comment]
What version of SOD are you using?

**Comment by mikeswartzentruber** [comment]
Just updated yesterday, version 9.0.0.317

Mike Swartzentruber​​​​
Financial Controller
330.516.1152
16875 Jericho Rd. Dalton, Ohio ***@***.***,-81.6876485,17z/data=!3m1!4b1!4m6!3m5!1s0x88372353bace04e5:0x7080b456232a38f4!8m2!3d40.733122!4d-81.6876485!16s%2Fg%2F11bw4ncf8n>
Flextur.com<http://www.flextur.com/>

**Comment by hougaard** [comment]
This works for me:
<img width="622" alt="image" src="https://github.com/hougaard/Simple-Object-Designer/assets/3357237/0ce0f7e6-3590-4bf8-8e86-e754409c069a">

When are you getting the error, what do you click?

**Comment by mikeswartzentruber** [comment]
That works for me as well, what doesn’t work is Planned|’’|Finished (adding the quotations between the pipes)

Mike Swartzentruber​​​​
Financial Controller
330.516.1152
16875 Jericho Rd. Dalton, Ohio ***@***.***,-81.6876485,17z/data=!3m1!4b1!4m6!3m5!1s0x88372353bace04e5:0x7080b456232a38f4!8m2!3d40.733122!4d-81.6876485!16s%2Fg%2F11bw4ncf8n>
Flextur.com<http://www.flextur.com/>

**Comment by hougaard** [comment]
If you want to include the "blank" option, that's **" "** (a space between two double quotes).

**Comment by mikeswartzentruber** [comment]
Get this error message.

***@***.***



***@***.***
Mike Swartzentruber​​​​
Financial Controller
330.516.1152
16875 Jericho Rd. Dalton, Ohio ***@***.***,-81.6876485,17z/data=!3m1!4b1!4m6!3m5!1s0x88372353bace04e5:0x7080b456232a38f4!8m2!3d40.733122!4d-81.6876485!16s%2Fg%2F11bw4ncf8n>
Flextur.com<http://www.flextur.com/>

**Comment by hougaard** [comment]
Sorry, can't see the images when you just reply to the email, use the github link and post via the web interface instead.

**Comment by mikeswartzentruber** [comment]
you bet, 

here is the image.

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/28f62a0c-4554-4f6f-b6ee-1574f64386c9)

**Comment by mikeswartzentruber** [comment]
This was Planned|" "|In Progress

**Comment by hougaard** [comment]
I see the problem... Quick hack: try <>Finished

**Comment by mikeswartzentruber** [comment]
good try! :) 

Doesn't work, returns a blank filter.

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/e45c8ac0-66fc-40c3-98d6-ef87cd55da69)

**Comment by hougaard** [comment]
Really blank? Send the .app file to support@hougaard.com - That should never happen.

**Comment by mikeswartzentruber** [comment]
it is really blank, thanks for your help. I'll send it, any idea on the issue on the |" "| error?

**Comment by mikeswartzentruber** [comment]
Solve for this was using a filter of <>Finished!
