### ISSUE TITLE
Flow Field Filter

### ISSUE THREAD

**Issue by AALEngTech** [hougaard/Simple-Object-Designer#258]
Hi, Is it possible to have the "count" flow field filter use two boolean const of true.

ie. The two fields are "Quality Issue" & "Delivery Issue" which are marked on the purchase header. I use the flow field to count how many purchase orders have issues and display this on the vendor card.

It works fine to count them interdependently but if i try sum the values the records where there were both issues are counted twice.

Many thanks Lee

**Comment by hougaard** [comment]
Sure, you just add two const lines in the filter section on the flowfield.

**Comment by AALEngTech** [comment]
I’ll try add that again, I maybe had something wrong the first time so I assumed it would require both const lines to be true. In records where either is true or both I want it to show them.

Out of interest, how would you them make it be both need to be true?

On 8 Aug 2023, at 00:33, Erik Hougaard ***@***.***> wrote:

﻿

Sure, you just add two const lines in the filter section on the flowfield.

**Comment by hougaard** [comment]
You cannot create an "or" condition, that's not supported by BC.
