### ISSUE TITLE
API tables not found

### ISSUE THREAD

**Issue by bhagaamt** [hougaard/Simple-Object-Designer#263]
I am trying to refresh the API data through Power BI and I keep getting the following error message:

Web.Contents failed to get contents from 'https://api.businesscentral.dynamics.com/v2.0/c2f0cc1e-c9d5-4b6c-8edd-f26517f13156/Sandbox_7_17_23/api/hougaard/SOD/v2.0/companies(55bd166c-6d27-ee11-bdf5-6045bd8286ba)/customers' (404): Not Found

Any help would be greatly appreciated. Thanks!

**Comment by hougaard** [comment]
Are you using the URL direct or via the Business Central Connector in Power BI?

**Comment by bhagaamt** [comment]
I copied the URL from the simple object designer and pasted it into a web source in power bi.

**Comment by hougaard** [comment]
Have you published your app from SOD?
(I recommend using the Connector rather that using the direct URL).

**Comment by bhagaamt** [comment]
The app had been published. I wasn’t familiar with using the Connector. I used that and the data is coming through now. Thanks for your help!

**Comment by bhagaamt** [comment]
Used connector. Problem solved.
