### ISSUE TITLE
Limited field transfers?

### ISSUE THREAD

**Issue by Oderick99** [hougaard/Simple-Object-Designer#266]
Hi

I am still on the free trial at the moment as our go live to BC is not for a few more months and we are trying to learn as much as we can, Simple Object Designer looks like an invaluable tool but I am having some issues transferring fields from table 36 (sales header) to 5766 (warehouse activity header). As soon as I get to the third field I get the following error. I have tried various fields, and deleting existing transfers and starting over but I always hit this limit. Is this a limit in the trial version only?

Thank you

Rod

The record in table New Fields already exists. Identification fields and values: Table No='36',FieldNo='50503'

Internal session ID: 
5fbedb43-a8d1-4d62-9e66-59b3521cacaa

Application Insights session ID: 
df876003-0c9a-4cc4-9bd4-47a3235b3645

Client activity id: 
89cf3264-605a-4ec9-a33f-17278713c70b

Time stamp on error: 
2023-08-17T13:43:26.1234794Z

AL call stack: 
"Existing Fields Hgd"(Page 70310251)."TransfersCtl - OnDrillDown"(Trigger) line 8 - Simple Object Designer by Hougaard

**Comment by hougaard** [comment]
This is not a "trial version issue", please show me a screenshot of your new fields?

**Comment by Oderick99** [comment]
Hi Eric

Thank you for your quick response.

New fields shown below, error when trying to transfer an existing field shown below that. We have moved on to field number 50504 today, one more than yesterday 😊

I am transferring fields from the sales header to the warehouse activity header to allow me to add these fields to the picking note report.

***@***.***

***@***.***

Kind regards​​​​
Rod Manning
|
Operations Manager

Celebration Packaging Limited, Stanley Street, Burton on Trent, DE14 1DY

**Comment by hougaard** [comment]
Sorry, screenshots doesn't come over when you just reply to the email, use the githib page instead please :)

**Comment by Oderick99** [comment]
Screen shots here...


![NewFields](https://github.com/hougaard/Simple-Object-Designer/assets/74183371/9a675323-9782-49d3-886f-42c4c7a809fc)

![FieldTransferError](https://github.com/hougaard/Simple-Object-Designer/assets/74183371/02670e38-9ff4-488f-bbf7-730c59223aac)

**Comment by hougaard** [comment]
Found it.... Stay tuned for an update!

**Comment by hougaard** [comment]
Try the newest version of SOD.

**Comment by Oderick99** [comment]
I have updated to the latest version and seems to be working OK now. Thank you Erik.
