### ISSUE TITLE
New Business Logic API feature request

### ISSUE THREAD

**Issue by RGI100** [hougaard/Simple-Object-Designer#271]
In the Business Logic API there is a code unit to release a sales order document, would we be able to get one to reopen a sales order document.

Our use case is that we want to be able to update an order line quantity but cannot do this is the order is Released.

**Comment by GrooveRings** [comment]
That is available. You just have to toggle advanced methods.

<img width="1068" alt="image" src="https://github.com/hougaard/Simple-Object-Designer/assets/82909149/61265ac5-0327-4da0-ab91-84e7e8daec28">

**Comment by hougaard** [comment]
Awesome answer @GrooveRings, and correct, it's there in codeunit 414, but you gotta venture into the advanced methods :)

**Comment by erlorenz** [comment]
Is there a video on how to use these? I'm trying to do the release sales order but can't find an example.

**Comment by RGI100** [comment]
Hi Erik,

Thank you for looking into this.

If an order is in a released status, you can go in and reopen it. In the order screen, click on release and then choose reopen.

I have tried updating the status directly using Microsoft Flow but Business Central does not allow this.

***@***.***

Please let me if this clarifies it or if you need anything else.

Regards

Lindsay Smith
Director of Information Systems

[Logo  Description automatically generated]
TEAMWORK~OWN IT~POSITIVITY
[Marker with solid ***@***.***,-122.0125659,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5484476c166f84c7:0x180398ab30dc54e9!2m2!1d-122.0128322!2d49.1177372>43756 South Sumas, Chilliwack, B.C. V2R 4L6
[Receiver with solid fill]778-704-0734 Ext. 109
[Smart Phone with solid fill]778-808-7006
[Telephone with solid fill](877) 866-8100
[Cursor with solid fill]<http://www.rainbow.ca/>www.rainbow.ca<http://www.rainbow.ca/>
***@***.******@***.***<https://www.instagram.com/rainbowgreenhouses/> ***@***.*** <https://www.linkedin.com/company/rainbow-greenhouses/mycompany/>  ***@***.*** <https://www.youtube.com/channel/UC3WQpUA2p-Ghl5drqR7X4AQ>

**Comment by RGI100** [comment]
> That is available. You just have to toggle advanced methods.
> 
> <img alt="image" width="1068" src="https://user-images.githubusercontent.com/82909149/263157346-61265ac5-0327-4da0-ab91-84e7e8daec28.png">

Thank you @GrooveRings , I will give this a try today.
