### ISSUE TITLE
Multiple Conditions on Mandatory fields

### ISSUE THREAD

**Issue by User1866f6d5** [hougaard/Simple-Object-Designer#278]
Is there documentation on how the condition levels work for mandatory fields on actions?

**Comment by hougaard** [comment]
Check this: https://youtu.be/Lfk2XAEPLSo

What do you want to accomplish?

**Comment by User1866f6d5** [comment]
This is great, let me get in and try it out. I think it will work

Here is the basic logic I am trying to specify

if  Prod. Order No is not blank 
and Qty To Receive + Quantity Received = Quantity
and Finished is “No”

then
Do not allow any posting actions and show an error

**Comment by User1866f6d5** [comment]
This works perfect, thanks Erik!
One more on this project, is it possible to specify a line property in the error message, such as the Item No.? the "%1" will work if not. 
Thanks again.

**Comment by hougaard** [comment]
Not possible :(

**Comment by User1866f6d5** [comment]
Thanks for verifying
