### ISSUE TITLE
Your Business Central environment failed to update

### ISSUE THREAD

**Issue by tstrop** [hougaard/Simple-Object-Designer#28]
I created and published a couple purchase order line item fields and then realized they belonged in the header and I apparently deleted them 
**Your Business Central environment failed to update**

NST Tenant State: OperationalWithSyncPending
Message: 
Per-tenant extension 'My Customizations' version 1.0.0.18 by '#######Training-New' failed to synchronize the database schema.
TableExtension SODPurchase_Line :: The table 'Purchase Line' cannot be located. Removing tables is not allowed unless they are temporary or are being moved by migration to another app.

NST Tenant Detailed State: The extension 'My Customizations by ########Training-New 1.0.0.18' has a newer version than the current schema version '1.0.0.11'. For OnPrem users, run Sync-NavApp to update the schema. For SaaS users, please contact your Microsoft Partner

Deployment failed. Errors: App ID : ########-####-####-####-############ Message : { Could not upgrade the NAV extension 'My Customizations by ##########Training-New 1.0.0.12' due to the following error: 'TableExtension SODPurchase_Line :: The field 'Multiplier' cannot be located. Removing fields is not allowed.'. }

**Comment by hougaard** [comment]
In that case, you must take the downloaded .app file, go to **Extension Management** and choose **Upload Extension** and set **Force** to allow deletions of fields. (This is not allowed by the automatically publish/deployment process, only the manual one.

**Comment by tstrop** [comment]
Gave it a shot and that too failed.

**Comment by hougaard** [comment]
With what error?

**Comment by tstrop** [comment]
Same as above.
Deployment failed. Errors: App ID : ae5bc78e-a4bf-4ee7-85a5-d33004ccfcd8 Message : { Could not upgrade the NAV extension 'My Customizations by AirProductsTraining-New 1.0.0.19' due to the following error: 'TableExtension SODPurchase_Line :: The table 'Purchase Line' cannot be located. Removing tables is not allowed unless they are temporary or are being moved by migration to another app.'. } - Job Id : 9c9f5b8a-94c3-421d-87f8-c5aec1f5e8a6
![Edit Customize Table Purchase Line](https://user-images.githubusercontent.com/15703800/149657408-327294e7-eac5-48e8-972d-1fd5827ba572.png)
![Edit Customize Table Purchase Header](https://user-images.githubusercontent.com/15703800/149657409-3dd234f4-b5d4-4911-a43f-b189c49033f6.png)
![View Tables](https://user-images.githubusercontent.com/15703800/149657411-60b86fb5-bf8a-4caf-9805-5793c9517d39.png)

**Comment by hougaard** [comment]
Try:

1. Click "Remove Customization" on purchase
2. Hit publish, but answer "No", so you're just downloading the .app
3. Go to Extension Mangement and chose "Upload Extension"
4. Set "Schema Sync Mode" to "Force"
![image](https://user-images.githubusercontent.com/3357237/149669133-bc829ba1-48ab-4003-8fc0-0e9a51afe959.png)
5. Deploy

If this also fail, please send the .app file to support@hougaard.com

**Comment by tstrop** [comment]
Outstanding! That cleared the Purchase Line customization ghost and the two fields now appear in the Purchase Order Header as I was trying to accomplish. Loving the Simple Object Designer.

**Comment by hougaard** [comment]
Good to hear!
