### ISSUE TITLE
Deployment Failure

### ISSUE THREAD

**Issue by MrPooks** [hougaard/Simple-Object-Designer#285]
Receiving the below deployment failure.  I was able to deploy in sandbox, not production.  Changed the sandbox new filed description and deployed again and received the same message.  A tad hard for me to troubleshoot.

![2023-09-08_10-47-22](https://github.com/hougaard/Simple-Object-Designer/assets/107048381/7aaee219-ce85-4fd6-9498-1f0de9b6ae52)

**Comment by hougaard** [comment]
Looks weird, please send your .app file to support@hougaard.com so I can what's going on..

**Comment by MrPooks** [comment]
Sent.

**Comment by hougaard** [comment]
Fixed in the latest verison of SOD.
