### ISSUE TITLE
TableFilter on Roadmap?

### ISSUE THREAD

**Issue by User1866f6d5** [hougaard/Simple-Object-Designer#286]
Will the field type tablefilter be developed in the future?

![Screenshot 2023-09-11 112817](https://github.com/hougaard/Simple-Object-Designer/assets/141262208/7e3f6ad0-57af-45b7-8eaf-06e725e50062)

**Comment by hougaard** [comment]
Why would you want to use that field type?

**Comment by hougaard** [comment]
"TableFilter" is actually an internal type, you can filter on all fields.

**Comment by User1866f6d5** [comment]
Ok thanks, I don't think it's what I was thinking..
