### ISSUE TITLE
Mandatory field on action not working

### ISSUE THREAD

**Issue by User1866f6d5** [hougaard/Simple-Object-Designer#287]
I have an "exist" flow field (SkuDescVerify) on the sales line that checks if the description exists on a different page, then returns yes or no. Works perfect. 
Then created a mandatory field that should verify if the flow field value is Yes or No. 
![mandatory](https://github.com/hougaard/Simple-Object-Designer/assets/141262208/6a8fd522-0ff1-4cfd-9caa-1303f56d33b7)

But it shows my error even if the Flow field value is Yes...
![image](https://github.com/hougaard/Simple-Object-Designer/assets/141262208/1810ae66-c588-4de2-b7b0-621315dde1e5)

**Comment by hougaard** [comment]
Are you on the trial version?

**Comment by User1866f6d5** [comment]
I am not..

![image](https://github.com/hougaard/Simple-Object-Designer/assets/141262208/891c8ca7-c19d-48ed-9b8b-1842c78c81c7)

**Comment by hougaard** [comment]
Then please email the generated .app file to support@hougaard.com and I'll take a look...

**Comment by User1866f6d5** [comment]
Sure will do
