### ISSUE TITLE
Failed package validation

### ISSUE THREAD

**Issue by Pwouterse** [hougaard/Simple-Object-Designer#288]
Hi Eric,

I get the following error after deploying. Hope you can help.
![image](https://github.com/hougaard/Simple-Object-Designer/assets/130642423/69bbd06f-169c-4886-94a8-ba4884fb7d54)

**Comment by hougaard** [comment]
You are using fields "Id" and "Cross-Reference No." in two different API pages, those fields are obsolete and have been removed. Removed them from your APIs and it will deploy again.
