### ISSUE TITLE
Failed deploy when new feature.

### ISSUE THREAD

**Issue by sjmoelgaard** [hougaard/Simple-Object-Designer#289]
Hi Eric, 

I have tried to make a new Data Tabel (function) and get this error, can you see why?

Deployment failed. Errors: App ID : 821d2269-262d-43e1-bf1e-49f71a986638 Message : { Extension compilation failed
Features/NetsetManuMapping/NetsetManuMapping.Table.al(20,29): error AL0581: The length for the type 'Code' must be positive }

**Comment by hougaard** [comment]
Sounds like you have a field of type Code that's missing a size/length?
