### ISSUE TITLE
New custom field is not available on Power Automae

### ISSUE THREAD

**Issue by wellylee** [hougaard/Simple-Object-Designer#29]
I am trying the simple object designer to add a new date field on Sales Order header table (36). I am using Power Automate to automate sales order creation process but I am unable to find the new field from Power Automate workflow editor. Is there a step/setting I missed?

**Comment by hougaard** [comment]
Then you have to create a new API exposed because even if you add a field, that field is not added to the endpoint. You can use the Object Designer to expose a new version of the Sales Header table that you can when catch from a custom connector in power automate.

**Comment by wellylee** [comment]
ok -- thanks for the quick response
