### ISSUE TITLE
Comparing fields with a flowfield

### ISSUE THREAD

**Issue by mikeswartzentruber** [hougaard/Simple-Object-Designer#291]
How do we compare fields in a flowfield? Trying to return YES if one field is equal or larger than another field.

Here is what i have.

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/69dcc775-e49f-4d96-80f2-5b7bd7e2af42)

**Comment by hougaard** [comment]
What type is field 50733?

**Comment by hougaard** [comment]
But no, you cannot use another field in a flowfield that way. Only constants are allowed in a "filter"

**Comment by mikeswartzentruber** [comment]
Thanks Erik,

Field 50733 is a Flowfield returning a sum of field 83 of table 5406. (Decimal)

Any roadmap to bring a functionality like this in the future?

**Comment by hougaard** [comment]
FlowFields inside flowfields will never work. This is a Business Central limitation, nothing I can do about that :)

**Comment by hougaard** [comment]
But you might want to look into calculated fields instead...

**Comment by mikeswartzentruber** [comment]
Got it, i did create a calculated field with this, but i can't filter that field in any way.

What I'm using this for is on a list I want to filter out all lines that have flowfield field #1 greater than flowfield field #2. 
is there another approach to do this? If i could use a calculated field inside a flowfield would work as well, but i can't....

Thanks for your support!
