### ISSUE TITLE
FlowField of a SOD Table doesn't show a lookup table

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#293]
When I create a FlowField table that looks information from another table created in SOD, there isn't a table to select:

![image](https://github.com/hougaard/Simple-Object-Designer/assets/99739571/a8c671bb-371c-40f4-9121-0441e639ff05)

This doesn't happen in tables that are BC tables or created by our partner.

Thanks

**Comment by hougaard** [comment]
Fied in version 9.0.0.344
