### ISSUE TITLE
Problems refreshing symbols.

### ISSUE THREAD

**Issue by Joseph-Candava** [hougaard/Simple-Object-Designer#30]
On the Access to Source Code - Authentication popup, I would normally click the https://microsoft.com/devicelogin and enter the code supplied for me to authenticate and refresh my symbols before performing a deployment.

After signing in, I am stuck at:

"Working on it...

Extracting
Base Application"

then after a long while of stalling on this, it goes into a "Something went wrong." screen.

An error has occurred
Date and time: Sun, 23 Jan 2022 23:07:04 GMT
Azure AD tenant: 885e251c-7ab9-4619-8449-fc7cf725f022
Environment: Production
Operation: 13fa5ecff2aa4fbca21d3b8bf368ef4a

Is there something that I can do about this so I can be able to use your extension?
I am running version 9.2.21123.00167

**Comment by hougaard** [comment]
That's strange, it usually takes a while (10-20 minutes). This is not something we have seen from anywhere else. I suggest trying again, and be patient.

**Comment by Joseph-Candava** [comment]
After giving it an hour and a half of waiting, retrying yielded me to this error message.

Something went wrong.
An error has occurred
Date and time: Mon, 24 Jan 2022 00:38:49 GMT
Azure AD tenant: 885e251c-7ab9-4619-8449-fc7cf725f022
Environment: Production
Operation: d94017f0d3d94288bffaa6dfca37a691

**Comment by hougaard** [comment]
That's waay to long, something is wrong. What was the content in the dialog when progress stopped?

**Comment by Joseph-Candava** [comment]
Working on it...

Extracting
Base Application

**Comment by hougaard** [comment]
It should go:
downloading->extracting->Reading
for each app.

Base application is the big one, but should complete in under 17 minutes. I have just tried running it here and it worked fine.

Do you have telemetry activated, you might be able to locate an error code/messge explaining what goes on?

Please also try from a sandbox instead.

**Comment by Joseph-Candava** [comment]
I'm not sure how to toggle on telemetry. How do I go about enabling this?

**Comment by hougaard** [comment]
In the admin center, see this <https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/telemetry-enable-application-insights>
