### ISSUE TITLE
Field Transfer Not Working

### ISSUE THREAD

**Issue by User1866f6d5** [hougaard/Simple-Object-Designer#302]
I created a basic text field (InvDisDesc) on the sales header (tlb. 36) also on Sales Invoice Header (tbl. 112). Then did a field transfer from sales header to sales invoice header. But if I post a sales order to a posted sales invoice the information in the text field doesn't transfer

![image](https://github.com/hougaard/Simple-Object-Designer/assets/141262208/3c392e05-9e03-4d5e-bb9f-cf2a03091bf7)

**Comment by hougaard** [comment]
Is your SOD up to the latest version?

**Comment by User1866f6d5** [comment]
Updated yesterday. My symbols weren't UTD, I just updated & republished but same thing..
![image](https://github.com/hougaard/Simple-Object-Designer/assets/141262208/7fed7c5b-95a8-4189-a757-a9790041d0d1)

**Comment by hougaard** [comment]
Send your app file to support@hougaard.com and I'll take a look...

**Comment by hougaard** [comment]
Solved in SOD 9.0.0.354

**Comment by User1866f6d5** [comment]
Didn’t get a chance to test till now but it works. Thanks for fixing again!

***@***.***
Nathan Wengerd​​​​
IT Administrator
330.857.6341
16875 Jericho Rd. Dalton, Ohio ***@***.***,-81.6876485,17z/data=!3m1!4b1!4m6!3m5!1s0x88372353bace04e5:0x7080b456232a38f4!8m2!3d40.733122!4d-81.6876485!16s%2Fg%2F11bw4ncf8n>
Flextur.com<http://www.flextur.com/>
