### ISSUE TITLE
Error using another customization’s field in criteria for mandatory actions

### ISSUE THREAD

**Issue by otherjoel** [hougaard/Simple-Object-Designer#303]
Trying to set up a mandatory action that is applicable if the `QCApprove` field on the sales header is "false":

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/bfea067b-da27-4808-97b0-1afa7def9edc)

When I deploy to the same environment, I see this error:

![image](https://github.com/hougaard/Simple-Object-Designer/assets/1553115/76d5648c-8372-41f5-b756-b698bdfcde88)

The field does exist, but it was added via another customization created by another developer. Is this a limitation of SOD or should this still be able to work?

**Comment by hougaard** [comment]
I think I know what's going on. Could you try add something else that uses fields/objects from that 3rd party app? And see if the inclusion of anything from that app would make the mandatory field deploy?

**Comment by otherjoel** [comment]
Something else, specifically in the area of mandatory actions? Or should it be in some other area? (I'm drawing a blank here)

**Comment by hougaard** [comment]
Not mandatory, put a field on a page from that app or something like that

**Comment by otherjoel** [comment]
I added the field to the Sales Order Statistics page (it is already on the sales order) and received the same error, except now for the Sales Order Statistics page: 

> Deployment failed. Errors: App ID : ab8e6875-5d1e-42cb-b326-da92f749c926 Message : { Extension compilation failed
PageExtensions/Sales_Order_Statistics_PageExt.al(7,40): error AL0132: 'Record "Sales Header"' does not contain a definition for 'QCApprove' }

**Comment by hougaard** [comment]
Hmm... Can you please use the "Refesh Symbols" (answer Yes to clearing the cache), it seems that this other extension is eluding  symbol detection (unless you have ignored the request to refesh). Is this other app installed with "dev" scope?

**Comment by otherjoel** [comment]
It seems the developer had recently uninstalled their app from my sandbox environment (unclear why). Once they installed it back, deploying by SOD app works properly. Since this was the first time referencing any other customization’s fields from within SOD I didn’t understand what was going on or what to look for. Thanks for the help!
