### ISSUE TITLE
Deploying Feature Error (DataTable)

### ISSUE THREAD

**Issue by mikeswartzentruber** [hougaard/Simple-Object-Designer#304]
Trying to deploy a simple Data Table and getting an error every time. 

It's set to use the number series for primary key value but gives an error:

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/16f51774-f526-4bda-86fd-40830b6ccd54)

Here is the Feature Card, doing something wrong?
![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/2266f714-700e-40d1-b472-c7e7aee36cb9)

**Comment by hougaard** [comment]
You're missing a field for the primary key. 

Think about it this way: You need one Production Instruction per <your primarykey>

If that's "per item", then the Item Number should be marked as the primary key (and you should un-check the "Use a number series for primary key.." checkbox.

**Comment by mikeswartzentruber** [comment]
I know i tried that but it's working now! Sorry for the bother.
