### ISSUE TITLE
Place an existing field in table 349 on Customer list page

### ISSUE THREAD

**Issue by ghassanm** [hougaard/Simple-Object-Designer#306]
Hi,
I tried to place the name (field number 3) from table 349 to the customer list page. I the customer list page is not available. is there a work around?

regards,
Ghassan

**Comment by hougaard** [comment]
Customer list is showing fields from the Customer Table, not from 349. To do that, you need to create a FlowField (subtype Lookup). Check this: https://www.youtube.com/watch?v=gnq2PUSozDU
