### ISSUE TITLE
Click on flowfield issue

### ISSUE THREAD

**Issue by mikeswartzentruber** [hougaard/Simple-Object-Designer#307]
I have a flowfield using a flowfield and the value that it returns is accurate, but when i click on it it should open the sales order list page with the correct filter, and the sales order number is always filted to blank...

here is my field settings:
![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/122b087c-e9d9-4380-bb39-e48031aab226)

Here is what the field looks like..
![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/578e2038-93dd-4f02-8555-031e680f6417)

This is what is looks like if i click on it...
![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/29ebd35c-f35f-489b-8a70-d9c82e18a474)

What's the issue?

**Comment by hougaard** [comment]
What is field 50731? (You cannot use another fieldflow as a filter in a flowfield)

**Comment by mikeswartzentruber** [comment]
50731 is a flowfield that uses another flowfield in the filters. :) And it does actually work just fine, until it's clicked on...

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139985257/9d757f13-6681-43cc-b704-6260888b17cb)

**Comment by hougaard** [comment]
Yeah, "it works" ... But I think that's by accident :)

**Comment by mikeswartzentruber** [comment]
Understood! :) So no workarounds with SOD?

**Comment by hougaard** [comment]
No...

**Comment by mikeswartzentruber** [comment]
thanks for direction, i'll figure it out with VS Code.
