### ISSUE TITLE
Trying to access Simple Object Designer generated fields from excel 

### ISSUE THREAD

**Issue by tstrop** [hougaard/Simple-Object-Designer#31]
I created  two text fields using the Simple Object Designer App on the Purchase header table and we are trying to access them from excel. Can you direct us to the web service table name IDs where the fields are stored?
![Purchase Order](https://user-images.githubusercontent.com/15703800/150835483-fc243a13-4ada-492a-ae86-c34a66485f2e.png)

**Comment by hougaard** [comment]
Then you need to expose the Purchase Order page (50) as a webservice. (Search for Web Services in Alt-Q).

**Comment by tstrop** [comment]
Hi Erik, we are still having problems and I was wondering if we could schedule additional assistance with you?

**Comment by hougaard** [comment]
What kind of problems?

**Comment by tstrop** [comment]
I followed the instructions as per your recommendation and as I understood them via alt-q web services and published purchase order . I'm working with an Enavate consultant who is putting an excel worksheet that aggregates information based on a global dimension value associated with various documents and he is still having problems finding the fields. He was wondering if we could get additional information to make this work. Is that a possibility?

**Comment by tstrop** [comment]
Good morning, I realize my issue exceeds the support offered with the Simple Object Designer app. Any additional advice would be appreciated. Thanks!

**Comment by tstrop** [comment]
Just wanted to follow up with a thank you for directing me to the Web Services docs article. with that and run throughs of your YouTube API video I was able to achieve what I needed for now an in the future.
