### ISSUE TITLE
Transfer additional fields from the sales order to the production order tables.

### ISSUE THREAD

**Issue by CrazyOnesHN** [hougaard/Simple-Object-Designer#312]
Hi Erik,

I need to transfer additional fields from the sales order to the production order tables. 

Page: Firm Planned Prod. Order (99000829, Document)
Page: Released Production Order (99000831, Document)
Page: Finished Production Order (99000867, Document)

Table: Production Order (5405)

Best regards,

**Comment by CrazyOnesHN** [comment]
Hi Erik,

I hope all as well with you, by the way; do you have any update about this request.

best regards.

**Comment by hougaard** [comment]
A field transfer from Sales Line to Production Order is added to the next version of SOD
