### ISSUE TITLE
Unknown Deployment Error

### ISSUE THREAD

**Issue by GrooveRings** [hougaard/Simple-Object-Designer#316]
Hi Erik,
Any idea why I'm getting this error when deploying SOD app?

Deployment failed. Errors: App ID : 888038fb-e48d-403f-a6a5-1e250be373c3 Message : { Could not upgrade the NAV extension 'New Fields by Groove Life 1.0.1.38' due to the following error: 'An unexpected error occurred after a database command was cancelled.'. }

**Comment by hougaard** [comment]
Microsoft... If it persist, try with Force mode...
