### ISSUE TITLE
Unable to publish API

### ISSUE THREAD

**Issue by bpulido76** [hougaard/Simple-Object-Designer#32]
Hi. I'm receiving this error when trying to publish an API. Please advise. Thank you.

_Deployment failed. Errors: App ID : 0b8e77a4-6e07-49b7-b7e0-2b185b9c4a42 Message : { Extension compilation failed
API/item_SOD.al(798,45): error AL0132: 'Record Item' does not contain a definition for 'Has Sales Forecast'
API/item_SOD.al(814,45): error AL0132: 'Record Item' does not contain a definition for 'EN Item Height (cm)'
API/item_SOD.al(818,44): error AL0132: 'Record Item' does not contain a definition for 'EN Item Width (cm)'
API/item_SOD.al(822,45): error AL0132: 'Record Item' does not contain a definition for 'EN Item Length (cm)'
API/item_SOD.al(826,45): error AL0132: 'Record Item' does not contain a definition for 'EN Item Weight (kg)'
API/item_SOD.al(830,45): error AL0132: 'Record Item' does not contain a definition for 'EN Item Volume (cc)'
API/item_SOD.al(834,45): error AL0132: 'Record Item' does not contain a definition for 'EN Item Height (in)'
API/item_SOD.al(838,44): error AL0132: 'Record Item' does not contain a definition for 'EN Item Width (in)'
API/item_SOD.al(842,45): error AL0132: 'Record Item' does not contain a definition for 'EN Item Length (in)'
API/item_SOD.al(846,46): error AL0132: 'Record Item' does not contain a definition for 'EN Item Weight (lbs)'
API/item_SOD.al(850,45): error AL0132: 'Record Item' does not contain a definition for 'EN Item Volume (ci)'
API/item_SOD.al(854,46): error AL0132: 'Record Item' does not contain a definition for 'EN Item Unit WPC (kg)'
API/item_SOD.al(858,52): error AL0132: 'Record Item' does not contain a definition for 'EN Item Unit VPC Volume (cm)'
API/item_SOD.al(862,46): error AL0132: 'Record Item' does not contain a definition for 'EN Item Unit WPC (lb)'
API/item_SOD.al(866,52): error AL0132: 'Record Item' does not contain a definition for 'EN Item Unit VPC Volume (ci)'
API/item_SOD.al(870,39): error AL0132: 'Record Item' does not contain a definition for 'EN Age Grade'
API/item_SOD.al(874,48): error AL0132: 'Record Item' does not contain a definition for 'EN Small Parts Warning'
API/item_SOD.al(878,40): error AL0132: 'Record Item' does not contain a definition for 'EN HTS-Canada'
API/item_SOD.al(882,53): error AL0132: 'Record Item' does not contain a definition for 'DC365 Exclude from Netstock'
API/item_SOD.al(886,51): error AL0132: 'Record Item' does not contain a definition for 'DC365 Stocking Indicator'
API/item_SOD.al(890,56): error AL0132: 'Record Item' does not contain a definition for 'DC365 Qty Purch Order(Special)'
API/item_SOD.al(894,56): error AL0132: 'Record Item' does not contain a definition for 'DC365 Qty Sales Order(Special)'
API/item_SOD.al(898,52): error AL0132: 'Record Item' does not contain a definition for 'DC365 Special Order Filter'
API/item_SOD.al(902,39): error AL0132: 'Record Item' does not contain a definition for 'Gift Card -CL-'
API/item_SOD.al(906,46): error AL0132: 'Record Item' does not contain a definition for 'Sync with Connect -CL-'
API/item_SOD.al(910,49): error AL0132: 'Record Item' does not contain a definition for 'POS Prompt Group Code -CL-'
API/item_SOD.al(914,45): error AL0132: 'Record Item' does not contain a definition for 'EFT Store Filter -CL-'
API/item_SOD.al(918,51): error AL0132: 'Record Item' does not contain a definition for 'POS Store Filter Exists -CL-'
API/item_SOD.al(922,48): error AL0132: 'Record Item' does not contain a definition for 'TRCPackageSetQtyNew'
API/item_SOD.al(926,44): error AL0132: 'Record Item' does not contain a definition for 'SQUARE Catalog ID' } - Job Id : 0fea57d3-9cda-46b2-84c3-28823104b1e9_

**Comment by hougaard** [comment]
Please try to refresh Symbols from the setup page and publish again...
(perhaps select yes to clear the cache)

**Comment by bpulido76** [comment]
Hi.

I refreshed but now I'm getting this error.

_Deployment failed. Errors: App ID : 0b8e77a4-6e07-49b7-b7e0-2b185b9c4a42 Message : { We could not update the data right now.
Please try again later.

Technical details:
A record was locked for use in another session. Administrators can see current locks on the Database Locks page or use telemetry (Snapshot ID: aeccae89-1648-46ae-882a-f0e854040e3c) } - Job Id : fb5561d3-797c-467a-879a-4c60cf3cd702_

**Comment by hougaard** [comment]
Could be another user doing something, try again later when there's less run on the system.
