### ISSUE TITLE
Not seeing the same fields on a new feature when logged into a different company.

### ISSUE THREAD

**Issue by asubi** [hougaard/Simple-Object-Designer#320]
I created a new feature in one company with certain 10 fields.  At one point, I opened the Simple Object Designer in a 2nd company within the same sandbox environment and I may have adjusted a field in that company.  
I then returned to the 1st company and added 20 more fields.  When I opened the feature in the 2nd company the fields I had added were not there. 
There does not seem to be a synchronization between companies on Features.  Is there a way to synchronize the Features?  I will be deleting the 1st company but want to make sure the Feature is intact as I had built it in the 1st company.

**Comment by hougaard** [comment]
... FULL STOP!

Extensions are not "per company", they are per environment. You should only operate SOD inside a single company (and always the sale). Currently, we do have an issue with features getting messed up if you operate from different companies.

So, please, stay in the first company :)

**Comment by asubi** [comment]
That is unfortunate...I would have hoped these tables were cross-company tables.  I was thinking of synchronizing the Feature tables with a configuration package.  Is that possible, or is there a risk?

**Comment by hougaard** [comment]
There are some other issues, you should never work on more than a single app at a time....

(We are working on an idea for having your "app" actually being two apps, working on both at the same time, but that's for 2024)

**Comment by asubi** [comment]
I am only working on 1 app.  The issue was I didn't know I could only work on the app from within one company only...
I assumed the app would be the same for all companies in the environment, so I did not make sure I was accessing the tool from only one company.  
I expect to need to clean up the companies and delete the company I am currently working in.  That is why I would like to access my app from another company...

**Comment by asubi** [comment]
If I RapidStart the SOD tables and import them into another company, that should work?

**Comment by hougaard** [comment]
You can use the "Export" and "Import" functions on the setup page if you need to have your "source".

Anyway, only use SOD in a single company, after publishing you can test all the changes in any company.

**Comment by asubi** [comment]
Thank-you!

**Comment by hougaard** [comment]
Yes
