### ISSUE TITLE
SystemCreatedBy Field on Other Pages

### ISSUE THREAD

**Issue by keysimm** [hougaard/Simple-Object-Designer#322]
Would it be possible to advise how it is possible to flow the "SystemCreatedBy" field from one page to another (e.g. Sales Header table 36 to Sales Lines Page 516) but with the field showing the text value of the username rather than random numbers and digits, which I presume is a GUID value?

I need to be able to see the human readable value of the user.

If somebody could help it would be appreciated.

![SystemCreatedBy](https://github.com/hougaard/Simple-Object-Designer/assets/134339137/d9407e54-4b66-4331-9b15-bca0b6eaa388)

**Comment by hougaard** [comment]
Not in the current version, that is not "simple" :)

**Comment by keysimm** [comment]
Just to confirm that I've achieved this by creating a flowfield lookup on Sales Line (37) via User table (2000000120) via the User Security ID field as the criteria, ensuring that SystemCreatedby (2000000002) field was present in the Sales Line table.
