### ISSUE TITLE
Flowfields with Flowfield Filters using the same field 

### ISSUE THREAD

**Issue by asubi** [hougaard/Simple-Object-Designer#323]
Hello,
Looking to create a flowfield that uses the flowfield filters, ex: like Job Task Lines total fields:

        field(10; "Schedule (Total Cost)"; Decimal)
        {
            AutoFormatType = 1;
            BlankZero = true;
            CalcFormula = Sum("Job Planning Line"."Total Cost (LCY)" WHERE("Job No." = FIELD("Job No."),
                                                                            "Job Task No." = FIELD("Job Task No."),
                                                                            _"Job Task No." = FIELD(FILTER(Totaling)),_
                                                                            "Schedule Line" = CONST(true),
                                                                            _"Planning Date" = FIELD("Planning Date Filter")));_ 

It always returns an error  "The record in table FlowField Filter already exists..." when you try to add the same field twice, even if the Filter Type is different.

Is this possible?

**Comment by hougaard** [comment]
... I don't think we're support FIELD(FILTER( right now, but you can use use flowfilter filter fields...

**Comment by asubi** [comment]
Can this be considered for enhancement?  FIELD(FILTER(... ??

**Comment by hougaard** [comment]
Sure, wait for the new release in start December...
