### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by altavistatech** [hougaard/Simple-Object-Designer#328]
I am trying to create a New Feature off with an anchor of Customer.  The feature verifies and the app file is created but when Depoying I am getting this error message.

_Package validation failed due to the following error(s): Features/CustThirdPartyBill/CustThirdPartyBill.FactBox.al (14,23) - Error PTE0008: Field '' must have a value for the ApplicationArea property so that they are visible to users. From runtime 11.0, you can specify on the application object level the ApplicationArea to use as default for all its controls and actions.
Features/CustThirdPartyBill/CustThirdPartyBill.FactBox.al (18,23) - Error PTE0008: Field '' must have a value for the ApplicationArea property so that they are visible to users. From runtime 11.0, you can specify on the application object level the ApplicationArea to use as default for all its controls and actions.
Features/CustThirdPartyBill/CustThirdPartyBill.ListPage.al (13,23) - Error PTE0008: Field '' must have a value for the ApplicationArea property so that they are visible to users. From runtime 11.0, you can specify on the application object level the ApplicationArea to use as default for all its controls and actions.
Features/CustThirdPartyBill/CustThirdPartyBill.ListPage.al (17,23) - Error PTE0008: Field '' must have a value for the ApplicationArea property so that they are visible to users. From runtime 11.0, you can specify on the application object level the ApplicationArea to use as default for all its controls and actions._

Looking at the Code I think it has something to do with the Actions section not having Application Area defined.

_[Alta Vista Technology_Operio Customizations1.0.0.91.zip](https://github.com/hougaard/Simple-Object-Designer/files/13536843/Alta.Vista.Technology_Operio.Customizations1.0.0.91.zip)_

I did not change anything I just added the fields and attempted to publish.  I watched the video on creating a new feature and do not think I am doing anything different.  Any advice would be appreciated.

**Comment by hougaard** [comment]
Can you try publishing again, because those errors are not present in the source you sent?

**Comment by altavistatech** [comment]
Thank you for taking a look.  I thought I already updated symbols but when I just went back in there it prompted me to update symbols and now it deployed.

**Comment by altavistatech** [comment]
I tried to deploy it in a different environment with just the APP file and got the same error.  Maybe I grabbed the wrong version of code last time.  Here is the app file.
[Alta Vista Technology_Operio Customizations1.0.0.95.zip](https://github.com/hougaard/Simple-Object-Designer/files/13536993/Alta.Vista.Technology_Operio.Customizations1.0.0.95.zip)

**Comment by altavistatech** [comment]
I tried to deploy it in a different environment with just the APP file and got the same error. Maybe I grabbed the wrong version of code last time. Here is the app file.
[Alta Vista Technology_Operio Customizations1.0.0.95.zip](https://github.com/hougaard/Simple-Object-Designer/files/13536997/Alta.Vista.Technology_Operio.Customizations1.0.0.95.zip)

**Comment by hougaard** [comment]
I still don't see anything in that app file that would give that error?

**Comment by hougaard** [comment]
(Sorry for the late reply)

**Comment by altavistatech** [comment]
Thank you for replying.  I will take another run through and see what happens.  I may circle back with you.
