### ISSUE TITLE
Changing field in "Update Document" for posted sales cr. memo does nothing

### ISSUE THREAD

**Issue by otherjoel** [hougaard/Simple-Object-Designer#329]
I have three custom fields which I have added to the Sales Cr.Memo Header.

* I have placed the fields on the `Pstd. Sales Cr. Memo - Update` page (1354). (learned my lesson from #239)
* I have added the field transfers for all three fields to the `Sales Cr.Memo Header` ("for update of posted document") and activated the transfers.

After deploying my app, I can open a posted sales credit memo, click “Update Document”, and see/edit these three fields. However, after editing any of these fields and clicking **OK**, the posted document is **not** updated.

These same three fields have also been added to the Update Document page for Posted Sales Invoices, and there the update functionality **is** working correctly.

It may be a gap in the code generation. In the `FieldManagement.al` source for my app, I see there is an Event Subscriber for `Page::"Posted Sales Inv. - Update", 'OnAfterRecordChanged'`. But there is no event subscriber for the equivalent event for the Sales Credit Memo. (In looking through it, I think the Posted Purchase Credit Memo may be similarly afflicted, or perhaps that one is just not implemented yet.)

**Comment by hougaard** [comment]
You need to add a field transfer from the Sales Cr. Memo header to the same table :)

**Comment by otherjoel** [comment]
> You need to add a field transfer from the Sales Cr. Memo header to the same table :)

Yep, did that (second bullet point above)

**Comment by hougaard** [comment]
Ahh.. (answered from phone, didn't read everything), let me check!

**Comment by hougaard** [comment]
Added in version 10.0.0.386
