### ISSUE TITLE
Item Class

### ISSUE THREAD

**Issue by sjmoelgaard** [hougaard/Simple-Object-Designer#333]
Hey Eric, 

Is it possiable to make e new field showing the description of another field. 

I want to show the category Code name on items, i have tried with flow field and lookup but cant seem to get it working. 

Is it me, or is it now possiable ? :) 

Kind Regards
Stefan

**Comment by hougaard** [comment]
That should be possible with a FlowField, subtype = Lookup.

**Comment by sjmoelgaard** [comment]
That is eacatly what i tried, but cant get it to work. Here is my setup

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139542638/60f0d303-671f-42e4-bd4a-119df059ab4f)

and the result 

It just says computere no matter what i do. 

![image](https://github.com/hougaard/Simple-Object-Designer/assets/139542638/79b67532-0e4d-4b2e-b5f8-0715e0f9048e)

**Comment by hougaard** [comment]
Have you specified the flowfield filter (in the next section), you need to link the "Item Category Code" field to the Code field in the Item Category table.
