### ISSUE TITLE
Warehouse Shipments

### ISSUE THREAD

**Issue by altavistatech** [hougaard/Simple-Object-Designer#335]
I am trying to add fields to the Warehouse Shipment page (Table 7320, page 7335) and transfer to the Posted Warehouse Shipment page (Table 7322, Page 7337).  Fields were added to the Warehouse Shipment page but there is no option to transfer the fields.

Is this a bug or something that needs to be added?  I saw a request for Warehouse transfers out here as well.

**Comment by hougaard** [comment]
Added in 10.0.0.384
