### ISSUE TITLE
API "When Record is Created" limitation

### ISSUE THREAD

**Issue by teganZT** [hougaard/Simple-Object-Designer#336]
Hi Erik,

I am using a SOD API as a trigger for a PowerAutomate flow. It triggers when a Job Journal line is created, and inserts the correct line type based on the job type. This worked correctly until we switched from Dynamics Timesheets to importing timesheets from Atlassian into the Job Journal.

Now that we are bulk importing Job Journal Lines, the "When a record is created" trigger does not run consistently. Is there a rate limit to this? I found that Microsoft recently [increased the change modification limit to 1000](https://learn.microsoft.com/en-us/dynamics365/release-plan/2023wave2/smb/dynamics365-business-central/change-modification-limits-triggering-flows-bulk-updates). Does that also apply to SOD or is there a different limit?

Thank you,

Tom

**Comment by hougaard** [comment]
APIs from the Simple Object Designer are just like any other API.

In general, it seems that those triggers are not always triggered, many people experience the same as you. I consider them quite unreliable and try not to use them.
