### ISSUE TITLE
Transferring fields from Sales Order to Purchase Order

### ISSUE THREAD

**Issue by HMadsen4000** [hougaard/Simple-Object-Designer#339]
Hi Erik

Many of our orders are handled as drop-shipments.

It would be super helpful if we could transfer fields from the salesorder header to the purchase order header.

BR
Henrik Madsen

**Comment by hougaard** [comment]
I'll add that, look for version 10.0.0.391 or later...

**Comment by HMadsen4000** [comment]
I have installed the update and I can see it is now possible to transfer the fields. But I cannot get the values transferred...

I need to get phonenumber (field 171) and email (field 172) from the contact on the salesorder header, transferred to the purchaseorder header.

After creating the purchase order with "indkøbskladde", the new fields I have added to the purchaseorder header remains empty.

Could it be that you are assuming another way of creating the purchase order?
