### ISSUE TITLE
Deployment Status Failed

### ISSUE THREAD

**Issue by KeriRatering** [hougaard/Simple-Object-Designer#34]
Deployment failed. Errors: App ID : 4fed44b8-b2b6-4526-8da3-8141132fd4c0 Message : { Cannot upgrade the NAV extension Implementation_dbasic by Doornekamp 1.0.0.27 because of the following error: TableExtension SODSales_Shipment_Header :: The table Sales Shipment Header cannot be found. Deletion of tables is allowed only if they are temporary or moved by migration to another app... } - Job Id : 81a2de1a-24c6-4528-ab7d-14dcd5ce1e73

How can we solve this problem?

**Comment by hougaard** [comment]
If you want to delete a previously deployed field or feature, you must upload the .app file to extension management and set schema sync mode to "Force". The automatic deployment will not allow deletions and give an error like that.
