### ISSUE TITLE
Report Calculated Field for I purchase line

### ISSUE THREAD

**Issue by altavistatech** [hougaard/Simple-Object-Designer#340]
I am trying to add a calculated field on a Purchase Order line.

The expression should be this.
Purchase Line."Direct Unit Cost"/Purchase Line.UofM_Wt_KG

I used the Cheat Sheet to pull in the first field and then used that syntax to add a SOD field.  When I go to publish the app I get an error on Purchase and Line that they are not recognized values.  I have tried removing the space, using an underscore and putting the name in quotes but still the equation will not verify and will not deploy.  Is there an issue with Purchaser Line?

**Comment by hougaard** [comment]
How about?

Rec."Direct Unit Cost" / Rec.UofM_Wt_KG

**Comment by altavistatech** [comment]
I appreciate your input however now I am getting this error.

Package validation failed due to the following error(s): ReportExtensions/Purchase_Order_ReportExt.al (227,44) - Error AL0118: The name 'Rec' does not exist in the current context.
ReportExtensions/Purchase_Order_ReportExt.al (227,19) - Error AL0118: The name 'Rec' does not exist in the current context.

**Comment by hougaard** [comment]
Ahh.. on a report, (I have got page syntax):

Try:

"Purchase Line"."Direct Unit Cost"/"Purchase Line".UofM_Wt_KG

**Comment by altavistatech** [comment]
OK I thought I tried that but apparently there is a PICNIC error going on.
