### ISSUE TITLE
unable to change caption

### ISSUE THREAD

**Issue by plsimmons** [hougaard/Simple-Object-Designer#35]
I am trying to demo the simple object designer, but nothing changes after publishing when I make the change to the field caption as instructed on your youtube channel.

**Comment by hougaard** [comment]
Do you have personalizations on that page?

**Comment by plsimmons** [comment]
I don't think so. It is on my dedicated sandbox environment.




Preston Simmons



Safari Endeavors, LLC

PO Box 419

Quanah, TX 79252

C: 903-245-7563<tel:+19032457563>

T: 1-888-426-7473<tel:+18884267473>

F: 940-257-6550<tel:+19402576550>

***@***.***



[image]

________________________________

**Comment by hougaard** [comment]
Please send the .app file to support@hougaard.com and I'll take a quick look.

**Comment by plsimmons** [comment]
I will as soon as I get back to the computer.




Preston Simmons



Safari Endeavors, LLC

PO Box 419

Quanah, TX 79252

C: 903-245-7563<tel:+19032457563>

T: 1-888-426-7473<tel:+18884267473>

F: 940-257-6550<tel:+19402576550>

***@***.***



[image]

________________________________

**Comment by plsimmons** [comment]
I just sent the app…

**Comment by plsimmons** [comment]
1)
***@***.***

2)
***@***.***

3)
***@***.***
4) Publish


Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by plsimmons** [comment]
Erik,

Did you have a chance to look at my issue?

Thank you,



Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

From: Preston Simmons
Sent: Monday, January 31, 2022 11:06 AM
To: hougaard/Simple-Object-Designer ***@***.***>; hougaard/Simple-Object-Designer ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [hougaard/Simple-Object-Designer] unable to change caption (Issue #35)

1)
***@***.***

2)
***@***.***

3)
***@***.***
4) Publish


Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by hougaard** [comment]
I sent you an email reply on the 28th, didn't you get it?

**Comment by plsimmons** [comment]
I did not. I don’t see anything on github either.



Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by plsimmons** [comment]
Erik,

I’m still at a loss and I didn’t receive a message. Do you have any suggestions?

Thank you,



Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by hougaard** [comment]
The extension you send me was completely empty, can you email me some screenshots of what customization you have created?

**Comment by plsimmons** [comment]
I tried to in an earlier email. It’s possible that my server didn’t let it through so I will try again.



Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by plsimmons** [comment]
I just resent. I zipped the app file hoping that would get around any filters, but I still got a message stating that recipients using outlook may have issues opening the file.



Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by hougaard** [comment]
Received, both files are empty, there are NO customizations in then? Have you added any fields? Can you email me screenshots of what you have done in the Object Designer?

**Comment by plsimmons** [comment]
I sent this with the app in the original email. These are the steps that I followed:

1)
***@***.***

2)
***@***.***

3)
***@***.***
4) Publish




Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by plsimmons** [comment]
I just sent over an email with screenshots.



Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by hougaard** [comment]
got it, thanks!

**Comment by hougaard** [comment]
Ahh, I see what you're trying to do...

That's a bug, will be fixed in the next version (coming soon, we're just wrapping up the last pieces).

**Comment by plsimmons** [comment]
Sounds good. How will I know when it is available?



Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by hougaard** [comment]
... keep an eye on hougaard.com :)

but there's actually a workaround, if you go to Tables (under inspect) and click customize on table 112, and then just close the page again, then it should be included and generated correctly.

**Comment by plsimmons** [comment]
Good enough. Will it work in a production environment?

Thank you,



Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***

**Comment by hougaard** [comment]
yes.

**Comment by plsimmons** [comment]
Great! Thank you very much!



Preston Simmons

Safari Endeavors, LLC
PO Box 419
Quanah, TX 79252
C: 903-245-7563
T: 1-888-426-7473
F: 940-257-6550
***@***.******@***.***>

***@***.***
