### ISSUE TITLE
New section not devided in 2 tables

### ISSUE THREAD

**Issue by Lennardleenheer** [hougaard/Simple-Object-Designer#354]
Hello, I have added some new fields to the qoute page. I have also created a new section. 
The fields I added to this new section have the full page width and are not devided into 2 columns like other sections. 
How can I devide the new section into 2 columns ?

![normal](https://github.com/hougaard/Simple-Object-Designer/assets/92366390/ea013b30-c2f8-4086-af3b-7e242d374f92)

![SOD](https://github.com/hougaard/Simple-Object-Designer/assets/92366390/88bad015-e29f-4799-b96d-547100516f62)

**Comment by ScottB-Ronco** [comment]
I have the same issue and what I did was I used the personalize feature to move the fields to be beside each other.

Now personalize only does it for the current logged in user. If you want to apply to all users then in BC search for Profiles (roles) and customize that page for each role that your your users use.

**Comment by Lennardleenheer** [comment]
Thank you very much ! This worked for me !
