### ISSUE TITLE
Exposing SystemCreatedBy on Customer Card

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#359]
I went and exposed the field SystemCreatedBy to show on the customer card.

However when shown, it shows the GUID, but when you do CTRL-ALT-F1 to show the Page Inspection details there is shows the name with the GUID in brackets.

Is there a way to have it show the name of who create record and not the GUID?

**Comment by hougaard** [comment]
Create a FlowField (type Lookup) to the User table.

**Comment by ScottB-Ronco** [comment]
That's what I thought, but wasn't sure.

I created a FlowFields as lookup and all it good now.
