### ISSUE TITLE
metadata hgd doesn't exist while publisher

### ISSUE THREAD

**Issue by KenAllgood** [hougaard/Simple-Object-Designer#360]
I see several others have had this error, but don't see any solutions.

Error: The Field MetaData Hgd does not exist. Identification fields and values: TableNo='51522',No.='1'

I've Refreshed the Symbols twice and tried publishing, same error.   This appears to be a custom table referenced and the table no longer exists.   What do we need to do to get past this?

**Comment by hougaard** [comment]
Sounds like there's something fishy in the extensions you have installed, check Extension Management to see if there are some old PTEs that you can remove?

**Comment by infuzion-BC** [comment]
We were able to get past that issue.   Next question is, will this work with eOne SmartConnect?   I can retrieve the data using Excel Odata, so the webservice is available.   However, when I try to connect using SmartConnect, I get 

Unable to retrieve the companies: Unable to get the companies: The remote server returned an error: (404) Not Found.
