### ISSUE TITLE
Filter ShipTo list on Sales Order

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#367]
Is there a means within SOD to filter lists in BC based on a field?

If we were to create a field on the ShipTo card in BC called Status and give it values of Active or Inactive could we then use this field to filter the results shown on in the ShipTo Code field on the Sales Order?

We have many customers where their various locations get closed or moved and right now we add a DO NOT USE in the front of customer name on ShipTo, but ideally we would like to hide values that are no longer active.

Thank
Scott

**Comment by hougaard** [comment]
Hi Scott,

All fields are filter-able in the filter pane (Shift-F3). I suggest you create a saved view on the sales order page:
https://learn.microsoft.com/en-ca/dynamics365/business-central/ui-views

**Comment by ScottB-Ronco** [comment]
Hello Erik,

That link is for filtering list view pages. What we want to achieve is when we're in a sales order and wanting filter the the drop down list that comes up when we select the code field in the shipto section as shown in the image below.

Even if we click the select from full list view there is no option to filter here and pressing Shift-F3 doesn't work.

![image](https://github.com/user-attachments/assets/9cd169b3-917e-4aa1-b280-5701cc7ae8cb)

**Comment by ScottB-Ronco** [comment]
Hello Erik,

Just following up on my last reply clarifying my request

**Comment by hougaard** [comment]
Sorry, I though I typed a reply...

anyway, this is not something you can accomplish with the Simple Object Designer, you might be able to solve it with the "Advanced Cloud Security" app... That one can set filters all over the place.

**Comment by ScottB-Ronco** [comment]
OK thank you, I will download a trial of the security app to see if it does what we need and then decide from there .
