### ISSUE TITLE
Posting Error after added a boolean field in Sales Order Header and transfer to Sales Order Archive

### ISSUE THREAD

**Issue by asbkevl** [hougaard/Simple-Object-Designer#369]
Hi Erik, I'd created a boolean field in Sales Order Header and transfer to Sales Order Archive. An error occurred when I want to post the Sales Order. 
Seems like this boolean field has conflicted with other SOD custom field.

![image](https://github.com/user-attachments/assets/e695c7ee-e6da-4918-a74f-1b83a2182bbe)

Error Detail:
If requesting support, please provide the following details to help troubleshooting:

Error message: 
The following fields must have the same type:

Field: [C] By B2BE <-- [C] Seal No.
Table: Sales Header Archive <-- Sales Header
Type: Boolean <-- Text

Internal session ID: 
dd1d43f8-9a15-4a0f-aba7-1928c683a038

Application Insights session ID: 
5fae0837-6f9b-4430-a0fc-72fe6d8c6009

Client activity id: 
739ae0ef-a5fd-434b-9476-babbe7ed9a15

Time stamp on error: 
2024-11-14T01:40:39.7487958Z

User telemetry id: 
13d485e3-e098-4501-92a8-25f4a6ee0ce9

AL call stack: 
ErrorMessagesRecommendationExt(PageExtension 7900)."Description - OnDrillDown"(Trigger) line 10 - Error Messages with Recommendations by Microsoft

Custom dimensions: 
[{"Item1":"ErrorCallStack","Item2":"ArchiveManagement(CodeUnit 5063).StoreSalesDocument line 13 - Base Application by Microsoft\\ArchiveManagement(CodeUnit 5063).ArchSalesDocumentNoConfirm line 9 - Base Application by Microsoft\\ArchiveManagement(CodeUnit 5063).AutoArchiveSalesDocument line 23 - Base Application by Microsoft\\\"Sales-Post\"(CodeUnit 80).FinalizePosting line 63 - Base Application by Microsoft\\\"Sales-Post\"(CodeUnit 80).RunWithCheck line 68 - Base Application by Microsoft\\\"Sales-Post\"(CodeUnit 80).OnRun(Trigger) line 2 - Base Application by Microsoft\\\"Sales-Post (Yes/No)\"(CodeUnit 81).OnRunPreview line 18 - Base Application by Microsoft\\\"Gen. Jnl.-Post Preview\"(CodeUnit 19).OnRunPreview(Event) line 2 - Base Application by Microsoft\\\"Gen. Jnl.-Post Preview\"(CodeUnit 19).RunPreview line 4 - Base Application by Microsoft\\\"Gen. Jnl.-Post Preview\"(CodeUnit 19).PreviewStart line 19 - Base Application by Microsoft\\\"Gen. Jnl.-Post Preview\"(CodeUnit 19).Preview line 7 - Base Application by Microsoft\\\"Sales-Post (Yes/No)\"(CodeUnit 81).Preview line 6 - Base Application by Microsoft\\\"Sales Order\"(Page 42).ShowPreview line 4 - Base Application by Microsoft\\\"Sales Order\"(Page 42).\"PreviewPosting - OnAction\"(Trigger) line 2 - Base Application by Microsoft\\"},{"Item1":"CreatedOn","Item2":"14/11/24 09:40 AM"}]

**Comment by hougaard** [comment]
That's Business Central being too clever.

This is what you do:

Use personalization to show the **Field No.** field to the new fields list. (Yes I know, too many "fields" in that sentence)

Then, make sure that the "same" field has the same Field No., in this case it's [C] By B2BE and [C] Seal No. that has the same number. You are allowed to switch numbers around.

This sometimes happens when fields are added in an unlucky order.

**Comment by asbkevl** [comment]
Hi Erik, your suggestion works! Thanks mate.
I just couldn't understand why this only happens to boolean field and not other field type. I'd added multiple of field in Sales Header and transfer to Sales Order Archive. All working fine until I added a boolean field.

![image](https://github.com/user-attachments/assets/e968e72c-2c05-4c78-8de7-74484bd5403d)

![image](https://github.com/user-attachments/assets/2d340b4f-9e28-47f9-b093-fd8487e3fe3d)
