### ISSUE TITLE
SOD won't open

### ISSUE THREAD

**Issue by CempBC** [hougaard/Simple-Object-Designer#370]
Not sure what is going on however i can't get SOD to open I have setup multiple fields and few features and now the App will not open when i search for it in BC i can see it come up however when i click it does nothing. All fields and feature that have been created are working.

**Comment by edward-nunn** [comment]
Same issue. Updated the app in BC admin portal. Currently having the below mismatch in Extension Management.

![image](https://github.com/user-attachments/assets/ffe607d8-3ac8-4540-a796-079ebb10f7b5)
![image](https://github.com/user-attachments/assets/2a5760bb-82d3-4719-8559-efba7ad27db6)

@hougaard I've also sent an email about this to support@hougaard.com earlier today. This is causing quite a big impact for us and would appreciate a response quickly, many thanks.

**Comment by hougaard** [comment]
"Allow HttpClient Request" MUST be turned on....

**Comment by hougaard** [comment]
Can you try adding page=70310263 to your URL ?

**Comment by CempBC** [comment]
I tried that it keeps on trying to load. Getting ready... screen
![image](https://github.com/user-attachments/assets/d4d390c5-4f90-4ab0-811c-72357dcbb250)

**Comment by hougaard** [comment]
Please go to admin center and restart the environment (If everything else fails, reboot).. You can also check Telemetry in admin center to see if there are weird errors showing up...

**Comment by CempBC** [comment]
Still no luck i have restarted all environments installed SOD on new sandbox (copy of prduction environment) I have checked telemetry no wierd errors. I'm running out of ideas. I luckily made source copy, even though i did some changes post that copy I might have to use that until solution to my issues.

**Comment by hougaard** [comment]
I need access to a sandbox where this happens, so I can connect a debugger. Please reach out on support@hougaard.com

**Comment by PatProHub** [comment]
Same Issue for me!
The problem (no loading of SOD and screen freeze) after clicking the sod exists even in a completely fresh environment.
It must be a general SOD issue.

**Comment by hougaard** [comment]
Thanks, it started happening on my tenant also this morning... Stay tuned!

**Comment by hougaard** [comment]
... It's a bug in Business Central.

I have devised a way to circumvent the issue (a brand new menu page). Please update the Admin Center and try again.

If you do have the Simple Object Designer bookmarked on your rolecenter, that bookmark is "dead" (at least until Microsoft fixes the issue). Start Simple Object Designer from the Alt-Q search function.

**Comment by CempBC** [comment]
Thanks Erik. 
Back in business...

**Comment by PatProHub** [comment]
Thanks too!
It's working again.
Can you explain some detail of this crazy issue?
