### ISSUE TITLE
Error trying to publish

### ISSUE THREAD

**Issue by Debej** [hougaard/Simple-Object-Designer#38]
I get the following when trying to publish changes made to placement of existing fields on pages
Field Name must have a value in New Fields: Table No=0, FieldNo=0. It cannot be zero or empty.

Internal session id: 
1ba0949c-e732-488c-83b3-02710b40db88

Application Insights session id: 
4a7354ee-756a-4e82-9bd0-cef9cf052acc

Client activity id: 
25ccee62-5151-4108-a8cf-a19109fcaf96

Timestamp: 
2022-02-17T22:34:04.2802851Z

AL call stack: 
"Build Extension Hgd"(CodeUnit 70310250).ExportTableExtensions line 32 - Simple Object Designer by Hougaard
"Build Extension Hgd"(CodeUnit 70310250).CreateExtension line 86 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."ExportExtension - OnAction"(Trigger) line 6 - Simple Object Designer by Hougaard

**Comment by Debej** [comment]
Yes but how do I know which table as I also get an error when selecting only customized objects

Regards


Debbie Jones
Group Systems Administrator
p: +61 2 4230 8029 | m: +61 402 330 335
e: ***@***.*** | w: www.kollaras.com
a: PO Box 424, Figtree NSW 2525 Australia

​Please note our postal address has changed
 Please consider the environment before printing this email.
_____________________________________________________________________________________________________
DISCLAIMER: This email and any files transmitted with it are confidential and may be the subject to copyright. They are intended solely for the use of the individual or entity to which they are addressed. If you have received this message in error please notify the Kollaras Group immediately by return email or by calling +61 (0)2 4230 8000. Any views or opinions expressed in this email are solely those of the author and do not necessarily represent those of the Kollaras Group except where an authorised sender specifically states them to be views of the Kollaras Group. It is your responsibility to verify this email and any attachments for the presence of viruses. The Kollaras Group accepts no liability for any damage caused by any virus transmitted here.

**Comment by Debej** [comment]
Hi

Disreagrd last email - found it  -thank you

Regards


Debbie Jones
Group Systems Administrator
p: +61 2 4230 8029 | m: +61 402 330 335
e: ***@***.*** | w: www.kollaras.com
a: PO Box 424, Figtree NSW 2525 Australia

​Please note our postal address has changed
 Please consider the environment before printing this email.
_____________________________________________________________________________________________________
DISCLAIMER: This email and any files transmitted with it are confidential and may be the subject to copyright. They are intended solely for the use of the individual or entity to which they are addressed. If you have received this message in error please notify the Kollaras Group immediately by return email or by calling +61 (0)2 4230 8000. Any views or opinions expressed in this email are solely those of the author and do not necessarily represent those of the Kollaras Group except where an authorised sender specifically states them to be views of the Kollaras Group. It is your responsibility to verify this email and any attachments for the presence of viruses. The Kollaras Group accepts no liability for any damage caused by any virus transmitted here.
From: Debbie Jones
Sent: Friday, 18 February 2022 10:27 AM
To: hougaard/Simple-Object-Designer ***@***.***>; hougaard/Simple-Object-Designer ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [hougaard/Simple-Object-Designer] Error trying to publish (Issue #38)

Yes but how do I know which table as I also get an error when selecting only customized objects

Regards

**Comment by hougaard** [comment]
I'll add an extra filter to avoid this situation.

**Comment by Debej** [comment]
Thank you Eric for the speedy reply
