### ISSUE TITLE
Publish isue: the record is no open

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#39]
I have just updated the extension to the latest version 4.0.0113 (which by the way is awesome, I am looking forward to create my own table).

However, when publishing after adding a new filed to a table, I got the error "The record is not open", and the publish doesn't even start.

This is the info shown:

The record is not open.

Internal session id: 
43123ee1-ff9b-4510-ba6e-e1f18a981cdc

Application Insights session id: 
4a5bf7b7-47b4-45fd-ae15-d08b578e5108

Client activity id: 
eccf7f94-da78-4e89-a945-36936c565bfa

Timestamp: 
2022-02-22T09:15:56.7919493Z

AL call stack: 
"Build Extension Hgd"(CodeUnit 70310250).ExportTableExtensions line 111 - Simple Object Designer by Hougaard
"Build Extension Hgd"(CodeUnit 70310250).CreateExtensionEx line 195 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."ExportExtension - OnAction"(Trigger) line 6 - Simple Object Designer by Hougaard

Any help would be greatly appreciated.

**Comment by juasanri** [comment]
Update: I have done a init new app, and I can publish with the new App, so I will leave the previous one safely stored in order to reinstall it if necessary.

**Comment by juasanri** [comment]
Update: I have tried with a new App, after downloading the previous installed app.

In the new app, I have added just one field, but it gives me an error when doing the Publish (the Publish process starts, not as before that doesn't even start). The error is:

Deployment failed. Errors: App ID : cdee0ab4-90a2-4faa-b47f-42e150f5b759 Message : { The object name 'Field Transfers Mgt. SOD' can only appear once for the type 'CodeUnit'. The same object exists in both extension ('cdee0ab4-90a2-4faa-b47f-xxxxxx' 'PC_Nuevos_Campos_02', Publisher: Polymer Char, Package ID: 1caa17ac-edd5-47d5-8e7a-xxxx, Runtime Package ID: 85ea6956-35ca-47c2-9fc3-xxxx, Scope: Tenant, Version: 1.0.0.1) and in extension ('6b540f1d-6281-4047-b564-xxxx' 'PC_Nuevos_Campos', Publisher: Polymer Char, Package ID: 2689380f-d72a-43bb-ba8e-xxxx, Runtime Package ID: a8759e0a-5472-4a1f-b52a-xxxx, Scope: Tenant, Version: 1.0.0.21). } - Job Id : 9d3e76d1-a1f3-4a4b-ac46-xxxx

Any help would be greatly appreciated.

Thanks

**Comment by hougaard** [comment]
You cannot have the same prefix (in SOD Setup) for two different apps, go change and publish again.

**Comment by hougaard** [comment]
Check "Inspect Tables" - is there a weird entry for table 0 ?

**Comment by juasanri** [comment]
Yes. When I hit the "Only customized objects" the following information is shown:

The Table Metadata Hgd does not exist. Identification fields and values: Table No.='0'

**Comment by hougaard** [comment]
Strange...  Not sure how you manage to get a blank entry into that table... I'll add some preventive code...

Will take a couple of days.

**Comment by hougaard** [comment]
If you want, please email me the json (setup page -> export app) then I'll take a look...

**Comment by juasanri** [comment]
Here you have it

https://acpolymerchar-my.sharepoint.com/:u:/g/personal/juan_sanchotello_polymerchar_com/EWrKcKRMaK1Nvta-Z1e8bBwBFzFfNRPVhdM7xNbra8_fMQ?e=aw7eO0

Thanks

**Comment by hougaard** [comment]
thanks

**Comment by hougaard** [comment]
If you edit the json file with notepad and remove this entry:

{"F1":0,"F4":"","F2":"","F40":""}

Save the file, and import again..

**Comment by juasanri** [comment]
This solved my issue. 

Thank you very much for this fast response!
