### ISSUE TITLE
New feature suggestion: new field type, hyperlink.

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#40]
I am am greatly impressed by the Simple Object Designer, and would like to suggest a new type of field: hyperlink.

In my company, we have a Sharepoint structure where all the documentation is stored, in an organized way. We have one folder per customer, per vendor...
All the sales order to a customer are stored under the customer folder, all the purchases order from a vendor are stored under the vendor folder, an so on.

As we didn't want to use the "links" feature of the pages, we asked a developer to put a new field in the header of some pages (customers, vendors...) called "Sharepoint Link", that we fill in with link to the Sharepoint folder.

We wanted to have this in the header and not as a link record, because thanks to the Simple Object Designer, we could expose this field in a custom API, and we can automate everything: when a new record in the customers table is created, a power automate routine is fired that creates the folder in our Sharepoint site withe the proper naming convention and in a given folder structure. This routine creates a read-only link for people in our organization that is saved back in the header in this field "Sharepoint link".

The nice thing is that by clicking on the field (when the page is in read only mode), we can navigate to the Sharepoing folder associated.

All this long story is to request this type of field available in the "create new field" option in the Simple Designer Object, as this would allow us to place and automate this in any page that we need.

Thanks.

**Comment by hougaard** [comment]
You should really check out the SharePoint Connector app, check the videos here: https://www.youtube.com/playlist?list=PLowctfi3tRdHHiyoJhcwBawgSBx5bdWZE

**Comment by juasanri** [comment]
I checked the videos, it is a really powerful app, but still it doesn't fit our needs. We want to have those links in any table (also in the new ones we are doing with the "New Feature" of the SOD).
Also, in the Sharepoint folders we have some hierarchical structure, and not only 2 levels.
We currently do all this through Power Automate and Power Apps, and in the tables were our partners didn't add the hyperlink field, we are using the Links-Attachments in the factbox of the page. But this cannot be automated through Power Automate and needs to be done manually.
Also, by adding new tables with the SOD now, we would also like to add those hyperlinks in our new tables.

Maybe even if the hyperlink can do an http request, it could throw a Power Automate Flow, what would be really awesome in terms of personalization and automation, together with custom APIs that the SOD allows.

Thanks for listening :)
