### ISSUE TITLE
Request: Extended Data Type

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#45]
Hello again.

Would it be possible to add the extended data type in the SOD?

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-extendeddatatype-property

This would allow for emails, web pages, phones, etc, in the new fields, and in the new features.

Currently, we can download the source code and change just this:

 field(103;"Home Page";Text[80])

       {

           Caption = 'Home Page';

           ExtendedDatatype = URL;

       }

But it would be really awesome that this is done in the SOD directly :)

Thanks

**Comment by hougaard** [comment]
Great suggestion, I'll put that on the list.

**Comment by hougaard** [comment]
Added to the newest version.
