### ISSUE TITLE
Can't see fields to place on report 1308 Sales Shipment

### ISSUE THREAD

**Issue by tstrop** [hougaard/Simple-Object-Designer#46]
Trying to figure out what I'm doing wrong. Trying to get shortcut dimension 1 and shortcut dimension 2 to populate on Sales Shipment Report 1308 shipping
Add existing fields to pages and reports, Table 110 Sales Shipment Header, placed on Page No 130 posted Sales Shipment Document addafter Document Date and page No 142 Posted Sales Shipments, List Addafter Document Date and then placed it on all the various reports and notice that Report No 1308 Standard Sales - Shipment dataitem states Header where all the others Dataitem says Sales Shipment Header. All the place boxes are checked. Published - When I export the 1308 layout and open in edit view/developer XML 1308 etc shortcut dimension 1 and shortcut dimension 2 are NOT available to place on Sales Shipment Report 1308? Do you know what I'm missing?
[2022-02-28_17-06-01 2.pdf](https://github.com/hougaard/Simple-Object-Designer/files/8157623/2022-02-28_17-06-01.2.pdf)
[2022-02-28_17-06-46 1.pdf](https://github.com/hougaard/Simple-Object-Designer/files/8157624/2022-02-28_17-06-46.1.pdf)

**Comment by hougaard** [comment]
When you export the layout from the Custom Report Layout page, have you tried to use the Update Layout function first?
![image](https://user-images.githubusercontent.com/3357237/156087840-c68d552d-46b3-43ab-bcce-2f5c4f37ab42.png)
