### ISSUE TITLE
Publish error

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#49]
Hello,

I have an issue when publishing: I have created a table with a code, a setup table for number of series, and a lookup field in the service item table. Then several read only fields that are transferred from the service item selected.

I have not been able to publish it. I have the following error code:

Package validation failed due to the following error(s): (1,13): error PTE0004: Table '65000' is missing a matching permission set. - Job Id : f1e899f4-8fa9-4e35-8ee4-117fc925c369

Could you give me a tip on where to investigate to solve it please?

Thanks

**Comment by hougaard** [comment]
Please send the .app file to support@hougaard.com and I'll take a look at what goes on.
