### ISSUE TITLE
Suggestion: Use SOD to Change field caption

### ISSUE THREAD

**Issue by ghassanm** [hougaard/Simple-Object-Designer#5]
It would be very helpful if we have the option to change the field caption on existing field. Additionally, on the home page to the extension, can you add button for creating new extension instead of going to manage and then create new. Currently, by default it brings up the last created extension.

**Comment by hougaard** [comment]
That everything goes into the same extension is done on purpose. Separate fields in different extension makes it problematic on the long run.

Changing caption on existing fields is a great suggestion!

**Comment by hougaard** [comment]
The ability to change captions is release in version 1.0.0.17 - available from AppSource now.

**Comment by ghassanm** [comment]
Wow, this is quick. Thanks.

**Comment by ghassanm** [comment]
Thanks Eric, it is working fine from the field property page. An interesting observation: When adding a field of type ENUM or Lookup and click on advance settings nothing happens. What should happen when clicking on advance settings?

Thanks,
Ghassan

**Comment by hougaard** [comment]
The Option and Enum column will show in the list, try scrolling right...

**Comment by ghassanm** [comment]
Thanks for the quick response. Another suggestion: Formula Field, Concatenate, calculated field. I pay the vendor for fuel based on the market rate for the month. The accountant enters the average market rate and multiply by the number of gallons/LBs used  (Converting Gallons to LBs). The Density varies from vendor to vendor. Operation enters the density expected from the vendor.
I don't mean to go on a tangent, It would be very helpful if I can create calculated field  doing basic operations on two or more fields without writing a procedure in a code unit. I am trying to avoid AL and leave to the experts like you.

Regards,
Ghassan

**Comment by ghassanm** [comment]
By the way, I think this app has lots of potential since it creates the code and downloaded to VSC for editing. Power Apps for BC. :)

**Comment by hougaard** [comment]
The whole idea is certainly that you can graduate from this app and move into VS Code without losing anything.

**Comment by ghassanm** [comment]
Good point! I still prefer to fire up SOD to add a simple calculated field. Good Job!

**Comment by hougaard** [comment]
We'll get there, but that will take way longer than support for captions :)

**Comment by ghassanm** [comment]
I do understand. I can appreciate the effort required. Kudus to you and your team. I watched your ENUMIFY :). It is way over my head at this time. I can see how it will replace options on the long run. You promised a walk through of downloading the code from SOD to VSC, modify and publish. I am looking forward for this video.

Regards,
ghassan
