### ISSUE TITLE
Boolean Value not accepted in API-Power Apps?

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#50]
I have created a new feature that has a field of boolean type. I have exposed that field in the API.

When I get the table through the API in PowerApps, it populates properly the table, and the column is shown as a checkbox (very last column in this case):

![image](https://user-images.githubusercontent.com/99739571/158416366-6eb0fe0a-418b-428f-bad8-0ae761c2207b.png)

However, if I change my filter query to filter the table by this boolean column, I get an error saying that this value is not compatible:

![image](https://user-images.githubusercontent.com/99739571/158416689-b85b6196-bc3f-4623-bbb9-805cfc8a1a9c.png)

Do you know if this is a limitation of PowerApps, or is it something with the API of the SOD?

Thanks

**Comment by hougaard** [comment]
Try "true" instead of "Yes.

**Comment by juasanri** [comment]
It is not something I type, it is just the value of the Checkbox: 
pchar_ts_finalizado = Checkbox_Cerrados.Value

**Comment by hougaard** [comment]
To be honest, that sounds like a PowerApps issue, the OData standard calls for true and false.

**Comment by juasanri** [comment]
Ok, thanks. It seems so, because it works in Power Automate, but not in Power Apps.
