### ISSUE TITLE
Could not publish Simple-Object-Designer App

### ISSUE THREAD

**Issue by tokyoronin** [hougaard/Simple-Object-Designer#51]
I got a failure. Could not add fields.
This error message showed up:  Package deployment failed due to the following error(s): Failure status code ServiceUnavailable returned - Job Id : 280f6e7b-ba48-43ab-b298-f629564ac8df

What does it mean? @hougaard

**Comment by hougaard** [comment]
Sounds like Microsoft is having an issue "service unavailable"... Wait a bit and try again.
