### ISSUE TITLE
Change hover over text field. Is it possible with SOD ?

### ISSUE THREAD

**Issue by tokyoronin** [hougaard/Simple-Object-Designer#53]
Every field in BC has a helper pop-up when you hover over it. I am wondering if I can also add some explanation to my SOD-created fields, so that when my users use my fields they can get a hint about best practise.

![Bildschirmfoto 2022-03-18 um 09 50 47](https://user-images.githubusercontent.com/92306028/158967952-ef8b4456-2a75-41d5-9a32-1809191551f1.png)

**Comment by hougaard** [comment]
Great idea, let me see what I can do about that.

**Comment by hougaard** [comment]
Included in the next version (1.0.0.129)
