### ISSUE TITLE
Lookup Field

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#55]
Hello,

I understand the limitations of the lookup fields when there is more than one primary key. But could this be solved by adding some more restrictions to the lookup field? For instance making some mandatory extra lookup fields to have all the primary keys needed in order to the final lookup? Something like "to enable this lookup, the following lookup fields need also to be added".

Thanks

**Comment by hougaard** [comment]
The challenge is, that it's very easy to transition from "Simple" to "Complicated Object Designer", I we don't want that - So right now, we'll stick with one field...

Sorry.

**Comment by juasanri** [comment]
Understood, you are right, thanks!
