### ISSUE TITLE
Question regarding field with extended data type

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#57]
Hello,

I have created fields with the "extended data type" set to "URL", which is an incredibly great function for us, thank you!

I have marked those fields as read-only, they are filled in with a power automate flow.

But I have a question. When I place such a field in Business Central original table, I can only click on the web page referenced by the field if the document is in read-only state, while if it is in edit state, I cannot click on it to open the web page:
<img width="537" alt="Captura de Pantalla 2022-03-21 a las 19 50 20" src="https://user-images.githubusercontent.com/99739571/159343401-64bb78dd-b635-41de-ba85-581b351198a0.png">
<img width="522" alt="Captura de Pantalla 2022-03-21 a las 19 50 45" src="https://user-images.githubusercontent.com/99739571/159343481-c716a792-1dd1-4c5a-94d7-a16a8d310a10.png">

However, when I place such a field in a feature created with the SOD, I can click and open the web page always, it doesn't matter if the document is in edit state or read-only.

<img width="361" alt="Captura de Pantalla 2022-03-21 a las 19 52 15" src="https://user-images.githubusercontent.com/99739571/159343746-3994f339-d24b-4380-a812-d8806b6b8279.png">
<img width="359" alt="Captura de Pantalla 2022-03-21 a las 19 52 30" src="https://user-images.githubusercontent.com/99739571/159343751-b8ab7aab-26c8-4ebf-8386-fc9c07431f93.png">

Which is much much better :).

Is there a way to control this in Business Central original tables?

Thanks again for your time.

**Comment by hougaard** [comment]
Unfortunately not, when adding fields to a page, you're playing by the rules of the hosting page. There's no different in the code between the two, the only difference is the host page with whatever happens on that page.
