### ISSUE TITLE
Report not available

### ISSUE THREAD

**Issue by DogmatixAU** [hougaard/Simple-Object-Designer#58]
Can you please add report 208 Sales - Shipment into the list of reports that a customer can add to?

**Comment by hougaard** [comment]
Sorry, the report will show up on the tables that are on that report. 

In case of 208, that would be table 110 (Sales Shipment Header) and 111 (Sales Shipment Line)

So if you want to add fields to the report, then you must add to 110 and 111 (and 36/37 with transfer to 110/111)
