### ISSUE TITLE
Suggestion / Request

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#59]
Hello,

Is it possible to create a feature that shows the list page with indentation? Like the BOM structure?

Thanks

**Comment by hougaard** [comment]
Perhaps, what's the use case?

**Comment by juasanri** [comment]
The use case is to give my production people an easy way to see the BOM structure in order to assign items in a production order.

The current production order is challenging for them with our item BOM structure level. 

And more than that, I would need a premium license for every person in the production team in order to assign items in a production order, while if I create a feature with this type of indentation I just need Team Member licenses for them in order to check what they have consumed in the production.

And from that information I can fill myself the production order. Currently we are doing this with different paper reports that they use and return to me, but it is not the ideal situation at all (and sometimes papers are just lost :)

An option I am also thinking is doing something outside in Excel, but it would be better to have it integrated in BC.

Thanks for listening

**Comment by hougaard** [comment]
But your team members can see the BOM structure from the Item List/Card using the "BOM Structure" action?

**Comment by juasanri** [comment]
Yes, they can.
So my idea was to replicate this table in a feature, with a checkbox extra, so they can just mark "done".
Our production is make to order, and from the order it takes 4 months to build the final item, so I need to keep updating what has been done in the production order to have an updated stock.
The other idea is to replicate it in Excel with Power Automate, but I cannot indent neither put checkboxes in Excel for readability (one final item can have more than 400 items inside in different levels).
Paper till now has shown to be a poor solution :)
Thanks

**Comment by hougaard** [comment]
I see. I think this is outside of the "simple" definition of the Object Designer :)

**Comment by juasanri** [comment]
Ok, thanks!
