### ISSUE TITLE
Add native field to another table

### ISSUE THREAD

**Issue by GrooveRings** [hougaard/Simple-Object-Designer#6]
Does the current functionality of the app allow for the placement of native fields on tables where they are not currently placed. For example, I'd like to be able to see the Vendor Name for purchase invoices posted with a payment method code when I drill into GL bank account activity (GL Entry table). I see the Vendor No. but that's not helpful without clicking into each Vendor No.

![image](https://user-images.githubusercontent.com/82909149/115639950-76d2dc00-a2db-11eb-9c03-541d61b51b26.png)

**Comment by hougaard** [comment]
Not yet, but there's a great extension in appsource called G/L Source Names https://appsource.microsoft.com/en-us/product/dynamics-365-business-central/PUBID.objects4nav%7CAID.717235da-2f3f-4e5a-95cd-4d6b7371068f%7CPAPPID.479e77f3-031a-49fe-bb6a-314464c6a9a8?tab=Overview

**Comment by igorkovski** [comment]
@GrooveRings , I was looking for the same solution for the GL/Customer entries table. The solution actually is quite simple. Go to Sales & Receivables Setup - see below, and make sure you select "Copy Customer Name to Entries". There's a similar option that's available under Purchases & Payables Setup.
![image](https://user-images.githubusercontent.com/7134359/124975673-dcd62200-dff3-11eb-984a-16d39322d977.png)
