### ISSUE TITLE
Create Multiple Apps

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#61]
In the latest version of SOD do we have the option to create multiple apps?

The problem we are facing is within our current app file we have created fields on pages that have no interaction/dependencies with our support company dev team, but at the same time have created some fields that do have interaction/dependencies on their apps.

Right now all the fields we created in SOD are within one app file so whether the fields are added with or without interact/dependencies, if our support company needs to reference a field we created that doesn't have any interaction/dependency with theirs it still creates loop and problems when deploying the apps.

**Comment by ScottB-Ronco** [comment]
Do you have an answer for this?

**Comment by ScottB-Ronco** [comment]
For example I created a field called allow backorders on customer card. The dev team at our support company is creating a new screen for us item information card. We want them to display this field on this screen in their app.

They are telling is it creates an dependency issue or loop so to speak that when a system is updated if our extension is not installed it creates a deployment issue for them and if I have field that is created on one of their screens but their app is missing then it creates a deployment issue for me.

So what I would like to know is if SOD has the ability to allow us to to maintain multiple apps. So any fields I create that have dependency on their extension or vice versa can be kept in its own app file extension.

An option like this would be practical as well when it comes to using your new features option. If I wanted to create a whole new page and tables like you showed in your YouTube video with the Veterinary. We could create separate apps for each and keep things separate.

**Comment by hougaard** [comment]
Make sure you're not ending up with cyclic references (A is dependent on B and B is dependent on A).

And if you want to show your new fields on their pages, do that with the Object Designer in you app.
