### ISSUE TITLE
Item Attributes into Reports

### ISSUE THREAD

**Issue by Joseph-Candava** [hougaard/Simple-Object-Designer#62]
Thanks for the help from your simple object designer, it is quite a powerful extension when it is working as intended.

I have received a request to place item attributes containing specific item attribute names (table 7500) and display their value (table 7501) onto a printed report and I couldn't find the way to do this using your extension.

Is there a way I can be able to specify an item attribute name like "inner quantity" or "outer quantity" and then be able to get the item attribute value to show up on a sales order report such as a Sales Return Order Line Subform (table 6631) ?

**Comment by hougaard** [comment]
Item Attributes are a big pain, the table structure is very un-BC. This is unfortunately not "simple" and way beyond the object designer's capabilities.
