### ISSUE TITLE
Issue with List Feature: not able to see them any more

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#63]
Hello,

I have an issue with my features created with the SOD. All of a sudden, we can no longer view the list page in Business Central. We can access it, but it seems blank.

![image](https://user-images.githubusercontent.com/99739571/161498404-b6cfdf18-273d-4b51-85f8-1b4cb2b0c71a.png)

I have checked via configuration package that all the information is stored in the table.
I can create new items, and the card is shown.
The API is also working properly and can retrieve the data from Power Automate.

Things we have done before it started to happen:
- Publish the app with the SOD with the language set to Spanish, instead of English (this gave me problems a few weeks ago, but by mistake I published the app with the language set to Spanish a couple of days ago).
- Change permissions to some users to see the tables of the new features.
- I am not sure if was just after the upgrade to SOD version .32

Things I have done after it is not working:
- Publish the app again with the language set to English. It made no difference.
- I have created a new field in one of my features just to check if this would made a difference, but with no luck. Still cannot see the lists I have created in Business Central

Any help or guidance will be greatly appreciated.

Thanks in advance.

**Comment by hougaard** [comment]
To support at hougaard.com

**Comment by juasanri** [comment]
Hello,

Please, find attached the app downloaded.

Thank you for looking into this!!

Best regards,

Juan

**Comment by hougaard** [comment]
Check your mail :)

**Comment by juasanri** [comment]
Thanks for doing the new release so fast, it solved the issue!!
