### ISSUE TITLE
Unable to publish in Demo

### ISSUE THREAD

**Issue by bmrankin** [hougaard/Simple-Object-Designer#65]
Hi Erik,
Trying to add a custom field and an API endpoint to test the demo but it will not publish.
Working in a Sandbox on BC online and receiving the following error 

```
The demo version of the Simple Object Designer only allows you to 
create 1 new field and one new API, please register to continue.
```

I have tried the following and received the error
- 1 field (Added to Item) added to Item Card and 1 API (Item)
- 1 field but not placed on a page and 1 API
- 1 API only
- 0 field and 0 API

Thoughts?
Thanks.
![2022-04-08_14-28-08](https://user-images.githubusercontent.com/5891981/162501101-6c7de956-0793-4f2e-9d29-8bb410316232.jpg)

**Comment by hougaard** [comment]
Use the **Inspect Tables**, use "delete customizations" on tables where you tried to add fields, but removed them again?

**Comment by bmrankin** [comment]
Thanks. That seem to let it publish. Waiting for the deployment but looks like it is good to go.

**Comment by bmrankin** [comment]
Thanks Erik.

One last quick question in testing the API for BC online with Postman 

Does this seem to be a path forward?
https://www.msnjournals.com/post/testing-business-central-online-apis-using-postman

**Comment by bmrankin** [comment]
Nevermind I think I found the official way.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps
