### ISSUE TITLE
Quote No

### ISSUE THREAD

**Issue by DogmatixAU** [hougaard/Simple-Object-Designer#66]
Hi.

I need to include the quote no on the sales invoice. Can you please include report #1306 Sales Invoice in the list of available reports to add to?

Thanks

**Comment by hougaard** [comment]
Report 1306 is available on table 112 (Post Sales Invoice Header)

For this to work, you'll have to add the same field to table 112 and specify a field transfer from table 36 to 112.

![image](https://user-images.githubusercontent.com/3357237/163275823-9cc36691-4b31-41ad-83d0-3c3c6122c8f2.png)

**Comment by DogmatixAU** [comment]
All good
