### ISSUE TITLE
Calculated Field

### ISSUE THREAD

**Issue by DogmatixAU** [hougaard/Simple-Object-Designer#67]
Is it possible to add a new field as a flow field - which is a calculation of other fields on from the same record

eg I want to have a fields for remaining qty on the order line - qty ordered less qty previously shipped

**Comment by hougaard** [comment]
Not yet, that's coming, we're working on it, but I cannot say when yet.... But don't hold your breath, it's going to be a while (It's complicated to make that "simple").

**Comment by Eric-NL** [comment]
I would really love to see that option!

**Comment by atrayf** [comment]
Is there any progress on this -It really would be the icing on the cake !

**Comment by hougaard** [comment]
Scheduled for "spring'23", working on it :)

**Comment by atrayf** [comment]
that would be great. Looking forward to it...

I've been a NAV/BC consultant for 20+ years and have found it very frustrating that I can't add/expose the odd field without referring to a developer of pratting around in Visual Studio, so this tool is looking very interesting.
My Development Director has just approve the purchase of a licence, so hopefully I will have it to use in the new year.
Do you have any licence options for resellers by any chance?

**Comment by hougaard** [comment]
Send an email to sales@hougaard.com, and Signe will hook you up with a reseller agreement.

**Comment by atrayf** [comment]
thanks - email sent

**Comment by DogmatixAU** [comment]
Erik - what do you mean by "Spring 23"? April-ish?

Im in Aus- so that doesnt phrase doesnt translate well.


Michael Inga

ERP Practice manager

[Smart Phone]   0418 926 687



________________________________

**Comment by hougaard** [comment]
My spring, april'2023

**Comment by hougaard** [comment]
This was released a while back, closing issue.
