### ISSUE TITLE
Transfer GL SOD fields to sales & purchase invoices

### ISSUE THREAD

**Issue by DogmatixAU** [hougaard/Simple-Object-Designer#68]
At the moment you can add a field to an item and have that item transfer to the sales lines. But clients don't always sell by items. Sales are sometimes by GL code only.

Could you expose the sales line tables and reports to allow for SOD fields to flow/transfer to these?

Example - My client has a second long description for their items, and that transfers to the sales line and sales documents. But when a prepayment invoice is created, it only generates a GL line, so the long description field on the sales line is not field. Prob is that in BC the same doc layout is used for normal invoices and prepayment invoices - so the long description is blank.

Ideally, if we could add a long description to the GL account and have the value transfer to the long descript field on the sales line - so it can be printed as well. Is that possible?

**Comment by hougaard** [comment]
Let me see if I can add a field transfer between GL Account and Sales Line.

**Comment by DogmatixAU** [comment]
Any update on this?

**Comment by hougaard** [comment]
That will be part of the next version, eta, late next week.
