### ISSUE TITLE
How to modify drop lists

### ISSUE THREAD

**Issue by DogmatixAU** [hougaard/Simple-Object-Designer#69]
When creating a sales quote/order/invoice - you have a drop list of items to select from. I want to be able to change the columns in that from list (eg show current qty bal without having to open the item card). 

I believe this drop list is Sales Quote (41, Document) - I dont appear to be able to add extra inventory fields (table 27) to this form though.

Is this possible? If so, how?

**Comment by hougaard** [comment]
Not even with code it's possible to change the column. There's a limited option to add columns, but that's it.
