### ISSUE TITLE
"The record is not open" when publish it

### ISSUE THREAD

**Issue by SmallBigear** [hougaard/Simple-Object-Designer#7]
After changed the fields, pop up "Publish to this environment?", select yes, then feedback "The record is not open."
would you please help about it, thanks!

**Comment by hougaard** [comment]
Sorry to hear about this, what did you change on the field?

Please use the **View the last known error** under help & support, and paste the information here:
![image](https://user-images.githubusercontent.com/3357237/120823704-8a917500-c50c-11eb-99be-6cadc694c9d3.png)

**Comment by SmallBigear** [comment]
Hello,

Thanks for the support, there is nothing in the last know error, please find the screenshot below.

Here are what i did on the field:

  *   Create a field, place it on one page, publish, success
  *   Change the field, but not delete it
  *   Then the system remind me something, i just ignore it without check the details, that is my fault
  *   Create a new field, place it on some page
  *   Then i try to publish it, then the error happens

I tried to uninstall it, and then install simple object designer again, this error still there.

***@***.***D75966.711A6350]

**Comment by hougaard** [comment]
You cannot "change" the following properties of an already published field:

1. Name
2. Type
3. Size
4. (Option members)

If you ignored the warning, then you must uninstall the "new fields" extension and remember to toggle the remove data option.

**Comment by SmallBigear** [comment]
Thanks!
Would you please let me know where to uninstall the “new fields” extension?
I don’t remember i installed it before, i only installed “simple object designer”

**Comment by hougaard** [comment]
That's the extension the object designer creates with your field in it. Open Extension Management, then you be able to locate it.

**Comment by SmallBigear** [comment]
Thanks!
Solved finally!

**Comment by SmallBigear** [comment]
thanks
