### ISSUE TITLE
Transferring "Percent Completed" Field from Job to Time sheet

### ISSUE THREAD

**Issue by teganZT** [hougaard/Simple-Object-Designer#70]
My users wish to see the field "Percent Complete" in the time sheet line (951) table. This field is confusing me because it does not live in the Job table (167), instead there appears to be a separate table named "My Job" (9154) that holds percent completed.

When I try to lookup the percent completed field from table 9154 to add it to table 951, I get the error "My Job cannot be used as a relation (too many fields in the primary key)". Does this mean it is impossible to place any fields from this table on a new page? I don't really understand why there are different tables for Job and My Job, and why only My Job can display the % completed even though it is visible in the Job list.

Are there any other alternatives that will allow my users to see how many more hours are budgeted on a job in their time sheet lines?

**Comment by hougaard** [comment]
Percent Completed is not a field. It's a calculation done by codeunit **Job Calculate Statistics**.

So the short version: It's far from "simple", sorry.
