### ISSUE TITLE
Error when publishing extension

### ISSUE THREAD

**Issue by gmotion** [hougaard/Simple-Object-Designer#71]
Hi,
I exposed 7 tables using "Expose Data as web service API". when I am done and go to publish the extension, it fails and the error is:
Unexpected error. There was an unknown error when attempting to deploy the extension. Try to deploy again.

thank you,
ghassan

**Comment by hougaard** [comment]
Please use the "download source" from the setup and and send that zip file to support(at)hougaard.com

**Comment by hougaard** [comment]
Reply sent back, issues:
- API names are too long, please shorten them (I'll create a proper fix for this in a coming version).
- "area" field is making trouble, please check that you're running the latest version of the Object Designer. That bug should have been fixed.

**Comment by hougaard** [comment]
.. and when I say "API names" I actually mean the "entity name".
