### ISSUE TITLE
Issue: Shipping service order ERROR after adding fields to Service Header and Service Shipment Header

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#72]
Hello again Erik,

I have created new fields in the Service Header, as well as in the Service Shipment header.

The publish has been ok, and I can see my fields, but now when I try to Ship on of my service orders, (Post --> Ship), BC throws an error that says that two of my new created fields should be of the same type (¿?). On is the one created in the Service Header, another one in the Service Shipment Header:

![image](https://user-images.githubusercontent.com/99739571/165303844-cde91609-6b73-44cb-974f-e23acd4af224.png)

The error Call Stack is the following:

![image](https://user-images.githubusercontent.com/99739571/165303909-81892d9c-e5dc-42cb-a140-9f581b57c30f.png)

Could you suggest me some actions please? We are now stopped because we cannot Ship neither Invoice Service Orders.

If needed, I can share with you by mail the .json file of my application.

Thanks in advance!!

**Comment by hougaard** [comment]
Change the field number of one of the fields... BC tries to auto-transfer in some cases if there's fields in both places with the same field number.

**Comment by juasanri** [comment]
This solved my issue.

Thanks for this fast answer!!
