### ISSUE TITLE
Error: Field does not exist

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#73]
Hello again Erik,

Yesterday I fixed the issue I had by changing the field numbers of the Service Shipment Header to something different than the ones I had in the Service Header, so BC didn't try to transfer fields from the service order to the service shipment when doing the Post->Ship.

This worked yesterday, but today I was creating new fields in the Service Header, and I have had an error:

![image](https://user-images.githubusercontent.com/99739571/165532729-d07c32f0-1d98-4f71-adfc-7679c46ed828.png)

The setup of my SOD says that the starting number for fields and tables is 60000. The Service Shipment Header field number that I changed yesterday were 60000, 60001 and 60003, so I changed the numbers to 60005, 60006 and 60008.

So the Service Header fields start in 60000, and Service Shipment Header goes from 60005 to 60008

Now my new field created in Service Shipment Header is 60009, but I get this error.

Could you help me please?

The version of my SOD is 4.0.0.135

Thanks in advance.

**Comment by juasanri** [comment]
I have gone back to my previous version of the json of the SOD, that publishes succesfully yesterday after changing the numbers of the fields, and now it is not publishing succesfully any more, just getting the same error.

Thanks in advance.

**Comment by hougaard** [comment]
Please email me the "Download Source" (from Setup), and I'll take a look!

**Comment by juasanri** [comment]
Here you go!

Thanks,

Juan

**Comment by juasanri** [comment]
Issue solved, thank you for your help!
