### ISSUE TITLE
Small feature suggestion: Schedule publishing

### ISSUE THREAD

**Issue by teganZT** [hougaard/Simple-Object-Designer#75]
Hi Erik,

It would be useful if the object designer allowed a feature to be scheduled for publishing. When a new field is placed on a page, all users have to refresh their page and potentially lose work. To get around this I push new fields when nobody is working. 

If there was a "Publish Later" option, I could schedule my fields to push to the live environment at midnight and nobody's work would be interrupted.

**Comment by hougaard** [comment]
Great suggestion.

I'll make sure there's a codeunit you can put in the job queue for that.
