### ISSUE TITLE
BC update 20.1 Automate action in pages and tables

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#76]
Good morning,

Our BC environment has been updated to version 20.1 and a new feature that we were expecting has been released: it is the ability to trigger power automate flows for a selected record.
In Microsoft documentation it says that the "Automate" option should appear in any page:
![image](https://user-images.githubusercontent.com/99739571/169479952-aedfd579-ccd6-4177-a4e6-c54238776948.png)

And it does, but not for the new "features" we have created with the SOD:

![image](https://user-images.githubusercontent.com/99739571/169480074-202cb716-b73d-4cfc-b476-0b63c58245d4.png)

Is there any way to setup the new created features with the SOD to show this menu? Or is it in Microsoft hands?

It would be extremely helpful for us.

Thank you very much.

**Comment by hougaard** [comment]
This is in Microsoft's hands, the pages created with SOD are correct and compliant.
