### ISSUE TITLE
adding filter to API call

### ISSUE THREAD

**Issue by ghassanm** [hougaard/Simple-Object-Designer#77]
Hello,
When using filter on calls to API published by Business Central, the filtered call works. Example:
https://api.businesscentral.dynamics.com/v2.0/Tenant ID/Integration/ODataV4/Company('DiCentral%20Testing%2002-22-22')/Chart_of_Accounts?$filter=No eq '10200'
This will return one record. 
When I use filter on API published by Simple Object Designer, the filters don't work example
https://api.businesscentral.dynamics.com/v2.0/Tenant ID/Integration/api/hougaard/FHF/v2.0/transfer_Lines?Company=DiCentral%20Testing%2002-22-22?$filter=DocumentNo_ eq '1002'

I get this error.
{
    "error": {
        "code": "Unknown",
        "message": "The supplied company name is not valid.  CorrelationId:  724f8332-2bf8-4223-9274-f0b0acfe0437."
    }
}

I tried several "syntax" combinations, and nothing worked.  Please help!

Regards,
ghassan

**Comment by hougaard** [comment]
> 2-22?$filter=

The second question mark should be an & 2-22&$filter=
