### ISSUE TITLE
Errors while adding new fields to tables

### ISSUE THREAD

**Issue by igorkovski** [hougaard/Simple-Object-Designer#8]
Erik, I'm having issues adding new fields to tables. Once I added a field table name, then I delete the record from SOD, then add that table again, the software gives me a validation error stating that I already have a field "Sample Field, two fields cannot be named the same." Why would this come up if I've already deleted the record? Thanks, Igor

**Comment by hougaard** [comment]
Was it deployed in the meantime? Then you might have to uninstall the new fields extension.

**Comment by igorkovski** [comment]
Hi Erik, no not deployed just yet, I'm adding the fields currently, and as soon as I add the second field, the system throws a validation error stating that I've already added the field. It doesn't matter what I name it, it just keeps saying I've added it already. This is happening in the insurance table - 5628

**Comment by hougaard** [comment]
I'll check tonight if there's something funky going on...

**Comment by igorkovski** [comment]
That would be great. Thanks Erik. I imagine that I can publish the extension after adding all of the necessary fields. In other words, I should be able to add 5 fields and publish them, and not add 1 field - then publish, then another field - then publish.

**Comment by hougaard** [comment]
Correct.

**Comment by igorkovski** [comment]
Erik, I ended up purchasing the app, however I'm wondering whether the fact that I purchased it using my personal email is causing the issue? I would think not but maybe you can take a look at that. Also, where do I go to add the license key, I cannot seem to find the configuration...THanks!

**Comment by hougaard** [comment]
Click on the "purchase link" on the main page of the designer, then you should be able to enter the license key.

**Comment by igorkovski** [comment]
Erik,

I found a workaround, I add a field (get an error), then switch the table, (all is well) then switch it back to the initial table that I wanted to add the field too it. It seems to work fine that way. 

By the way, do you happen to have a little tutorial regarding on how to reconfigure the config package once you're done with an extension project, and you have to setup a new project/extension? I keep running into failed deployment errors.

Thanks,
Igor

**Comment by hougaard** [comment]
Found the bug... Submitting to Microsoft now...
