### ISSUE TITLE
How do i remove or correct table

### ISSUE THREAD

**Issue by Debej** [hougaard/Simple-Object-Designer#80]
I created a table (50820) via the Create New Features along with a Card and list. I realised i incorrectly set up the wrong field as the primary field.
I then manged to delete the table from the Features list but the table still resides in the table list.
I cant customize it there as it says i have to do it on the features card but it no longer exists in the Features card list.
i tried to readd it but it resulted in another table and errored when publishing.
How do I remove the table and any associated pages?
I have sent the zip of the source to support

**Comment by hougaard** [comment]
You'll need to deploy the .app manually if it contains breaking changes. 

1. Save the .app that gets downloaded when you publish from the Object Designer
2. Go to Extension Management
3. Select "Upload Extension" and select the .app you saved in step 1
4. Select "Force" in Schema Sync Mode

<img width="457" alt="image" src="https://user-images.githubusercontent.com/3357237/173243553-fac6766a-e13e-43c7-b721-048a983b644a.png">

5. Accept privacy policy and click deploy

Now Business Central will deploy you extension and perform any destructive (such as deletion of a table) operation needed.

**Comment by Debej** [comment]
Hi Eric thanks for your quick response. I manually loaded the app and it said deployment failed. However it did remove the table and added another one i created but now when i try to publish it fails each time. i have emailed the App to you

**Comment by hougaard** [comment]
On the failed deployment, what was the error? (click details on the deploy card)

**Comment by Debej** [comment]
Deployment failed. Errors: App ID : f1145dd3-e0cd-46a5-80e5-2fedf363629f Message : { Extension compilation failed
TableExtensions/Product_GroupsSOD_TableExt.al(1,22): error AL0334: The extension object 'SODProduct_GroupsSOD' cannot be declared. Another extension for target 'Product_GroupsSOD' or the target itself is already declared in this module. } - Job Id : f1f55e09-fa6e-4848-8311-9f5d8befc1c6

**Comment by hougaard** [comment]
Hang on, I think you might have used the "Add fields" to a feature(new table) you have created?

That's not allowed by Microsoft. If you want to add more fields to an already created table(feature) then you can just go and add the new field to the feature instead of using "Add field to existing tables".

To fix this, please delete the field from "Add field" and add it on the feature card for the product groups table.

**Comment by Debej** [comment]
No It doesn't let you - it advises it has to be done via Features

**Comment by hougaard** [comment]
Please use the "download source" from the Object Designer Setup Page, and send me that file?

**Comment by hougaard** [comment]
> No It doesn't let you - it advises it has to be done via Features

And it shouldn't, but sometimes users surprise me with their creativity :)

**Comment by Debej** [comment]
Regards


Debbie Jones
Group Systems Administrator
p: +61 2 4230 8029 | m: +61 402 330 335
e: ***@***.*** | w: www.kollaras.com
a: PO Box 424, Figtree NSW 2525 Australia

​Please note our postal address has changed
 Please consider the environment before printing this email.
_____________________________________________________________________________________________________
DISCLAIMER: This email and any files transmitted with it are confidential and may be the subject to copyright. They are intended solely for the use of the individual or entity to which they are addressed. If you have received this message in error please notify the Kollaras Group immediately by return email or by calling +61 (0)2 4230 8000. Any views or opinions expressed in this email are solely those of the author and do not necessarily represent those of the Kollaras Group except where an authorised sender specifically states them to be views of the Kollaras Group. It is your responsibility to verify this email and any attachments for the presence of viruses. The Kollaras Group accepts no liability for any damage caused by any virus transmitted here.

**Comment by hougaard** [comment]
You cannot attach it here, please send it to support@hougaard.com
