### ISSUE TITLE
Deployment Failed on custom table

### ISSUE THREAD

**Issue by terrancehenry** [hougaard/Simple-Object-Designer#81]
I'm attempting to deploy an api that will expose a custom table.  I am getting the following error.  Any help would be appreciated.

Deployment failed. Errors: App ID : aac1022a-20d7-4c96-b172-47628d5aef8f Message : { Extension compilation failed
API/proof_SOD.APIPage.al(15,19): error AL0185: Table '"Proof"' is missing
API/proof_SOD.APIPage.al(14,22): error AL0307: Property value cannot be validated because the source table is unreachable.
API/proof_SOD.APIPage.al(25,27): error AL0118: The name 'Rec' does not exist in the current context
API/proof_SOD.APIPage.al(23,13): error AL0429: A repeater control can only be added to pages that have a source table. } - Job Id : 6d8d5ad8-26a7-4ccd-8363-0cda89df04d7

**Comment by hougaard** [comment]
Are you running the latest version of the Object Designer (Check in Admin Center), if not, please update?

+ Please update your symbols from the Object Designer Setup page (answer Yes to clear the cache completely)

**Comment by terrancehenry** [comment]
Hi Erik,
I just installed it yesterday so it's up to date.

**Comment by hougaard** [comment]
OK, then please refresh the Symbol... It seems that the Object Designer fails to identify what other Extension the "Proof" table is from....

**Comment by terrancehenry** [comment]
I refreshed the symbols and started the publish again.  It returned the same result.

**Comment by hougaard** [comment]
Do me a favour, please go to the setup page and use the "Download Source" and send that ZIP file to support@hougaard.com - Plus, information on what extension the Proof table is coming from?

**Comment by hougaard** [comment]
The issue turned out to be an API page without any fields. A check for this case will be added to version 5.0.0.144 of the Object Designer.
