### ISSUE TITLE
Your extension needs updating your extension is not compatible with version 20.4.43015.0. 

### ISSUE THREAD

**Issue by ghassanm** [hougaard/Simple-Object-Designer#85]
This extension was working fine before the attempted update by Microsoft. Now I am getting the below error.
The compatibility issue must be resolved before the environment for which the extension is installed can be successfully updated to version 20.4.43015.0. 
Name: My Customizations
Version: 1.0.0.5
PageExtensions/General_Ledger_Setup_PageExt.al (12,17) - Error AL0272: The anchoring symbol '"Bank Recon. with Auto. Match"' must be a **grouping symbol.** 

I checked the error list and didn't find additional information 
The anchoring symbol '{0}' must be a grouping symbol.
Description: An anchoring symbol must be a grouping symbol.

I couldn't find anything else on this error. any help is appreciated.

Regards,
Ghassan

**Comment by hougaard** [comment]
That means, that the field you have placed on the General Ledger Setup page has an "anchor" that's not valid. If you use AddFirst or AddLast, then the anchor has to be a "group" style control.

**Comment by ghassanm** [comment]
Hi Erik,
This is what I had on the setup card.
***@***.***
Addlast was already there under where. Did I screw up somewhere else?
Regards,
Ghassan

**Comment by hougaard** [comment]
I cannot see screenshots unless you paste them directly into the github page, click on "view it on github.com" where you started the issue and paste it there.

**Comment by ghassanm** [comment]
<img width="436" alt="image" src="https://user-images.githubusercontent.com/1273245/176741405-ccb260fa-4c3f-4f39-b1ba-cd7b70ad5ffd.png">

**Comment by ghassanm** [comment]
Thank you, by the way, is there a list of new features in the upcoming updates? I don't want to code, I love this App. this is the real citizen developer :)

**Comment by ghassanm** [comment]
Thank you, by the way, is there a list of new features in the upcoming updates? I don't want to code, I love this App. this is the real citizen developer :)
