### ISSUE TITLE
Error when uploading published SOD app into different environment

### ISSUE THREAD

**Issue by DogmatixAU** [hougaard/Simple-Object-Designer#86]
Hi. I have amended a report layout (1306 Sales Invoice) to add extra fields. I then publihsed the change and exported the app.

But whenever I uploaded the app into different environment, it fails - with the following message. 
   Unexpected error. There was an unknown error when attempting to deploy the extension. Try to deploy again.

The SOD environment is 20.2.41144.41547 and the receiving environment is 19.3.34541.35247.

I have also tried to create in 19.3.34541.35247 (sandbox) and upload into same (Production) but same error.

Can you help? My client cant send invocie until this is sorted.

**Comment by hougaard** [comment]
You should never get an error like that from the same environment. If you do cross-environment deployments, you could encounter "strangeness". Do your 19.3 environments have the same versions of dependent extensions?

**Comment by DogmatixAU** [comment]
Erik – Still getting the error. Tried uninstalling & reinstalling etc – no luck.

BTW – our license is up today. But I cant find any link to renew the license. Can you advise?


Michael Inga
ERP Practice Manager
0418 926 687

**Comment by hougaard** [comment]
Renewal is done just by purchasing a new one-year license key from hougaard.com.

Please email the .app file to support@hougaard.com if the deployment fails, and we will take a look at it.
