### ISSUE TITLE
Repeated failures when trying to push extension

### ISSUE THREAD

**Issue by teganZT** [hougaard/Simple-Object-Designer#87]
Hi Erik,

I am having a repeated failure trying to add a field. I think what triggered the error was my attempt to place "Order No." (66) on table "Sales Cr.Memo Line" (115). I want to be able to see which order a credit memo is connected to on its page and in reports. However, I get this error: 

```
Package validation failed due to the following error(s): ReportExtensions/Sales___Credit_Memo_ReportExt.al (8,56) - Error AL0118: The name '"Order No."' does not exist in the current context
ReportExtensions/Sales___Credit_Memo_ReportExt.al (1,56) - Error AL0247: The target Report "Sales - Credit Memo" for the extension object is not found - Job Id : 071d181b-a92f-48e2-bc1e-46c8f4135aa6
```

I attached the .txt file, Github will not allow me to attach the .app. Two questions I have:

1. How can I make the Order No. field appear on the Sales Cr. Memo?
2. When I get an error like this, how do I clear it out so I can add other fields? Any new fields I try to add still give me this error. In my sandbox I chose "Init new app" thinking that would get rid of my erroneous fields, but that just lead to more errors.

Any assistance you can provide would be appreciated, thank you.

[Result{8AF72E66-0C34-4B5A-8041-3613E59D817B} (1).txt](https://github.com/hougaard/Simple-Object-Designer/files/9086613/Result.8AF72E66-0C34-4B5A-8041-3613E59D817B.1.txt)

**Comment by hougaard** [comment]
Are your symbols fully updated? Perhaps refresh from the Setup and answer yes to clear cache first?

**Comment by teganZT** [comment]
When I removed the changes and cleared cache that allowed my other updates to go through, thank you. Can tell me why the error is occurring with the Credit Memo lines?

**Comment by hougaard** [comment]
Are you still getting this error?
