### ISSUE TITLE
Modify additional field properties 

### ISSUE THREAD

**Issue by CMouat** [hougaard/Simple-Object-Designer#88]
Currently the only property we can edit is the caption of a field. It would be nice to be able to modify more field properties, like setting a field that is currently visible to be hidden if I don't want users to see it. I tried using the hidden field that is in there currently, but that doesn't seem to work with existing fields since it's not modifying them.

**Comment by hougaard** [comment]
... the challenge is that "hidden" is a property of the field placed on the page, not a property of the field itself.

**Comment by hougaard** [comment]
... We have been very careful about adding "destructive" options, but customizing existing fields on pages is on our list, but the ruleset surrounding fields on pages is quite complicated, and we have a mission statement of "simple", it's even in the name ;)
