### ISSUE TITLE
Failed uploads of new extension

### ISSUE THREAD

**Issue by igorkovski** [hougaard/Simple-Object-Designer#9]
Erik, do you happen to have a little tutorial regarding on how to reconfigure the config package once you're done with an extension project, and you have to setup a new project/extension? I keep running into failed deployment errors.

**Comment by hougaard** [comment]
You much include all the tables (postfixed with Hgd) tables in a config package.

The base design is really aimed at the app handling a single environment. So if you do multiple apps, make sure you're deleting the setup page (it get a new App Id). (Check the ID field with page inspector on the Object Designer Setup Page).

**Comment by igorkovski** [comment]
I see, so what you're saying is that SOD allows for 1 extension to be built (with multiple tables/pages etc) within 1 development environment, or did I misunderstand that?

**Comment by hougaard** [comment]
No, that's the intention of the app. What I find is that even developers now are no longer "mixing" customers in the same development environment, if you work on a new customer, you fire up a new sandbox.

**Comment by igorkovski** [comment]
Ok sounds good. Thanks Erik.
