### ISSUE TITLE
Publish Error

### ISSUE THREAD

**Issue by MaxPowerPlatform** [hougaard/Simple-Object-Designer#90]
I tried publishing my first API and got the following error.
' ' is an unexpected token. The expected token is ';'. Line 1, position 170.

Internal session ID: 
02e37ae8-0c8b-4447-ad4e-17625a15eee3

Application Insights session ID: 
1b5d1ed4-b1be-4b78-8474-8af9cc13963f

Client activity id: 
594f1823-5adf-47bb-a738-355672dfd2b5

Time stamp on error: 
2022-07-15T14:07:44.3183923Z

AL call stack: 
"Extension Operation Impl"(CodeUnit 2503).UploadExtension line 7 - System Application by Microsoft
"Extension Management"(CodeUnit 2504).UploadExtension line 2 - System Application by Microsoft
"Build Extension Hgd"(CodeUnit 70310250).InstallExtension line 4 - Simple Object Designer by Hougaard
"Build Extension Hgd"(CodeUnit 70310250).CreateExtensionEx line 482 - Simple Object Designer by Hougaard
"Object Designer Menu Hgd"(Page 70310263)."ExportExtension - OnAction"(Trigger) line 6 - Simple Object Designer by Hougaard

**Comment by hougaard** [comment]
Please go to the setup page, and use "Download Source", send the downloaded zipfile to support@hougaard.com, and we'll take a look.
