### ISSUE TITLE
API calls returns only the "@odata.etag" line and "id" line.

### ISSUE THREAD

**Issue by gmotion** [hougaard/Simple-Object-Designer#91]
Hi Support,
When calling API generate by SOD, it only returns a list made up of two lines. When calling native BC published APIs, it returns all the fields in the endpoint.

by the way, it works fine for transfer_Headers and transfer_lines which was created by SOD. It doesn't work for other calls.

**Actual Call**
https://api.businesscentral.dynamics.com/v2.0/6fd97b54-3483-4f7e-8d06-685564656d2d/Integration/api/hougaard/FHF/v2.0/sales_Shipment_Lines?Company=DiCentral%20Testing%2002-22-22

**Response**
{
    "@odata.context": "https://api.businesscentral.dynamics.com/v2.0/6fd97b54-3483-4f7e-8d06-685564656d2d/Integration/api/hougaard/FHF/v2.0/$metadata#sales_Shipment_Lines",
    "value": [
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODIwOTUzOTY2MTEzMTswMDsn\"",
            "id": "60f961f5-01ca-eb11-9f0a-000d3aec33ef"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODIxMzIyODkyMDcwMTswMDsn\"",
            "id": "cbf30c3e-bcc3-eb11-9f0a-000d3aec393f"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODIxNDUwNTM4MTAxMTswMDsn\"",
            "id": "d00f4bcf-aec3-eb11-9f0a-000d3aec3e81"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODE4MDc1NDQyNDI0MTswMDsn\"",
            "id": "12642b72-a7c4-eb11-9f0a-000d3aec3e81"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODE4MTYyNDY2NzY1MTswMDsn\"",
            "id": "d60348a9-6cd3-eb11-9f0a-000d3aec880f"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODE4Nzk1NDU5MjQxMTswMDsn\"",
            "id": "b13aba28-51b1-ec11-8aa5-002248a684aa"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODE4OTYzMjMxNDAxMTswMDsn\"",
            "id": "bb3aba28-51b1-ec11-8aa5-002248a684aa"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODIxMzM4NjU1OTEyMTswMDsn\"",
            "id": "2c909c29-54b1-ec11-8aa5-002248a684aa"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODIwMTY1MDk0MzQ1MTswMDsn\"",
            "id": "659fa308-57b1-ec11-8aa5-002248a684aa"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODIwMDgxMjA4MjY1MTswMDsn\"",
            "id": "7a9fa308-57b1-ec11-8aa5-002248a684aa"
        },
        {
            "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODE4NTM3NzA0MzkzMTswMDsn\"",
            "id": "869fa308-57b1-ec11-8aa5-002248a684aa"
        }
    ]
}

[BC API Calls.txt](https://github.com/hougaard/Simple-Object-Designer/files/9128701/BC.API.Calls.txt)

**Comment by hougaard** [comment]
And you have added fields to that API endpoint?

**Comment by gmotion** [comment]
Hi Erik,
Yes, I added all the fields for now.

Regards,
Ghassan

***@***.***

**Comment by hougaard** [comment]
Please go to the Setup Page and use "Download Source" and send me the .ZIP file downloaded.

**Comment by gmotion** [comment]
Hi Erik,
Here you go.

By the way, the calls to transfer_Headers and transfer_Lines works as expected.

Regards,
Ghassan

**Comment by hougaard** [comment]
Sorry, you cannot attach to the github.com email, gotta send a separate email to support@hougaard.com with the download.
