### ISSUE TITLE
License Upgrade

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#93]
Hello Erik,

I just renewed my license which is expiring on July 22 2022.

After payment it gave me a new license key. However when I go to SOD in BC and click on the Buy/Register it only shows the date the current license expires on.

Do I need to wait for it to expire before I can put in the new license key?

**Comment by hougaard** [comment]
Yes, please wait until your license expires, then enter the new key.
(We're working to improve the license process over the next 6 months)

**Comment by ScottB-Ronco** [comment]
OK thank you
