### ISSUE TITLE
Change field display name

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#94]
Is it possible to change the display name of a field in 365BC with SOD. I thought in earlier versions I saw this option but for the life of me can't remember where it is now or if I was just confused or imagining things.

For example change the display name on Sales Order for External Doc # to Customer PO #
![image](https://user-images.githubusercontent.com/87865315/180282536-895c6b15-7eb5-47c1-834f-9fd2016f9e21.png)

**Comment by hougaard** [comment]
Yes, go to "Place existing fields on pages" and use the "Field Properties" menu item to change the caption of an existing field.

**Comment by ScottB-Ronco** [comment]
Erik,

First thank you for quick response and reminding me where it was. 

With that I'll assume you mean to go to "Add existing fields to pages and reports".

Now I do see the field settings and and the caption field to where I can make the change.
