### ISSUE TITLE
Document Date from Job Planning Line (1003)

### ISSUE THREAD

**Issue by g0g11** [hougaard/Simple-Object-Designer#95]
Hi Erik, 

I am trying to transfer "Document Date" from "Job Planning Line (1003)" to a Sales Invoice. We need this field when we create a new "Job Sales Invoice". But that is not available in Simple Object Designer. It would be great if that can be also added to Simple Object Designer.

**Comment by hougaard** [comment]
That is not "simple" and is currently beyond the capabilities of the Simple Object Designer.

But it is an area we're looking into, but that's complicated because it will open up for breaking stuff.

**Comment by g0g11** [comment]
Thanks for your response. It will be great if that will be available in the future. This field is for us important to have it also on all sales lines, and currently that's not possible in BC. Will be great to solve that with Simple Object Designer.
