### ISSUE TITLE
Bad Request error message when I try to post from postman

### ISSUE THREAD

**Issue by ghassanm** [hougaard/Simple-Object-Designer#96]
Hi Support,
When I try the first 2 lines (tag and id) it works. When I add the rest if the body, it fails.

Response.
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid Request Body  CorrelationId:  5249d4af-a77d-4a0a-a4a3-a464f978b1dc."
    }
}

Body
{
    "@odata.etag": "W/\"JzIwOzExNDAwNzE0ODE5NzU1OTE4MjQzMTswMDsn\"",
    "id": "c2a22b30-db68-ec11-bf27-000d3a5dcaae",
    "PaytoName": "Innovative Packaging Group",
    "PaytoAddress": "Attn: Accounts Payable",
    "PaytoAddress2": "P.O. Box 540996 ",
    "PaytoCity": "",
    "ShiptoName": "3PL No Warehouse Shipment",
    "ShiptoAddress": "",
    "ShiptoAddress2": "",
    "ShiptoCity": "",
    "PostingDate": "2022-07-26T09:56:20.1790112-04:00",
    "OrderNo_": "PO-000007",
    "BuyfromVendorName": "Innovative Packaging Group",
    "BuyfromAddress": "Attn: Accounts Payable",
    "BuyfromAddress2": "P.O. Box 540996 ",
    "BuyfromCity": "",
    "PaytoPostCode": "75354-0996",
    "PaytoCounty": "TX",
    "PaytoCountryRegionCode": "US",
    "BuyfromPostCode": "75354-0996",
    "BuyfromCounty": "TX",
    "BuyfromCountryRegionCode": "US",
    "ShiptoPostCode": "",
    "ShiptoCounty": "",
    "ShiptoCountryRegionCode": "US",
    "DocumentDate": "2022-07-26T09:56:20.1790112-04:00"
}

**Comment by ghassanm** [comment]
Hi Support.
below is the request
https://api.businesscentral.dynamics.com/v2.0/xxxxxxxxxxxx/Integration/api/hougaard/FHF/v2.0/purch__Rcpt__Headers?Company=DiCentral%20Testing%2002-22-22

**Comment by hougaard** [comment]
Please report this issue at hougaard.com/support if this is still an issue
