### ISSUE TITLE
Package validation failed.  An Enum  field is not a valid field type

### ISSUE THREAD

**Issue by magsterrrr1** [hougaard/Simple-Object-Designer#98]
When publishing API for Custom Table I get the following error:

Package validation failed due to the following error(s):  Error AL0156: 'Rec."Status"' is not a valid field type

The field is type enum.  The enum it references is also a custom object.  

When I remove this field the API publishes normally.  However, I need to include this field in the API.

**Comment by hougaard** [comment]
Please go to setup and use the "download source", and send that file to support@hougaard.com
